### ISSUE TITLE
Progress bar using radix-ui

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#1023]

**Comment by annaisaacks** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role

**Comment by Enjoy2Live** [comment]
We can use Radix's UI progress bar
https://www.radix-ui.com/primitives/docs/components/progress

**Comment by Enjoy2Live** [comment]
moved to #1735
