### ISSUE TITLE
[Dev](User Profile) Onboarding Modal Next & back Button {Stepper Component creation}

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1033]
User Story:
As Nancy Newbie
I want to progress or go back to any part of an onboarding task
So I can navigate through the onboarding process

Acceptance Criteria:
Given I am on an onboarding task
When I click the next or back button
Then I will be able to continue to the next page or go back to the previous page of the onboarding task

Given, I am on an onboarding task
when I move through the task
then a progress bar will indicate which step I am on

Given different tasks will have a different amount of steps
when I am on a task with x amount of steps
then the progress bar will indicate there are x amount of steps

**Comment by judeamos** [comment]
Hey @nmoon4, here are tasks for the stepper component: 
1. Create Stepper folder in the `apps/user-profile/src/components/common` folder.
2. Create relevant files: index.js, Stepper.js, StyledStepper.js
3. Implement basic functionality for the stepper: 
- Show Progress bar of current step user is in. 
- Show two buttons, next & back, with navigation functionality
- Render components for each step

**Comment by judeamos** [comment]
This has been completed and is in production.
