### ISSUE TITLE
[Dev](User Profile) Platform Onboarding Tour

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1034]
User Story:
As Nancy Newbie
I want to be welcomed to the organization
So that I feel a greater connection with the organization

Acceptance Criteria:
Given, I am on the first part of the onboarding modal
When I click next
Then I will be directed to the first page of the platform onboarding

Given I am on the first page of the platform onboarding
when I look at the page
then I will see the following Text and image
Heading: "Welcome (User First Name)!"
SubHeading: "We’re so glad you’re here. Let’s get started on your journey."
Image:
![devlogo.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/a5e3ebc0-c747-47d5-8ac3-bced6e756c69)

**Comment by judeamos** [comment]
![Logo float.png](https://images.zenhubusercontent.com/6404cfc245aeb948e3148743/aa86e5d2-6627-410f-9edf-7e838dd52791)

**Comment by judeamos** [comment]
This is related to V2 figma design. There is now V4 and stories to reflect this.
