### ISSUE TITLE
[Dev](User Profile) Second Onboarding tour page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1054]
User Story:
As Nancy Newbie
I want to continue the onboarding tour 
So that I can see some of the things to do with devlaunchers

Acceptance Criteria
Given I have finished the first page of the onboarding tour
when I click next
then the next page of the onboarding tour will populate with 
Heading text "Here are some of the things you can do at Dev Launchers"
3 Pictures and "blurbs" :![things to do.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/a88c0fa1-f4dc-460c-9304-6ef1e34195ed)

[project 1.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/c46fa61b-1527-4699-b885-c421cd81990e)
[network 1.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/990c4be1-265f-4bec-8e0c-4a7d7ffd4796)
[level 1.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/be18b599-aa14-4c2f-a8c3-0d6b235ed05a)

**Comment by judeamos** [comment]
This has been completed, and in production.
