### ISSUE TITLE
[Dev](UserProfile) Create User Variable "Role"

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1055]
As Nancy Newbie
I want to have my role stored
so that projects and people may be recommended to me

Given I have input, the role I take on
when the backend is called
then my role will be viewable

**Comment by judeamos** [comment]
PR as been approved by the backend team, moving this to QA. 
Noel rated this a 5 for first time doing this task, but after completing it, can be lowered to a 3.

**Comment by judeamos** [comment]
Already working in backend, and has been integrated with the onboarding process.
