### ISSUE TITLE
[Dev](User Profile) Restructure the development styling system [Tech Dept]

### ISSUE THREAD

**Issue by judeamos** [dev-launchers/dev-launchers-platform#1057]
A new development styling system is needed to reflect the dev launchers' design system better and accommodate new styles unique to the user profile project. 

This new styling system will be scalable, and help developers code faster, with more clarity on which styling properties to use.

Tasks: 
- Remove undeeded styling files
- Come up with a system to better manage styling for the user profile
- Implement the system

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
