### ISSUE TITLE
Develop Email Notification Content

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1072]
**Considerations**
Dev Launchers members need to receive email notifications from products they are subscribed to.
Required email templates should be gathered from product teams.
Should we include all Dev Launchers teams? (ex: operations).
This ticket does not include designing the email templates.

**Acceptance Criteria**
email content should:
- Have an informative subject line
- Be aligned with Dev Launchers brand
- Be highly personalized
- Focus on one idea 
- Have a clear CTA

**Comment by annaisaacks** [comment]
[https://docs.google.com/document/d/1iYZ1vwDuwSjHApYwH-kk5M9uly2WRbsSTap7jS3dVSw/edit?usp=sharing](url)
