### ISSUE TITLE
[Dev](User Profile) Third Onboarding Tour Page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1074]
As Nancy Newbie
I want to submit my role during onboarding
so that I can be given better recommendations for projects and people

Acceptance criteria
Given I have pressed continue on the second onboarding tour page,
when I view the third onboarding tour page
then I will See
Heading: What Role Best Describes You?
Subheading: We'll use this to recommend open source projects for you to work on.
Role Card 1: Developer
Role Card 2: UX Research/Design
Role Card 3: Other

**Comment by judeamos** [comment]
This has been completed, and in production.
