### ISSUE TITLE
[Dev](User Profile) Role Card Component

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1075]
As Nancy Newbie 
I want to be able to input details about my role
So that I can have accurate recommendations

Acceptance Criteria:
Given, the card has space for a Picture, heading, & subheading
When the card is selected
then the card's border will be highlighted
![rolecard.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/3227b779-1df2-4e29-91fb-33f132983a69)
![rolecardselected.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/ef3f3350-1463-4f64-b5f4-e412270fdbf4)

**Comment by judeamos** [comment]
This has been completed, and in production.
