### ISSUE TITLE
As a Potential Member, I am not interested in agreeing to Terms and Conditions that are not available to read, and would like that field removed when submitting an application

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1084]
TODO: Remove Terms and Conditions box on submission page temporarily (until we have terms and conditions)

![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/367508a1-7d7c-42b4-a319-47f92ad4de78)

Acceptance Criteria
 - The Terms and Conditions checkbox no longer appears at the bottom of the /join submission page

**Comment by hema35** [comment]
![image.png](https://images.zenhubusercontent.com/644977a337832e129a0b3f4c/787821fa-e802-4a26-96bd-19658d61f428)

PASSED
