### ISSUE TITLE
[Dev](User Profile) Fourth Onboarding Tour Page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1096]
As Nancy Newbie
I want to submit my experience level during onboarding
so that I can be given better recommendations for projects and people

Acceptance criteria
Given I have pressed continue on the third onboarding tour page,
when I view the fourth onboarding tour page
then I will See
Heading: What is your experience level?
Subheading: We'll use this to match you with the perfect Project.
Role Card 1: Junior
Role Card 2: Mid-Level
Role Card 3: Senior

**Comment by ethanzlevin** [comment]
Use Role Card Component

**Comment by judeamos** [comment]
Has been completed.
<img width="953" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU11Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efbe7d35f2f78abd8ad63a703620cb8c93af052e/image.png" alt="image.png" />
