### ISSUE TITLE
[DEV] As a Potential Member, I'd like to see the job title I'm applying for whenever I use the Job application page.

### ISSUE THREAD

**Issue by sandra-romero-dev** [dev-launchers/dev-launchers-platform#1098]
Currently: 

![image.png](https://images.zenhubusercontent.com/644ea43b931828e79c0bd5ad/65eaf272-32f5-4ac3-b36a-7b630baa2e5f)

It should be like this, please use the same type face and mix case. 

![image.png](https://images.zenhubusercontent.com/644ea43b931828e79c0bd5ad/a7b837ab-c45d-4912-abbb-1f9615a78ad9)

**Comment by hema35** [comment]
![image.png](https://images.zenhubusercontent.com/644977a337832e129a0b3f4c/5c73c082-c2dc-465d-9ea9-2e3bbf2712ff)

PASSED!
