### ISSUE TITLE
[DEV] As a Potential Member, I'd like to read error-free text when looking up help/tips in the Job application page.

### ISSUE THREAD

**Issue by sandra-romero-dev** [dev-launchers/dev-launchers-platform#1099]
Please fix this typo in the 

'What are your relevant skills?'  prompt: 

it should read:  comma (instead of coma) 

![image.png](https://images.zenhubusercontent.com/644ea43b931828e79c0bd5ad/a17be97b-bfb6-4deb-b7c3-c9aeea284706)

**Comment by hema35** [comment]
![image.png](https://images.zenhubusercontent.com/644977a337832e129a0b3f4c/fc02349a-5b8d-49aa-b2e5-8724c56ed0bd)
