### ISSUE TITLE
[DEV] As a Potential Member, I'd like to read error-free text when looking up help/tips in the Job application page

### ISSUE THREAD

**Issue by sandra-romero-dev** [dev-launchers/dev-launchers-platform#1100]
Please fix typo found in this prompt:

PLEASE BREIFLY DESCRIBE YOUR EXPERIENCE IN DEVELOPMENT OR DESIGN *

It should read 'BRIEFLY' (instead of BREIFLY)
![image.png](https://images.zenhubusercontent.com/644ea43b931828e79c0bd5ad/b708cb4e-7801-46d0-b6bc-5b8c00cdb366)

**Comment by hema35** [comment]
This issue was fixed by Kirubel in story #1099. Please close the issue
