### ISSUE TITLE
[US - UXD] As  MILES HARDIN, I want to download a PDF version of IdeaSpace’s terms and conditions so that I can access and review the terms at any time.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1109]
### Considerations:
While having a terms and conditions agreement on a website is important, providing a downloadable PDF version of the agreement is also a good practice. Providing a PDF version of the agreement makes it easy for Miles to access and review the terms at any time, even if he isn't currently on the website.

_Note: Accessibility guidelines should be taken into account while designing this document. Please find below some references._
- “[Publishing accessible documents](https://www.gov.uk/guidance/publishing-accessible-documents )” from UK.gov
- "[What to Know About Accessible PDFs From Microsoft Word and Google Docs](https://www.lireo.com/accessible-pdfs-microsoft-word-google-docs/ )" by Deborah Edwards-Oñoro, August 24, 2022 

----------------------------------------------------
### Acceptance criteria:
- A PDF version of IdeaSpace’s Terms & Conditions is designed.
- The Terms and Conditions PDF document meets accessibility standards. Please review the references above.

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1109?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @Nouri-Anouar @rashikashaw @RETprojects

**Comment by MariliaDP** [comment]
@JulieMass 
PDF version of IdeaSpace's Terms and conditions is ready in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5303-13035&t=9Pn1eVWiZ24E116B-0). I added a few comments in there as well.

Here is the PDF file:
[https://app.zenhub.com/files/225525029/b2d8dcc0-7f25-46ab-a3f4-31caaeae3fa0/download](https://app.zenhub.com/files/225525029/b2d8dcc0-7f25-46ab-a3f4-31caaeae3fa0/download)

**Comment by JulieMass** [comment]
> @JulieMass PDF version of IdeaSpace's Terms and conditions is ready in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5303-13035&t=9Pn1eVWiZ24E116B-0). I added a few comments in there as well.
> 
> Here is the PDF file: https://app.zenhub.com/files/225525029/b2d8dcc0-7f25-46ab-a3f4-31caaeae3fa0/download

Thank you so much for everything @MariliaDP ! I've replied to your comments in our Figma. 

Is there anything missing from us to complete the design tasks for this ticket? If not, whenever you think this ticket is ready, feel free to move it to the done column and the final designs to the “LATEST DESIGNS” layer in Figma for the devs to find them. 🙌

**Comment by MariliaDP** [comment]
@JulieMass Thank you so much for reviewing this. 
Final Designs are placed in the "Latest Designs" page in Figma.

**Comment by JulieMass** [comment]
Thank you so much @MariliaDP! I'm closing this ticket 🙌💃
