### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to visually identify approved ideas  so that I know my idea project was approved by Dev Launchers.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1110]
### Considerations:
Miles Hardin's idea being approved is a significant milestone in his journey in IdeaSpace. To celebrate this key moment, a special design can be created that provides transparency, a sense of accomplishment, and a positive and engaging user experience. This can help increase user engagement and satisfaction with the platform. 

**Questions to consider:**
- What if we use animations to highlight the approval of an idea or project completion, making it more visually appealing and exciting? If so, what animations can we include? Are they technically feasible? 
- How do we visually share this celebration key moment in the experience to Miles?

**Resources:**
- [[DL - IdeaSpace] Personas + user journey](https://www.figma.com/file/wZOu3DawCKymngV9WLJ4Q3/%5BDL---IdeaSpace%5D-Personas-%2B-user-journey?type=design&node-id=0%3A1&t=90WTiEo2vU0um0r7-1)
- [[DL - IdeaSpace] Analogous Inspiration](https://www.figma.com/file/8CWv3yX3090jWWo4nNAF25/%5BDL---IdeaSpace%5D-Analogous-Inspiration?type=design&node-id=603%3A58&t=QVlb1gfgHbWYGfts-1)

### Acceptance criteria:
- New visual design (hi-fi mockups) are designed for the idea approval. 
- Research about adding animations is performed.

----------------------------------------------------
### Sub-tasks:
- [ ] UX design: Hi-fi mockups for idea approval

----------------------------------------------------

Idea approval key moment in Mile's user journey
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/72d9209e-647d-4aae-8f36-e92f75c36f5e)

Analogous inspiration:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/488832cd-e4d5-49d3-afa6-c51faacb0ba3)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1110?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @Nouri-Anouar @rashikashaw @RETprojects

**Comment by MariliaDP** [comment]
@JulieMass 
From my understanding, these are the ways Miles will be notified when his idea is approved:
 -Email 
-Notification alert on the top navigation
-Tag on the idea card in the IdeaSpace Dashboard & Browse pages will change to Approved
-Celebration banner on the Idea Workshop page
Is that right?

I added a couple of banner options to the [Figma doc](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5312-13056&t=F2UfEN9K4119X1fP-0) and some comments too. Let me know what you think!

**Comment by JulieMass** [comment]
> @JulieMass From my understanding, these are the ways Miles will be notified when his idea is approved:  -Email  -Notification alert on the top navigation -Tag on the idea card in the IdeaSpace Dashboard & Browse pages will change to Approved -Celebration banner on the Idea Workshop page Is that right?
> 
> I added a couple of banner options to the [Figma doc](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5312-13056&t=F2UfEN9K4119X1fP-0) and some comments too. Let me know what you think!

I love this combined approach you are proposing for notifying Miles using email, notifications, tags and the banners options which we discussed in our weekly meeting yesterday. I think this is a great idea Marilia 👏👏! Super excited about this! It will bring a celebration key moment in Miles's experience 😀🎉

**Comment by MariliaDP** [comment]
@JulieMass I left comments in the [Figma file](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5501-12007&mode=design&t=lOn63PxO4jmDK4Ir-0) about some changes to this design. Please let me know if you have any questions or would like to discuss them more.

**Comment by MariliaDP** [comment]
Approved Idea header is added to ["Latest Designs" in Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=2645-5947&mode=design&t=b6QOUpYNQ2tNCIoG-0)

Notes:
-Dark background to differentiate from Workshopping page. Confetti is static for now, but it may be animated.
-Idea Name and Idea Owner Name will appear in Bold in the header and should be adjusted for each idea page.
-Next Step button will direct to the Idea Roadmap at the bottom of the page (the roadmap may change depending on the usability testing findings).
-Idea Roadmap will feature a link to follow the development of this project.

**Comment by JulieMass** [comment]
Thank you so much @MariliaDP for the update and the notes. As always you are super detailed and organized 👑! I added a reminder to myself in our Figjam story map, to add your notes when I create the ticket for development.

I created a comment for you in the Figma file about the last step in the roadmap. Nothing major, but let me know your thoughts there please.

**Comment by MariliaDP** [comment]
Thank you @JulieMass :)

I replied to your comment in Figma. I agree with removing the word "you" in the first sentence, but I still think "Follow this project" would be a better copy for the link. The sentence before the link is already long, and I think it can get repetitive to say "Dev Launchers" and the idea/project name again.

**Comment by JulieMass** [comment]
Hey Marilia, just wanted to say that you totally rocked it! Thanks a ton for being so detailed with the designs and updating the roadmap in the other design pages. You're the best! We're closing the ticket now, so thanks again! 🙏

**Comment by MariliaDP** [comment]
Thank you Julie!!!
