### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to be able to see the most recent comments on ideas I own so that I can quickly follow up on them

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1113]
### Considerations:
MILES can see the most recent comments on ideas he owns in his dashboard and quickly reply to them. We have an initial design but we need to advance this user flow in more detail.

**Questions to consider in this user flow:**
- Filter: what are the values of the filter? 
- How are ideas ordered by default?
- What is the maximum amount of comments we should display in his dashboard? When does the “Load more replies” should show up? Always? Once “x” amount of comments? Etc. 
- Should we add a total of comments like we have in the workshopping page? 
- Should we add any other quick action from the dashboard? For example: ability to like a comment from the dashboard? 
- What happens when Miles clicks on “Reply”? 
_etc etc..._ 

### Acceptance criteria:
- New visual design (hi-fi mockups) are designed for the latest comments in the dashboard.
- The design includes solutions and resolves the questions mentioned above such as:
  - filter and options needed
  - Managing a big amount of comments
  - any quick action (if needed)
  - Shows the user flow and steps to reply from the dashboard, etc.
- Mockups are web responsive and include mobile, tablet and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [ ] UX design: Hi-fi mockups for latest comments in the dashboard

----------------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/373a4b3e-83c4-4e30-8cc4-ba0637af00ce)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1113?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @Nouri-Anouar @rashikashaw @RETprojects

**Comment by MariliaDP** [comment]
Hi @JulieMass 
Here is the latest solution for ideas Miles owns in his dashboard: https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5914-9989&mode=design&t=Kxf9TTFuvmdWDR1w-0

About the questions above:
1- Filter Values
We would have 2 filters:
-Select idea: Lists all his Ideas where comments were made
-Date Posted: Anytime, Past 24 hours, Past week and Past Month.

2- Ideas and Comments are always organized by the Newest first, even when using a filter.

3- I think 10 is a good number for displayed comments. A link to “Show more comments” adds 10 more.

4- Adding a total of comments: I don’t think that’s necessary. Users can keep track of recent posts by filtering and sorting the dates posted. They can go to their idea pages to see how many comments each idea has. I think that's not a major improvement and will end up creating more work for the team.

5-Quick Actions: Like, Reply, and View Idea. When Miles clicks on Reply, it will take him straight to the comment input field on their Idea Workshopping Page.

Please let me know your thoughts. 
I added more comments in the Figma file, happy to discuss anything if needed. Thank you!

**Comment by JulieMass** [comment]
> Hi @JulieMass Here is the latest solution for ideas Miles owns in his dashboard: https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=5914-9989&mode=design&t=Kxf9TTFuvmdWDR1w-0
> 
> About the questions above: 1- Filter Values We would have 2 filters: -Select idea: Lists all his Ideas where comments were made -Date Posted: Anytime, Past 24 hours, Past week and Past Month.
> 
> 2- Ideas and Comments are always organized by the Newest first, even when using a filter.
> 
> 3- I think 10 is a good number for displayed comments. A link to “Show more comments” adds 10 more.
> 
> 4- Adding a total of comments: I don’t think that’s necessary. Users can keep track of recent posts by filtering and sorting the dates posted. They can go to their idea pages to see how many comments each idea has. I think that's not a major improvement and will end up creating more work for the team.
> 
> 5-Quick Actions: Like, Reply, and View Idea. When Miles clicks on Reply, it will take him straight to the comment input field on their Idea Workshopping Page.
> 
> Please let me know your thoughts. I added more comments in the Figma file, happy to discuss anything if needed. Thank you!

Hey @MariliaDP , I just wanted to say that your explanation and answers to our questions about the acceptance criteria were amazing! You covered everything as always.

Regarding point 4, leaving it as a future improvement sounds good to me.

I did leave a few minor suggestions in the Figma file, but overall, great job! 

Thanks again!

**Comment by MariliaDP** [comment]
@JulieMass 
Thank you so much for your feedback and great insights! I replied your comments in Figma. I'll check in after I come back to see if the team has any questions.
Thanks again

**Comment by MariliaDP** [comment]
@JulieMass 
"Recent Activity" section on the dashboard is updated and added to the Latest Designs page and Prototype.

Here are some considerations that we discussed:

-Two Filters will be displayed:
My Ideas (Lists ideas that Miles owns)
Date Posted (Options: Past 24 hours, Past Week, Past Month & Anytime - Note that past week will be the default option )

-The comment section displays name, Idea name, date, buttons to like, reply (same functionality as in the comment section on the workshopping page) and view idea (takes the user to the Workshopping page). It also displays a three dots icon for more options (“Report this Comment” and “Clear from Dashboard”)

-10 comments in total should be displayed. A link to “Show more comments” adds 10 more.

Please let me know if you need any adjustments or have any questions. Thank you for all your help!

**Comment by JulieMass** [comment]
@MariliaDP  Just wanted to say thanks for documenting here the decisions taken! This will help me a lot when creating the ticket for development.

Closing this ticket. Great job! Thank you so much!
