### ISSUE TITLE
[US-UXD] As AMELIA HARRIS, I want to “@” tag Miles in the comments on the workshopping page so that I can bring his attention to a particular message

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1114]
### Considerations:
Ability for AMELIA to “@” to mention or tag MILES in the conversation on the workshopping page’s comment section to make sure he sees and responds to her message.

Questions to consider:
- What happens when Amelia writes “@”? Will the app bring a list of possible dev launcher’s members? 
- Should the @ be a link to the person’s user ideas dashboard? If so, should we think about having a “public” view dashboard? Etc etc

### Acceptance criteria:
- New visual designs (hi-fi mockups) are designed for tagging someone’s user flow.
- Layout is web responsive and it works well for mobile, tablets and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [x] UX design: Hi-fi mockups for …

----------------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/db077896-d2d8-4b4e-b5a8-97c7fe8a4700)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/3640df56-7697-4c5d-b842-b4cbca37020e)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1114?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @Nouri-Anouar @rashikashaw @RETprojects

**Comment by Nouri-Anouar** [comment]
@JulieMass 
Please check this prototype out and give me your feedback [Here](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=4991-11641&scaling=min-zoom&page-id=2562%3A6706&starting-point-node-id=2834%3A6526)

**Comment by MariliaDP** [comment]
@Nouri-Anouar the prototype looks great.
@JulieMass your question about where the @link takes you is also great. We should consider having a public user profile or something like that. I'll think more about it.

**Comment by Nouri-Anouar** [comment]
**Final design** 

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/79311912/d57442ad-79d1-48df-ab8d-e1947a005897)

[**Interactive Prototype**](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=4991-11641&scaling=contain&page-id=2562%3A6706&starting-point-node-id=2834%3A6526)

**Comment by JulieMass** [comment]
Thank you @Nouri-Anouar 🎉!  are these designs in our "LATEST DESIGNS" layer in the Figma file for developers to find it out? I wasn't able to find it there. 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/6fa18f0c-994c-4a70-9df8-9a3c3cb92eac)

**Comment by Nouri-Anouar** [comment]
@JulieMass They were in "work in progress" 😅 
I've moved them to the "components" section in "latest designs.

**Comment by JulieMass** [comment]
Great!  Thank you so much @Nouri-Anouar 🙌! I’ve created the ticket #1184 for us to develop this feature that you designed, in which I added your prototype link and I’ll add the location of your final designs in Figma for devs to find them.

It seems that we have dependencies on the email and notifications tickets from the Universal design team as well as the User profile team, so unfortunately we’ll need to wait for all these tasks to be done for us to start implementing it. But I’m sure we’ll be able to start soon 😀!

**Comment by Nouri-Anouar** [comment]
Everyone is working hard on this, I am really excited to see this feature live.
