### ISSUE TITLE
[Dev](User Profile) Animate the last* onboarding tour page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1115]
As Nancy Newbie
I want to view an animated dev launchers logo on the first onboarding tour page
so that I am more engaged

Given I have clicked the 'Platform Onboarding' Task
When the page loads
The Dev Launchers Logo will continuously bounce up and down, and the shadow will grow and shrink alongside it.
& the Next button will remain clickable during the animation

**Comment by judeamos** [comment]
The initial story was for V2 design of the onboarding process. We did not create a new story to cover the change to V4 where the animation was moved to the last page.
