### ISSUE TITLE
[Dev](User Profile) Animate the second onboarding tour page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1116]
As Nancy Newbie
I want the three "What is Dev Launchers" blurbs to slide onto the screen
So that I am engaged with each one individually

Given I have finished the Welcome Page
when I click next
Then 
The Heading text will be static on screen
The three blurbs will fade in one at a time
The "next" button will not be clickable until the animation is finished

**Comment by judeamos** [comment]
This has been completed.
