### ISSUE TITLE
[Dev](User Profile)Onboarding task card behavior on hover

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1117]
As Nancy Newbie
I want the onboarding task card to have a border appear on hover
so that I understand it is clickable

Given, I am on the onboarding page and the task card is not in its completed mode
When I hover my mouse over any onboarding card
then a light blue border will appear

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
