### ISSUE TITLE
Design Email Notification Templates 

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1127]
**Acceptance Criteria**
- Templates design is aligned with the Dev Launchers style guide.
- The Layout is web responsive and it works well for all breakpoints.
- Templates should include a header, a body, and a footer.

**Comment by annaisaacks** [comment]
@JulieMass I will prioritize this one and the onboarding ones after we make any changes to the welcome email.

**Comment by JulieMass** [comment]
> @JulieMass I will prioritize this one and the onboarding ones after we make any changes to the welcome email.

That is awesome! Thank you so much Anna!

**Comment by annaisaacks** [comment]
[Figma Design](https://www.figma.com/file/B8QY4HfTxJVlvpCaRjyiXw/Email-Template-Design?type=design&node-id=301-3231&mode=design)
