### ISSUE TITLE
Design a shared grid system 

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1128]
**Considerations:**
What grid systems our teams are currently using?

**Acceptance criteria:**
- The grid system is web responsive across all breakpoints.
- The grid system satisfies our teams required layouts.

**Comment by Nouri-Anouar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1128?planning-poker) with Zenhub @annaisaacks @linakim602

**Comment by Nouri-Anouar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1128?planning-poker) with Zenhub @Leah0996

**Comment by linakim602** [comment]
6/22 Had the first meeting with all UX designers and discuss about the grid system.

**Comment by linakim602** [comment]
The research foam was developed to gather input from various team members, such as researchers, designers, and developers. Its purpose is to **investigate the experiences and requirements related to the grid system**. Additionally, this approach aids in **identifying the primary problem and determining task priorities** for the development of an enhanced grid system. Link to the research: https://www.figma.com/file/xv82pE8HBfYnkxPQGRhalI/Grid-System---Research?type=whiteboard&node-id=0%3A1&t=SfpxK77vvnAZ3OwB-1

Next Step:
1. Getting more inputs for the research
2. Research other companies grid system
3. Create an analysis template(competitive analysis) to identify potential opportunities
