### ISSUE TITLE
[ENHANCEMENT - DEV] As MILES HARDIN, I want to leave a new comment in the comment feed so that I can workshop my idea with other people (part 2)

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1138]
### Considerations:

**Note:** We have decided to split ticket #744 and created this ticket as a continuation. 

Miles Hardin wants to add a new comment in the comment feed from the workshopping page. We also need to update the comment feed look & feel to match our new designs.

This task DOESN'T include the followings:
- Comment's filter drop down.
- Reply to a comment
- "Load more" button that brings up new comments
- Like a comment

Please refer to our 
- [Figma prototype](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?page-id=2562%3A6706&node-id=2562%3A6894&viewport=458%2C-268%2C0.52&scaling=min-zoom&starting-point-node-id=2562%3A6894&show-proto-sidebar=1) 
- “workshopping page” UX mockups in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/IdeaSpace-(Copy)?node-id=0%3A1) and related US - UXD #704.

NOTE: @Enjoy2Live mentioned this item seems to be good for the library that the platform enablement team is working on. Good to keep them updated on it. 

-----------------------------------------------

### Acceptance criteria:
- New visual design layout is implemented.
- The comment feed is web responsive (desktop, mobile and tablet breakpoints).
- Comments should be ordered by most recent.
- Miles can add a new comment using the input field at the top. This input has a placeholder that says: "Add your comment"
- Each comment created should include:
  - the date of creation _(e.g. 2 days ago)_

-----------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/bf489d34-16c4-4bd2-8ca9-ba787a07c027)

![image](https://user-images.githubusercontent.com/104226366/213287504-dbde6ae9-e526-4574-9d3e-bd2cbf9b5b04.png)

![image](https://user-images.githubusercontent.com/104226366/213288402-11796be0-06ce-48e5-8622-b2b7ba784def.png)

**Comment by RETprojects** [comment]
The comment form text box says "What are your thoughts?" in staging. When I post a new comment to an idea's workshopping page on staging, the number of comments updates immediately, and the new comment is shown with my username, the comment text, and how long ago it was posted. The newest comment first appears at the top of the feed, as the ticket says it should, but upon refreshing, the feed has been sorted so that the newest comments are at the bottom.

**Comment by chadcrotchett** [comment]
### Acceptance criteria:
- New visual design layout is implemented.
- The comment feed is web responsive (desktop, mobile and tablet breakpoints).
- Comments should be ordered by most recent.
- Miles can add a new comment using the input field at the top. This input has a placeholder that says: "Add your comment"
- Each comment created should include:
  - the date of creation _(e.g. 2 days ago)_

**Comment by chadcrotchett** [comment]
meh, good enough for now...
