### ISSUE TITLE
Add Outlined Variant for Tag Component

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1170]
**Considerations:**

Currently, the existing variants of the tag component are causing excessive visual attention, particularly the black variant. In order to address this issue and provide more flexibility, we need to introduce a new variant: the outlined version.

The outlined variant will offer a less prominent visual appearance compared to the existing options.

**Acceptance Criteria:**

- The new outlined variant for the tag component is added to the existing set of variants.
- The outlined variant has a visually distinct appearance that is less prominent compared to the other variants.

**Comment by annaisaacks** [comment]
Already designed in the system - 

[https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?type=design&node-id=2018-8031&t=Rkt5OeDYXjA7qAGz-4]

**Comment by Nouri-Anouar** [comment]
Thank you @annaisaacks, for resolving this ticket. I assigned it to you since you were the original creator of the outlined tag variant.
