### ISSUE TITLE
Enhance Slider Component with Dual Thumbs

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1171]
**Considerations:**

The current slider component provides a single thumb for selecting a single value along a range.
The need for increased flexibility has arisen, prompting the decision to update the slider component with two thumbs.
The addition of dual thumbs will enable users to select a range of values, accommodating a wider range of use cases and providing more versatility to our teams.

**Acceptance Criteria:**

- A new slider component variant is added to display two thumbs.
- The dual thumbs can be independently moved along the slider track to select a range of values.
- The selected range between the two thumbs is visually highlighted or differentiated from the rest of the slider track.

**Comment by annaisaacks** [comment]
19/81 variations completed for a 1- 10 slider. 
Range sliders should only be used in cases with a limited range (1-10)
Range sliders 1-40 would have 400 variations and would be impractical and inaccessible. 

[https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?type=design&node-id=4956-12855&t=Rkt5OeDYXjA7qAGz-4](url)

**Comment by annaisaacks** [comment]
Sliders Designed 
https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?type=design&node-id=6189-24144&mode=design&t=Fd8BGKQ8JjtylkgR-4

* I need to set varient styles as a small left over task and finish the prototype functionality *
