### ISSUE TITLE
(User Profile) Onboarding Introduction Modal (Implementation)

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1176]
As Nancy Newbie
I want to be prompted to ask if I want to complete the onboarding process now or later
so that I can complete my onboarding later if I do not have the time

Given I have completed the initial data collection page
when the User Profile is loaded initially
then the "Intro" Modal will load

Given, I have previously selected "Set Up Later" or have not completly finished the onboarding modal
when I reload the user profile
then the "intro" Modal will load

**Comment by judeamos** [comment]
Has been completed.
<img width="539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVF1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d34ccfefe249d6625fbc764d93b73187afdfc74/image.png" alt="image.png" />
