### ISSUE TITLE
(User Profile) Onboarding Complete Variable

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1178]
As Nancy Newbie
I want to access onboarding if I have not completed it
so that I can finish the onboarding process

Given, I have not finished working on the onboarding process
when I return to my user profile
then the backend will contain a variable called "Onboarding Complete" that set as false by default

**Comment by judeamos** [comment]
This has been completed, and integrated with the fronend.
