### ISSUE TITLE
(User Profile) Update Initial Data Collection Page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1180]
As Nancy Newbie
I want the IDC page to be updated
so that it is more readable and welcoming

Given I have started my profile creation
when the page loads
then
the background of the IDC page will be white
The Continue button will be Primary Standard and say "Save and Continue" and be located Center Right
a grey bar will be located across the top of the screen underneath the site banner
The Header to be updated to Say 
H1: First Let's Set Up Your Profile
H2: A complete profile will help to match you with the perfect opportunity

**Comment by judeamos** [comment]
This was a change to the onboarding page.
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUl1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24a75f532eb965ebad1ac3dba6f9c0234c9d0737/image.png" alt="image.png" />
