### ISSUE TITLE
Create Tutorials Section within the Design System's Cover Page

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1197]
Create a dedicated area on the Design System cover page to provide tutorials and guidelines for designers in creating UIs.

**Acceptance Criteria:**

- A tutorials section is added to the cover page, prominently displayed and easily accessible.
- The tutorials section includes how to use instructions, atomic design overview, best practices, and design principles.
- The tutorials section is comprehensive, covering various aspects of UI design to ensure consistency and quality across team projects.

**Comment by annaisaacks** [comment]
Should this possibly have it's own page in the design system ?
