### ISSUE TITLE
Add Links to Design Figma Files of all Dev Launchers teams within the Design System's Cover Page 

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1198]
Include prominent links or references to different design Figma files related to our teams on the cover page.

**Acceptance Criteria:**

- Relevant design Figma files are identified and linked from the cover page.
- The links or references are prominently displayed and easily identifiable.
- Designers can access the linked Figma files directly from the cover page, promoting collaboration and knowledge sharing.
- Embed design previews within the cover page if possible.

**Comment by annaisaacks** [comment]
This may still be something we implement or the Figma structure may actually cover this - @Nouri-Anouar What do you think?

**Comment by Nouri-Anouar** [comment]
@annaisaacks Thank you for bringing that up. I agree with you, the Figma structure already provides a suitable solution. So, I will close this ticket.
