### ISSUE TITLE
As a Website Visitor, I do not want to see project milestones listed on the project description page unless I am a member of the project team

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1203]
---
**TASK**: Hide milestones if user is not logged in and part of the team

You can see an example of a milestone listed at https://devlaunchers.org/projects/user-profile
![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/c1e31f30-8e15-40f1-a1aa-97a39a1f91c7)

**ACCEPTANCE CRITERIA**
 - When users are not logged in to the site, or are logged into the site but not part of the team listed on the page they're viewing, the Milestones section is hidden

**Comment by helioLJ** [comment]
Made a P.R. for this issue:

[See here](https://github.com/dev-launchers/dev-launchers-platform/pull/1211/commits/11df3feda40c223fbfdb6cc1a4acb948d3cc0f15)

**Comment by Devanshusp** [comment]
Need a way to test this (need to be able to log in)
