### ISSUE TITLE
As a Website Visitor, I do not want to see team meeting information listed on the project description page unless I am a member of the project team

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1204]
---
**TASK**: Hide upcoming meetings if user is not logged in and part of the team

You can see an example of the team meetings section at https://devlaunchers.org/projects/hello-world
![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/391e2f77-ac79-429e-8e6e-7ed6ad55b07b)

**ACCEPTANCE CRITERIA**
 - When users are not logged in to the site, or are logged into the site but not part of the team listed on the page they're viewing, the Upcoming Meetings section of the page is hidden

**Comment by helioLJ** [comment]
I created two constants to hold booleans that check if user id is on the project team and if user is logged.

[See here](https://github.com/dev-launchers/dev-launchers-platform/pull/1211/commits/11df3feda40c223fbfdb6cc1a4acb948d3cc0f15)

So it would be very nice if the future developer who is gonna solve this use this utils :D

**Comment by Devanshusp** [comment]
lets wait until we can test this while being logged in as well :)
