### ISSUE TITLE
As a Website Visitor, I would like to have more uniform and expected behavior when clicking on a team member's picture on a project page

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1205]
---
**ISSUE**: Clicking a member’s picture takes you to the top of the page. It should NOT be clickable, and not have any hover effect or cursor changes to denote that it is clickable

![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/1ad0ee21-dfff-4fc6-937b-36595d076230)

**ACCEPTANCE CRITERIA**
 - When users click on any team member image on a project page, nothing happens
 - When users hover over any team member image on a project page, nothing happens

**Comment by helioLJ** [comment]
Created a P.R. for this and waiting for Review:

[Pull Request](https://github.com/dev-launchers/dev-launchers-platform/pull/1212)
