### ISSUE TITLE
As a Potential Sponsor, I'd like to see properly formatted text copy attached to calls to action on the project description page

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1207]
---
**TASK**: “We are looking for sponsors to fund the financial costs of different operations, with your help we can build a better product!” - Make 2 sentences

![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/b1063aff-b0de-4dc4-8353-5e43b1e8b0f5)

**ACCEPTANCE CRITERIA**
 - The described text above reads as "We are looking for sponsors to fund the financial costs of different operations. With your help we can build a better product!"

**Comment by Devanshusp** [comment]
https://devlaunchers.org/projects/hello-world
