### ISSUE TITLE
As a Team Member, I do not want to see old and outdated project milestones on project pages

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1208]
---
**TASK**: Remove old milestones client side. If older than 1 month, do not render milestone.

![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/0593e3e8-239e-4588-8ee4-b7255a969911)

**ACCEPTANCE CRITERIA**
 - Milestones older than one month no longer render on any project description pages

**Comment by helioLJ** [comment]
I created two constants to hold booleans that check if user id is on the project team and if user is logged.

[See here](https://github.com/dev-launchers/dev-launchers-platform/pull/1211/commits/11df3feda40c223fbfdb6cc1a4acb948d3cc0f15)

So it would be very nice if the future developer who is gonna solve this use this utils :D

**Comment by yacineKahlerras** [comment]
this is already solved and merged by @helioLJ  right ? so no need to add anything else and move it to Q/A ?

**Comment by helioLJ** [comment]
Made a Pull Request for this issue:

[Link for P.R.](https://github.com/dev-launchers/dev-launchers-platform/pull/1237)
