### ISSUE TITLE
As a Team Member, I do not want to see meetings listed in the "Upcoming Meetings" section of the project details page that have already passed

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#1209]
---
**ISSUE**: Meetings that have already passed are still being displayed on the page by at least one day

![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/93229c26-dea1-41ce-9d29-5be3bcd82494)

**ACCEPTANCE CRITERIA**
 - Meetings that have already happened do not render on any project pages

**Comment by helioLJ** [comment]
Made a P.R. for this issue:

[Pull Request](https://github.com/dev-launchers/dev-launchers-platform/pull/1210)
