### ISSUE TITLE
Cannot close dialog box on project page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1228]
**Describe the bug**
On Project Page, users with edit access cannot close out dialog box for editing permissions

**To Reproduce**
1. Go to https://devlaunchers.org/projects/user-profile (or any project page you have admin access for)
2. Click on ![image.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/db134cc7-624e-4408-bb8d-39b0cccf6da2)
3. no response

**Expected behavior**
dialoge box should close

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version ??

**Comment by helioLJ** [comment]
@Devanshusp Think I'm gonna need a Admin Permission to test this dialog box.
