### ISSUE TITLE
adding a back button to each project page

### ISSUE THREAD

**Issue by yacineKahlerras** [dev-launchers/dev-launchers-platform#1231]
as a website visitor i would like to go back to the _**projects page**_ using a button on the page instead of using my browser's **back button**

![Screenshot 2023-07-07 at 2.54.44 PM.png](https://images.zenhubusercontent.com/64921182b8a2370ddbf0f9b2/56309d6f-6af1-40a7-b924-ee960d687683)

Could look similar to this back button on the top of the page

**Comment by Devanshusp** [comment]
https://storybook.devlaunchers.org/?path=/story/molecules-backbutton--back
