### ISSUE TITLE
[Dev](User Profile) Create Interests page onboarding modal

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1256]
BE Story?
As Nancy Newbie
I want to enter my interests during onboarding
so that I can get better recommendations

Given I have entered my experience level
when I click "Next"
then the "Interests Page" will appear on the modal

given the interests modal has loaded
when the user sees the modal
the page will match the image below
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkdDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89ef91b8e61972a3c3cdbbc463b8fb105d254ffe/image.png)

**Comment by judeamos** [comment]
This has been completed and is in production.
