### ISSUE TITLE
[Dev](User Profile)Change the First Onboarding tour page to the Congratulations Page & Update Content/Styling

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1258]
As Nancy Newbie
I want the first onboarding tour page to become the congratulations page
so the animation for this page is the final onboarding page.

Given I have completed the interests page
when I click next
then I will be directed to the new congratulations page

Given I am on the new congratulations page
when I click the end button
Then the modal will close with no warning.

Given I am on the new congratulations page
when the page loads
the styling/copy will match the figma file
https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/User-Profile-%2F-Onboarding-Main-File?type=design&node-id=1268-13038&mode=design&t=3wXbBzMgAx91KMHF-0

**Comment by judeamos** [comment]
This has been changed.
