### ISSUE TITLE
[Dev](User Profile) Restyle "About Us"

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1260]
![image.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/b3aaaca6-e87e-4ace-9310-676dac04c543)
Follow Figma
https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/User-Profile-%2F-Onboarding-Main-File?type=design&node-id=1268-13038&mode=design&t=3wXbBzMgAx91KMHF-0

**Comment by judeamos** [comment]
This has been completed and is in production.
