### ISSUE TITLE
[Dev](User Profile) Restyle About You Role

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1261]
![image.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/45fcc135-bf97-4a5b-b7d2-70a4fb1c6851)
Follow Figma
https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/User-Profile-%2F-Onboarding-Main-File?type=design&node-id=1268-13038&mode=design&t=3wXbBzMgAx91KMHF-0

**Comment by judeamos** [comment]
This has been completed
