### ISSUE TITLE
[Dev](User Profile)Restyle About You Experience

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1262]
![image.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/17e9ba6f-3a7a-4bcf-8640-116dafbc72eb)
Follow Figma
https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/User-Profile-%2F-Onboarding-Main-File?type=design&node-id=1268-13038&mode=design&t=3wXbBzMgAx91KMHF-0

**Comment by judeamos** [comment]
This has been completed
