### ISSUE TITLE
[Dev](User Profile) Create "Close Onboarding" modal

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1263]
As Nancy Newbie
I want to be able to close out of the onboarding at any stage of the process
so that I can pause onboarding and return later

Given, I am on any given page of onboarding
when I click on the x button on the top right of the modal
then the close onboarding confirmation will appear
![image.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/1cb625e9-4b20-45a0-9746-096c4e0e8752)
Given the close onboarding confirmation is open
when I click confirm,
then my changes will save and the onboarding modal will close

Given the onboarding confirmation is open
when I click Cancel,
then the close onboarding confirmation will close

**Comment by judeamos** [comment]
This has been completed and is in production.
