### ISSUE TITLE
[SPIKE] In order to develop the confetti header animation in the workshopping page, our UX Designer needs to research the best practices for animations, and have some conversations with the developers.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1267]
### Context:
Our UX Designer is conducting research and collaborating with developers to implement a confetti header animation in the approved idea page. The confetti header animation will add a celebratory touch to the user experience.

### Acceptance Criteria:
- Confetti header animation is triggered at the appropriate time, such as when a user completes a process.
- UX Designer researches the best practices for animations and analyzes the technical feasibility of implementing the animation.
- UX Designer collaborates with developers to ensure a seamless implementation of the animation.
- Accessibility best practices are considered for this confetti header animation.
- We have a decision on clear next steps on how we will implement the Confetti header animation on the approved idea page and what tasks need to be done (e.g. “The animation needs to be created and exported as “X” type of file in order to follow accessibility best practices and development feasibility”)

-------------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/ecf1397d-0c77-40f8-b8a8-e636031d9686)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1267?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @RETprojects

**Comment by JulieMass** [comment]
Hi @MariliaDP, as discussed yesterday I added this spike task so we can research how to implement the header animations in the workshopping page. Please let me know if I missed anything in the description of the ticket. Thank you in advance!

**Comment by MariliaDP** [comment]
@JulieMass 
In my search, it looks like GIF is the best file format for animations. It looks like we could create it so it doesn’t loop, which would work well for our approval header. In that case, we’d need an animator to create that. 

There are many other styles of animations, even coding like this website (https://confetti.js.org/), that I don’t understand or know how much easier/harder it is to implement. It would be helpful to have a developer look into it as well. 

That said, I don’t think we should worry about adding animations right now. This will take time and resources from other essential tasks.

**Comment by JulieMass** [comment]
Hey @MariliaDP !

Thanks a ton for this! The code demo you found is seriously awesome!! I totally agree with you that we can put off the animations for now, but the research you did is really helpful! Right now, we have a lot of things on our backlog that are a higher priority, so we can save this for later.

**Comment by MariliaDP** [comment]
Great! Thanks Julie!
