### ISSUE TITLE
[US1.0] Create a User Context for the Resources Page

### ISSUE THREAD

**Issue by Devanshusp** [dev-launchers/dev-launchers-platform#1283]
**Problem:**
- We don’t know if a user is signed in
- We don’t know if a user is from the dev or product team
- We don’t know which teams the user is from

**Goal:**
- Link and organize user context to be used in the Resources page
- We need to know the user, user’s projects, and the user’s position (developer vs UX), and whether they are in a lead position or not

**Additional Information:**
- Link to [Figma](https://www.figma.com/file/hS4Cvs69za7LNkT9BYaDlo/Resource-Page?type=design&node-id=0%3A1&mode=design&t=4lW8pI9q9HyVF7qF-1)
- Link to [Storybook](https://storybook.devlaunchers.org/?path=/story/docs-iconography--page)

**Comment by helioLJ** [comment]
https://github.com/dev-launchers/dev-launchers-platform/pull/1328
