### ISSUE TITLE
[US2.0] Create a Projects Display and its contents

### ISSUE THREAD

**Issue by Devanshusp** [dev-launchers/dev-launchers-platform#1285]
**Problem:**
- A user should be able to see the projects they are part of on the resource page and click them to view their resources

**Goal:**
- Add the projects the user is a part of as clickable buttons on the top of the resource page.
- When clicked, the project button should display the resources, team meetings, people and other resources specific to that project.
- Manage it so a new module opens with each project A, B, C, etc.
    - The first project, project A, should be open by default

**Additional Information:**
- ![image.png](https://images.zenhubusercontent.com/64921182b8a2370ddbf0f9b2/e77e0c60-1e3b-48de-bcf6-fd2a5310a01d)
- ![image.png](https://images.zenhubusercontent.com/64921182b8a2370ddbf0f9b2/0ba08164-80c1-44c2-a9b1-83485e92b37e)
- Link to [Figma](https://www.figma.com/file/hS4Cvs69za7LNkT9BYaDlo/Resource-Page?type=design&node-id=0%3A1&mode=design&t=4lW8pI9q9HyVF7qF-1)
- Link to [Storybook](https://storybook.devlaunchers.org/?path=/story/docs-iconography--page)

**Comment by helioLJ** [comment]
https://github.com/dev-launchers/dev-launchers-platform/pull/1328
