### ISSUE TITLE
Improve Button Colors Differentiation

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1293]
**Considerations:**
Marilia suggested enhancing the button colors to improve user experience. Currently, the Primary and Secondary button colors are too similar. As discussed, we should explore adding distinct colors to make them more visually distinguishable.

**Acceptance Criteria:**

- Primary and Secondary buttons should have visually distinct colors, making them easily recognizable.
- The new button colors should be chosen based on the provided ideations and accessibility standards.

Marilia's additional suggestion: 
_In case the universal team doesn't want to change primary and secondary buttons, I think they should consider introducing a button for dark/mode or dark background._

![image.png](https://images.zenhubusercontent.com/6350551534ca83302f37d59a/18b15b18-8826-42bd-958e-28617712a110)

**Comment by Nouri-Anouar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1293?planning-poker) with Zenhub @annaisaacks @Nouri-Anouar @Leah0996 @linakim602

**Comment by annaisaacks** [comment]
I think it might be interesting to experiment with the secondary being an outline style instead and possibly converting the button colors into a greyscale or adding a primary/ secondary color that is outside of our brand colors. I like the idea of light/dark mode here as well
