### ISSUE TITLE
Document and Refine All Color Styles

### ISSUE THREAD

**Issue by annaisaacks** [dev-launchers/dev-launchers-platform#1315]
**Description**
Refactor the color palette to enhance flexibility, cohesiveness, and documentation.

**Completed Color Palette Refactoring Tasks**
- Add Nebula, Cosmic, and Warning colors to the palette with corresponding hex codes.
- Implement color ranges from 50 to 900 following Tailwind conventions.
- Adjust notification, success, and error colors to harmonize with the main brand colors.
- Rename the main brand colors to Jupiter, Uranus, Neptune, and Saturn.
- Create display chips for each color, including name, swatch, hex code, RGB values, and accessibility contrast ratios.
- Organize colors into Grayscale, Brand-Primary, Brand-Secondary, and Alert categories.

**Comment by Nouri-Anouar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1315?planning-poker) with Zenhub @AmalJS00 @annaisaacks @leeah-d @linakim602 @SiiiyanLiii

**Comment by Nouri-Anouar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1315?planning-poker) with Zenhub @KatrinaCCC
