### ISSUE TITLE
[US - UXD] As MILES HARDIN, when I want to submit a new idea to IdeaSpace, I want to access a FAQ page, so I can gain a clear understanding of the idea submission process and approval criteria without feeling frustrated or confused without support

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1361]
### Considerations:
The idea of including an FAQ page was generated based on the recommendations from the team after conducting a usability test. During the test, participants like MILES expressed a lot of questions and concerns that were crucial in assisting them throughout the process of submitting a new idea to IdeaSpace.

We believe that **by providing a helpful and informative FAQ page, we can make it easier for MILES to submit his ideas with confidence and clarity**.

**Some initial questions to consider for design:**
- Are there any areas in the product where some FAQs should be linked? For example, in the idea submission form.
- Should we consider a short survey at the end of each FAQ to validate if the information was useful?

Please consider the following documentation:
- [UXR Analysis, synthesis & ideation](https://www.figma.com/file/KJ4zv96IoAzh8FuoXNq2nB/%5BDL---IdeaSpace%5D-UXR-Analysis%2C-synthesis-%26-ideation?type=whiteboard&node-id=1254%3A2183&t=zqi9bDQma6M4OLAW-1 ) (FigJam file) 
- In our Figma file of “[[DL - IdeaSpace] Analogous Inspiration](https://www.figma.com/file/8CWv3yX3090jWWo4nNAF25/%5BDL---IdeaSpace%5D-Analogous-Inspiration?type=design&node-id=603%3A58&mode=design&t=kXxqdXHt5ZfH01Wm-1 )” we have some screenshots of other competitor’s FAQs pages 
- [FAQ Content ](https://docs.google.com/document/d/1BLsMWnznATd5Kq_igRYlyd2PTKCBgI9YFiAYxIT2LlA/edit?usp=sharing)(.doc) 

### Acceptance criteria:
- The FAQ page should be easily accessible from the IdeaSpace homepage. 
  - Ideas to consider from the ideation:
     -  1. Add a "Learn more" next to each of these 3 ways to contribute that redirects to the FAQ page
     -  2. Have a link somewhere in the landing page that says “How does it work?” or similar?
- The FAQ page should be well-organized and easy to navigate, with clear headings and subheadings. 
  - For inspiration: https://help.producthunt.com/en/ 
- The FAQ page should cover all the necessary information about the idea submission process and approval criteria. To ensure that it meets the needs of users like MILES HARDIN, the content should be based on feedback from the usability test participants. 
  -  Note: We listed an initial draft of FAQ questions in our  [[DL - IdeaSpace] UXR Analysis, synthesis & ideation](https://www.figma.com/file/KJ4zv96IoAzh8FuoXNq2nB/%5BDL---IdeaSpace%5D-UXR-Analysis%2C-synthesis-%26-ideation?type=whiteboard&node-id=1254%3A2183&t=zqi9bDQma6M4OLAW-1 ) (FigJam file) 
- The language used on the FAQ page should be clear and concise, avoiding technical jargon or confusing terminology.
- The FAQ page should include examples and visuals where appropriate to help users understand the submission process and criteria.
- New visual design (hi-fi mockups) are designed for the FAQ page and follows the established Dev Launcher’s design guidelines.
- Mockups are web responsive and include mobile, tablet and desktop breakpoints.
- Final and approved mockups were included in the “LATEST DESIGNS” layer in Figma

----------------------------------------------------
### Sub-tasks:
- [ ] FAQ content: based on usability test 
- [ ] UX design: Hi-fi mockups for FAQ page + landing page

----------------------------------------------------
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnBjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bbc587ccf0918ce2a8502bf8c584885768f2feb8/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzFjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7610be16ffeaa7c4b979a3583a61b91cd8c60680/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmRjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d52c9e965bc0c319eb771a36b085cd80a91c8ab0/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzljIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d34a4096a257181f56ca18fa5eb600f9e6154874/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEZjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2654cecff43be425688aa0c433eec4aa8611a4e/image.png)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1361?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @RETprojects @Rutuja177

**Comment by JulieMass** [comment]
Hey @MariliaDP ,

I made a list of initial FAQ questions based on the participant’s quotes from the usability testing. You can find more details of this in our [UX research Figjam](https://www.figma.com/file/KJ4zv96IoAzh8FuoXNq2nB/%5BDL---IdeaSpace%5D-UXR-Analysis%2C-synthesis-%26-ideation?type=whiteboard&node-id=0%3A1&t=zqi9bDQma6M4OLAW-1). 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTljIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1458ba3219a01bc79d873777016c3b05d67b9992/image.png)

However, I was wondering how you prefer to work on the content for the FAQ pages. Do you want to work on it together or is this enough? I don’t know how much you enjoy writing content, but we could also help ourselves with AI to speed up the content creation. 

Let me know what you think!

**Comment by MariliaDP** [comment]
Hi @JulieMass, this is great! Thank you so much for putting this together. 
I'm not very confident about writing the content on my own, so I'd love some help in this matter. I'll take a look at this document soon and see how I can start gathering answers for those questions.

**Comment by JulieMass** [comment]
@MariliaDP I just wanted to let you know that I selected an "8" for this ticket since it has two people assigned and we need to create both the content and the design. But please let me know if you think differently. Thanks!

**Comment by JulieMass** [comment]
_(CC. @NokaUX it would be interesting to have your point of view and see if the answers make sense to you too.)_

Hi @MariliaDP ,

Just wanted to let you know that I finished writing the initial content for all our FAQs, and I even added some new ones and refined some of the questions we had on our post-its.

Whenever you have a moment (either this week or the following after our Sprint Review as I know you might have a lot with your current ticket), I would really appreciate your feedback on two things:
- Did I miss anything in each FAQ answer?
- Is there a question that we haven't included that you think we should include?

Thanks so much!

https://docs.google.com/document/d/1BLsMWnznATd5Kq_igRYlyd2PTKCBgI9YFiAYxIT2LlA/edit?usp=sharing

**Comment by MariliaDP** [comment]
Thank you so much @JulieMass 
You are right, I didn't have time to start working on this ticket this sprint, but what you did is so helpful already. Thank you! I'll dive into it in the next sprint and let you know my answers.

**Comment by MariliaDP** [comment]
Just adding a link to the Design Working Section [HERE](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=6339-7900&mode=design&t=y51pv0a7RMjfsIpo-0).

**Comment by JulieMass** [comment]
@MariliaDP Oh, wow! I just took a sneak peek at what you're working on and I love where it's going 🤩! I'm going to move this ticket to the next sprint so you can keep working on it. I hope that's okay with you!

**Comment by MariliaDP** [comment]
@JulieMass 
I completed my review of the FAQ content. I didn't want to mess up the file, so I worked on a copy of it. You can find it here: https://docs.google.com/document/d/1SrNK2NrxxhA72wnJhr2y3nDElFBSsO-KekJw1gUhJco/edit

I think you covered everything. I just removed and tweaked a few things to be more straightforward.
Let me know if you have any questions!

**Comment by JulieMass** [comment]
Hey Marilia,

I finally had a chance to review the latest FAQ document with your changes. I've incorporated your feedback and cleaned it up. Thanks a lot for taking the time to review it! Your input was really valuable.

I have a question for you about the big buttons in Figma. I'm wondering if there's a way to make them visually more appealing and indicate that they are clickable, similar to the "back" button. Any thoughts on this?

Let me know what you think!

**Comment by MariliaDP** [comment]
Hi @JulieMass 
I adjusted those buttons on the FAQ page. Let me know if you like that solution.

**Comment by JulieMass** [comment]
Looks great @MariliaDP! Thank you!

**Comment by JulieMass** [comment]
Closing this ticket from a previous designer (Marilia). @julianalobosque is finalizing the designs of the FAQ page that were pending here and handling the migration with her ticket #1805.

(CC. @chadcrotchett, @dbradham, @AlinaU1 )
