### ISSUE TITLE
[UXR] Evaluative research for the top navigation - Step 1: Plan & logistics

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1363]
### Context:
We are conducting an **evaluative research study** to **improve the information architecture of IdeaSpace** and enhance the findability of our platform for our target audience. The business goal is to increase user awareness, findability and retention.

**Here are some initial questions we would like to address:**
- Labels for IdeaSpace navigation
  - What labels could we use for IdeaSpace to make it more clear and user-friendly?
- Category Label for "Dream"
  - What is a better category label for "Dream" that will help people discover our product in the top nav?

-------------------------------------------------

### Acceptance criteria:
The following outcomes have been created:
- Evaluative research plan which includes at least the following information:
  - Research background & goal
  - Key research questions
  - Method and tools to conduct which best answers the questions and is the most effective
  - Initial schedule
- Discussion guide (if needed)
- Screening & recruiting communications & logistics

-------------------------------------------------

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bc098826dfbf9cf93399997a7b9fbb2a9564b90/image.png)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1363?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @RETprojects @Rutuja177

**Comment by katehirschman** [comment]
Hey @JulieMass 

I think that works. Since both are about labels, it make sense to include the dashboard in this research.

**Comment by JulieMass** [comment]
Hey @katehirschman 

I finally got a chance to check out the plan and approach you defined for this research in EnjoyHQ. I think it's really good! Here are a couple of comments/suggestions from my side:

1. **I hope you don't mind, but I added some labels to the project**. I added the labels of "primary research", "ideaspace", "Survey", and "Preference Testing". Labels are high-level tags that will help stakeholders discover information throughout the search. This will become more important in the future as we'll have more and more research.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da611a55cdfffbde5fa80713cad9f2323bcc85b1/image.png)


2. **Is this a question for the test? "In your opinion, which label would be the best solution?" **If so, a minor suggestion from my side: I know you added some context on the top, but most people don't read, they scan. In case they scan the intro and jump directly to the question, it would be better to phrase the question in a more specific way. What is "best solution" for some might not be what we are looking for. Maybe we could ask something like: "Which label communicates the best that you’ll discover IdeaSpace product after clicking?" or "Which design makes it easier for you to discover IdeaSpace products on Dev Launcher's website?", or combine the problem statement and the question into one: "which top navigation label would be the best solution to effectively convey our product to new users of Dev Launchers?" It doesn't need to be those questions precisely, but I hope those examples help out. Also, if you are thinking of running a pilot test this would help checking the questions before launching the survey officially. =)

3. I think the rest of the questions after this initial question are very good as a follow-up! and I loved the intro too.

Lastly, whenever you're ready, just let me know what the next step is, and I'll create a ticket for you. 

I hope this helps!

**Comment by JulieMass** [comment]
Hey @katehirschman, thanks for your help! I think I understand those questions better now, and I appreciate you explaining that it's still a work in progress. Makes sense!

I was checking our last research to see how we split the steps, and based on your idea for next steps, it sounds like the next two tickets could be:
- Pilot test the survey
- Recruiting

How does that sound? 

I agree with you that this ticket includes the plan and all the logistics, so it makes sense that you're still working on it. Please don't rush at all. I was just trying to understand if any further tickets were needed for you. 

Thanks again Kate!

**Comment by katehirschman** [comment]
Hey @JulieMass sounds great!

**Comment by JulieMass** [comment]
As discussed with @katehirschman, we decided that the dashboard location expectation from our audience should be a separate research study, so I removed it from the ticket description. Here's what I removed:

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/2dee848b-6a36-47d2-85c6-d72e7e81a0fc)

**Comment by katehirschman** [comment]
Hi @JulieMass I sent you a draft of the survey - adding a link [here](https://www.surveymonkey.com/r/Preview/?sm=urIt_2FFGfSlNYZ3n2aL8ayaRryFUblV1C8P46xtNf3LKVY6WaQyc1LdhrGKs9IskL) for convenience. Look forward to your feedback!

**Comment by JulieMass** [comment]
> Hi @JulieMass I sent you a draft of the survey - adding a link [here](https://www.surveymonkey.com/r/Preview/?sm=urIt_2FFGfSlNYZ3n2aL8ayaRryFUblV1C8P46xtNf3LKVY6WaQyc1LdhrGKs9IskL) for convenience. Look forward to your feedback!

Uooojooooooo! Thanks Kate! I'll check it out asap

**Comment by JulieMass** [comment]
> Hi @JulieMass I sent you a draft of the survey - adding a link [here](https://www.surveymonkey.com/r/Preview/?sm=urIt_2FFGfSlNYZ3n2aL8ayaRryFUblV1C8P46xtNf3LKVY6WaQyc1LdhrGKs9IskL) for convenience. Look forward to your feedback!

Kate , this looks amazing 🤩🤩! Thanks for sharing it in advance! 

I'm excited to see what happens with this research and the feedback we receive. I have two small comments about the survey: 

- First, can we change "students" to "people" in the sentence "DevLaunchers is a nonprofit organization dedicated to empowering students"? Not all of us in Dev Launchers are students. If you have any other better suggestion please share it. "People" is the only one that came to my mind as a possible alternative 😆.

- Second, a small suggestion too:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlpkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17e978b0c0c5fdf7f2896265be4113713bde0127/image.png)


Let me know your thoughts!

**Comment by katehirschman** [comment]
Hi @JulieMass thank you for this feedback - I hadn't even thought of the double meaning of "solution" and have updated the survey.

**Comment by JulieMass** [comment]
I accidentally missed this ticket. Closing it a completed! Thank you @katehirschman
