### ISSUE TITLE
Conduct Typography Modular Scale Feedback Survey

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1378]
We need to gather feedback from stakeholders to make an informed decision between using Major Third or Perfect Fifth for our typography modular scale. The choice of a modular scale is critical for maintaining brand consistency and readability across our designs.

**Acceptance Criteria**
- Create a clear and comprehensive survey document.
- Distribute the survey among internal stakeholders, including designers, researchers, developers, and leads.
- Each target group has its own set of specific, relevant questions.
- Analyze results and provide a clear recommendation based on provided insights.

[**Major Third and Perfect Fifth Advantages Comparison**](https://docs.google.com/document/d/1uXHYW9LEehevSHDUCuOf2-OTGKCRjQDSntgR0QdkIKU/edit?usp=sharing)
[**Figma side-by-side Comparison**](https://www.figma.com/file/dBfjgptLt5c9GwMbmW09VF/refactoring-styles?type=design&node-id=371-2363&mode=design&t=51wJam8ySoK6oOyQ-4)

**Comment by Nouri-Anouar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1378?planning-poker) with Zenhub @annaisaacks @leeah-d @linakim602 @SiiiyanLiii @AmalJS00

**Comment by Nouri-Anouar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1378?planning-poker) with Zenhub @KatrinaCCC

**Comment by MaeCarlson** [comment]
@Nouri-Anouar Here is my idea for [survey questions](https://docs.google.com/document/d/1jPkXgbGQjEZHKqiICsTPPqyyekO82zk1_lco1WoDAK4/edit?usp=sharing). I will also follow up with you on discord with more comments.

**Comment by MaeCarlson** [comment]
[Modular Scale Survey_October 15, 2023_10.41.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjAzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--893f65a14e4a735bb55d4dac877b3a67b1ec8b4f/Modular%20Scale%20Survey_October%2015%2C%202023_10.41.xlsx)
[ModularScaleSurvey_Results.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjQzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b66045ff3c15c82ea755e1cc8f4a8efc218e97d9/ModularScaleSurvey_Results.pdf)

Attached are the response reports of the survey.
