### ISSUE TITLE
Usability Testing Planning and Setup for Dev Launchers Mobile Navigation

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1396]
This ticket is dedicated to the initial planning and setup required for conducting usability testing of the mobile navigation of Dev Launchers. The goal is to enhance the usability, intuitiveness, and accessibility of mobile navigation.

**Acceptance criteria:**
The following outcomes have been created:
- Usability testing plan
- Discussion guide
- Screening & recruiting communications & logistics

**Comment by linakim602** [comment]
@Nouri-Anouar Here is the documentation for the usability testing plan: [](https://docs.google.com/document/d/1f1ItD1ErizUcf-wdLjUoqRXtJoRfClnE/edit?usp=sharing&ouid=117125072838308761243&rtpof=true&sd=true)

**Comment by Nouri-Anouar** [comment]
> @Nouri-Anouar Here is the documentation for the usability testing plan: [Link](https://docs.google.com/document/d/1f1ItD1ErizUcf-wdLjUoqRXtJoRfClnE/edit?usp=sharing&ouid=117125072838308761243&rtpof=true&sd=true)

Thank you, Lina!

**Comment by linakim602** [comment]
@Nouri-Anouar @JulieMass Usability Testing Report: https://docs.google.com/presentation/d/1j9gymjWb8_Wsxb3IQg_prBn6j6CZf06m/edit?usp=sharing&ouid=113571146445494703873&rtpof=true&sd=true

**Comment by Nouri-Anouar** [comment]
> @Nouri-Anouar @JulieMass Usability Testing Report: https://docs.google.com/presentation/d/1j9gymjWb8_Wsxb3IQg_prBn6j6CZf06m/edit?usp=sharing&ouid=113571146445494703873&rtpof=true&sd=true

Thank you very much, Lina!

**Comment by JulieMass** [comment]
> > @Nouri-Anouar @JulieMass Usability Testing Report: https://docs.google.com/presentation/d/1j9gymjWb8_Wsxb3IQg_prBn6j6CZf06m/edit?usp=sharing&ouid=113571146445494703873&rtpof=true&sd=true
> 
> Thank you very much, Lina!

@linakim602 @Nouri-Anouar 
Hey, thanks for sharing this. I'll make sure to share this report with our team. 

As for the Dream labels and IdeaSpace navigation, we're aware that it's confusing, and we're currently doing research to improve it. I also noticed that you might be running a card sorting exercise in the next steps.  I recommend also involving @katehirschman in this effort or any type of research effort that involves our project, as she might have valuable insights and to avoid overlapping efforts within our teams.  

Lastly, I couldn't find this document in our common Google Drive folder. If it hasn't been added yet, I suggest we add it for transparency and to allow all members of the organization to access the research information of the universal design team. 

Thanks!

**Comment by JulieMass** [comment]
Hey @linakim602, here's the link to the research folder for the Universal design team: https://drive.google.com/drive/folders/14w3MfkM1myg6q0jWpoT_hqFE-wGW9P-k?usp=sharing . Could you please add this report and all the resources related to this research to this folder? Having this information open in our Google Drive can bring transparency and allow access to all members of the organization, which can help avoid duplicated efforts and also enable members to see how other teams conduct research and learn from each other. 

@Nouri-Anouar I think we are also missing the guide document that Siyan created for the usability testings. Can you please help us making sure all the research documentation of the universal profile team is open and available for everyone in our google drive? All the teams are sharing their research information there as well.

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/14d26caf-affe-4ebf-8f01-d657e22e2779)

Thanks a lot!

**Comment by Nouri-Anouar** [comment]
Hi @JulieMass, I apologize for the delay.
I have added shortcuts for Lina's and Siyan's files to that folder (shortcuts for now).
Thank you for the heads up!

**Comment by JulieMass** [comment]
> Hi @JulieMass, I apologize for the delay. I have added shortcuts for Lina's and Siyan's files to that folder (shortcuts for now). Thank you for the heads up!

Thank you Anwar!

**Comment by linakim602** [comment]
@JulieMass @Nouri-Anouar It looks like Anwar has already added the report file to our folder. Thanks, Anwar! I've also put the usability test plan in the same folder. Thank you for letting me know, Julie. I'll make sure to share the files in our team folder as well.

**Comment by JulieMass** [comment]
> @JulieMass @Nouri-Anouar It looks like Anwar has already added the report file to our folder. Thanks, Anwar! I've also put the usability test plan in the same folder. Thank you for letting me know, Julie. I'll make sure to share the files in our team folder as well.

Thanks Lina!
