### ISSUE TITLE
Integration Figma Component Documentation 

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1417]
**Description:**
We need to add documentation for our Figma components. The documentation is already prepared in separate documents and needs to be integrated into the design system for better accessibility and usability.

**Comment by AOHEE** [comment]
@Nouri-Anouar where can I find the prepared documentation for this?

**Comment by AOHEE** [comment]
@Nouri-Anouar I saw that for the button, there was this description already so I just pasted the description from the google docs on top. Let me know if I can remove the initial description that was already there. [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0hrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--60ff6b2cf3550284ae93004b4d973fe2b70bc810/Screenshot%202023-09-27%20at%204.39.22%20PM.png)

**Comment by AOHEE** [comment]
So far the components that I haven't added a description to are: back button, interaction buttons, typography and slider since it says they are either on hold or there isn't a description. I added the links, though (except for typography).

**Comment by Nouri-Anouar** [comment]
> @Nouri-Anouar I saw that for the button, there was this description already so I just pasted the description from the google docs on top. Let me know if I can remove the initial description that was already there. [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0hrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--60ff6b2cf3550284ae93004b4d973fe2b70bc810/Screenshot%202023-09-27%20at%204.39.22%20PM.png)

@AOHEE Yes, feel free to replace the existing button description.

**Comment by Nouri-Anouar** [comment]
> So far the components that I haven't added a description to are: back button, interaction buttons, typography and slider since it says they are either on hold or there isn't a description. I added the links, though (except for typography).

That sounds good, thank you! I will take an overall look tomorrow and provide you with feedback.
