### ISSUE TITLE
[Dev][User Profile][Edit Profile Modal][1] — Edit Profile Modal creation (Blank Modal Only)

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1430]
As Nancy newbie
I want to change something in my profile
so that I can keep my information up to date

Given I am signed onto my profile
when I click the "Edit Profile Button"
then the edit profile modal will appear

Given the onboarding modal is open
when I click the X button
then the edit profile modal will close

What you will be creating: 
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0YxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7c77dd0257e28e32292ee05085a014555ad27fd/image.png" alt="image.png" />

The Final Stage of the modal: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdS95IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--469a03878b42129613c98f550a669ecfcc0a6b91/image.png)

**Comment by ethanzlevin** [comment]
Do not create interests tab

**Comment by judeamos** [comment]
1. Create a new folder in the `apps/user-profile/src/components/modules/UserProfile`, called ProfileEditModal. 
2. Create respective files e.g index.js styled files etc. 
3. Implement the modal.
- You can use the IntroductionModal as a reference, located in `src/components/modules/UserOnboardingModal/IntroductionModal`

**Comment by judeamos** [comment]
You can get the dimensions of the modal from Figma: https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/User-Profile-%2F-Onboarding-Main-File?type=design&node-id=1431%3A15138&mode=design&t=3waiJH5bAjE5qPch-1

-Image of where the modal design is located in Figma

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGwxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22e216609262c2f75bfeeffe03920c7693f328df/image.png" alt="image.png" />

**Comment by judeamos** [comment]
This has been completed and is in production.
