### ISSUE TITLE
Global Grid component

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#1447]

**Comment by Enjoy2Live** [comment]
@Nouri-Anouar @leeah-d Let's meet to discuss this further.

**Comment by Nouri-Anouar** [comment]
@Enjoy2Live Sure! I should be available next week.

**Comment by Enjoy2Live** [comment]
@Nouri-Anouar let's talk about this in the meeting you schedule on the 25th. feel free to invite any team member who might benefit from this!

**Comment by Enjoy2Live** [comment]
fixed in #1716

**Comment by Enjoy2Live** [comment]
fixed in #1716
