### ISSUE TITLE
[Dev][User Profile][Edit Profile Modal][2]  — Edit Modal creation (Tabs & Modal Layout only)

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#1458]
As a Dev Launchers User
I want an edit modal
so that I can edit my entire profile in one place

Acceptance Criteria
Given the Edit Modal is open
when I click on any given tab
then the modal will change to a window correlating to that tab

This is what you'll be adding on to the Edit Profile Modal (which should have already been created)
<img width="1107" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUYxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--914344021ec11fd49f9bd731d3ae30cc5d8e6832/image.png" alt="image.png" />

**Comment by judeamos** [comment]
Book some time with me, so we can plan how to structure the front end to achieve this.

**Comment by judeamos** [comment]
This has been completed and is in production.
