### ISSUE TITLE
[Talent Community page] As a potential member, I want Dev Launchers to provide opportunity to join the talent community if I do not find suitable open positions available

### ISSUE THREAD

**Issue by Srividya1394** [dev-launchers/dev-launchers-platform#1467]
- Link to join talent community needs to be added in the footer section of join landing page and subsequent pages
- Include the following text and CTA button(Join the talent community) to join : "Join the Dev Launchers Talent Community

Join the Dev Launchers Talent Community to be notified about new volunteering roles that match your skillset!"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ae82e3a31e3a3be763138a24788b3ce7df8c17b/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--747493f934fad0f087d05669ee815bfd0f606e68/image.png)

**Comment by ramy-coder** [comment]
Merged to staging/recruitment
