### ISSUE TITLE
[Talent community page] As a potential member, I want DL Talent community page to acknowledge with a message once I submit contact details to join the community

### ISSUE THREAD

**Issue by Srividya1394** [dev-launchers/dev-launchers-platform#1470]
- When the user fills in mandatory fields and clicks on submit button, redirect to thank you message page
- Include following message - " Thank you! Your application for the Dev Launchers Talent Community has been received.   We will email you when a volunteer role that matches your skillsets and/or interests opens up!" (Refer image)
- Include View current open roles button below the message. This button leads to Join page landing displaying all the open roels

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64811edcbb7a7d1bc263b24e0ef899b14bb4f53d/image.png)

**Comment by jeyanthi-sm** [comment]
https://github.com/dev-launchers/dev-launchers-platform/pull/1850

**Comment by jeyanthi-sm** [comment]
After the review, I added the Terms and Conditions checkbox
