### ISSUE TITLE
[SPIKE] In order to clarify and ensure that the feature of “save an idea" is suitable for our target audience, the UX Designer needs to conduct an activity with the team.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1506]
### Context:
The team has encountered some confusion regarding the features of "like" and "save" for an idea. To clarify any differences and ensure that the feature of "save an idea" is suitable for our target audience, we’ll be conducting an activity with the team. 

-------------------------------------------------

### Acceptance criteria:
- The UX Designer will schedule a meeting with the team to conduct the activity.
- The activity involves a discussion of the current "save" feature for an idea and its difference with the "like" button.
- The UX Designer will document the feedback and incorporate it into the following designs if necessary:
   - ideas page
   - workshopping page

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1506?planning-poker) with Zenhub @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @NokaUX @RETprojects @Rutuja177 @Sherry19971998

**Comment by JulieMass** [comment]
Hey @MariliaDP ! Just wanted to let you know that I added the task we talked about in our last weekly to our backlog so we can get started on it. If there's anything I missed or if you think there's anything else we should add or change, please let me know. 

Also, I won't be able to make it to our next weekly, but please feel free to lead the activity with the team during our meeting. 

Thanks a lot!

**Comment by MariliaDP** [comment]
@NokaUX  here are a few links to help you work on this task:

WIP Figma: https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=6454-8393&mode=design&t=Hh1VlXdbjdzRcPkA-0

Activity with the team: https://www.figma.com/file/KJ4zv96IoAzh8FuoXNq2nB/%5BDL---IdeaSpace%5D-UXR-Analysis%2C-synthesis-%26-ideation?type=whiteboard&node-id=1886-3079&t=9Q6pC6pUsIhQMgKU-0

Inspiration Board: https://www.figma.com/file/8CWv3yX3090jWWo4nNAF25/%5BDL---IdeaSpace%5D-Analogous-Inspiration?type=design&node-id=1708-28&mode=design&t=TlaZZUkD03YZsbbX-0

**Comment by JulieMass** [comment]
Hi @MariliaDP I'm marking this ticket as completed. We generated a new ticket for @NokaUX to proceed with the design task, building on the work you facilitated with the team. Thank you so much for everything!
