### ISSUE TITLE
[Dev](User Profile) Improve Edit Profile Picture Button UI

### ISSUE THREAD

**Issue by awaswick** [dev-launchers/dev-launchers-platform#1510]
As Nacy Newbie
I want to update my profile picture 
So that my picture is more professional. 

Given I am on the Upload Photo Screen
When I click “Choose Files”
Then I can select a file.jpg to upload from my PC to my user profile 
(what are the size and file type requirements?) 

Given I am on the Upload Photo Screen
When I drag and drop a file.jpg into the dotted line square
Then the dropped file.jpg is uploaded to my user profile
(what are the size and file type requirements?) 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c9cc7223e5577d8241f3f802a785201ea7a3b8c/Edit%20Photo_upload_photo.png)

**Comment by judeamos** [comment]
A new line of story was created to cover this. This is not needed anymore
