### ISSUE TITLE
Fix File Upload Component Responsiveness

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1513]
**Description:**
The file upload feature within the design system on Figma is experiencing responsiveness issues. When accessed on different devices or screen sizes, the file upload component fails to adapt appropriately, causing usability concerns.

**Acceptance Criteria:**
- Ensure the file upload component is responsive across various screen sizes.
- Test the file upload on Figma to confirm responsiveness and adaptability.
- Document any specific breakpoints or design guidelines for responsive behavior.

**Comment by yzabelcabral** [comment]
Hi, I have finished the issue. Here are the changes I've made. Please leave any feedback. https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/DL-Universal-Design-System?type=design&node-id=10528%3A7981&mode=design&t=DmzvERXvOJshUurR-1

**Comment by Nouri-Anouar** [comment]
Hi @yzabelcabral thank you for the update.
I like how you made a sub-component for the loading bar as it can be reusable in other areas.
Also, I like the responsiveness of the first variant.

Is it possible to make the 2nd and 3rd variants responsive as well? I tried resizing the frame with no impact.
And can you move the component to the organisms page?

**Comment by yzabelcabral** [comment]
Thank you so much for your feedback! 

 - I have made the  2nd and 3rd variants responsive
 - I have moved the component to the organisms page. 

Please let me know if you have any questions, if not, please feel free to assign me another task.
