### ISSUE TITLE
Refine Checkbox Component Design

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1564]
**Description:**
Enhance the checkbox component's design for improved usability and consistency.

**Acceptance Criteria**
  - [x] Update checkbox hover state: Remove background and shadow styles.
  - [x] Ensure consistent and clear hover, active, and focus states.
  - [ ] Confirm the component's adherence to accessibility standards.

**Comment by Nouri-Anouar** [comment]
Hi @JulieMass 👋
I have made some updates to the checkbox variants, let me know what you think:

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/79311912/093d1873-2d39-4505-8953-6c3b1d9433c1)

And here is a prototype of what it would look like:
![chrome_39TaiqfBzr](https://github.com/dev-launchers/dev-launchers-platform/assets/79311912/bd9e0f01-db6b-417d-ba2d-8b6f1dacaf1f)

**Comment by JulieMass** [comment]
Hi @Nouri-Anouar , I just got back from my holidays. Thanks for advancing with this! 

I think it looks great 😀, but I was wondering if we could use a different color for the "selected" checkbox instead of black. I know you might have chosen dark gray for the disabled checkbox to make it accessible for color-blind people, but there isn't much difference between black (selected) and dark gray (disabled). 

What if we use the color of the primary buttons or another color and keep the dark gray for the disabled? Let me know your thoughts!

**Comment by Nouri-Anouar** [comment]
Fantastic suggestion, @JulieMass! I've come across this idea in a few design systems, and incorporating it would really enhance the component. How about this?

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/79311912/7bed1301-d2ee-4851-9c46-88fa24f866c1)

**Comment by JulieMass** [comment]
> Fantastic suggestion, @JulieMass! I've come across this idea in a few design systems, and incorporating it would really enhance the component. How about this?
> 
> ![image](https://private-user-images.githubusercontent.com/79311912/294579870-7bed1301-d2ee-4851-9c46-88fa24f866c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDU1MDMsIm5iZiI6MTcwNDU0NTIwMywicGF0aCI6Ii83OTMxMTkxMi8yOTQ1Nzk4NzAtN2JlZDEzMDEtZDJlZS00ODUxLTljNDYtODhmYTI0Zjg2NmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDEyNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMDRkMGM5NWJlYjBmN2JlMzQ0NGQ0ZDFkM2UxMWYwMTQ1ODVhNjY5ZDBmNmNiNDc3MjE3Mjc2OGRkYjAzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYvYnAkvDL4Gvzo7w4e5glrB9GhfkG7bacfeD2g3t3Q)

This looks GREAT Anwar 👏👏 !! 

@Nouri-Anouar What would be the next step from here? @Enjoy2Live Should we work on developing this component with the platform enablement team, or should our team handle it? If so, please keep us in the loop once it's done. Our team has a bug ticket (#1270)  which it's currently blocked waiting for this enhancement.

(CC. @dbradham)

**Comment by Nouri-Anouar** [comment]
@JulieMass I will get some feedback and approval from our designers tomorrow and mark it as ready for development.
Then, I will work with Mohammed to create a ticket on the PE backlog and attach it here and you can attach it to #1270 as well. 

We will keep you posted.

**Comment by JulieMass** [comment]
> @JulieMass I will get some feedback and approval from our designers tomorrow and mark it as ready for development. Then, I will work with Mohammed to create a ticket on the PE backlog and attach it here and you can attach it to #1270 as well.
> 
> We will keep you posted.

Sound good @Nouri-Anouar! Thank you!

**Comment by Nouri-Anouar** [comment]
@JulieMass here is the development ticket #1605 on the PE team backlog.

**Comment by JulieMass** [comment]
Awesome! Thanks @Nouri-Anouar ! I'll link it as a dependency to our ticket so we can keep better track of it.
