### ISSUE TITLE
Implement Enhanced Checkbox Component Design Changes

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1605]
**Description**:
Develop and implement the refined checkbox component design as outlined in ticket #1564 for improved usability and consistency.

**Acceptance Criteria:**
- Update the checkbox according to the new component's design.
- Verify the checkbox component's adherence to accessibility standards post-implementation.
- Ensure the changes are compatible across multiple browsers and devices.
- Test and validate the changes in different scenarios, including edge cases.

**Comment by Enjoy2Live** [comment]
https://www.radix-ui.com/primitives/docs/components/checkbox#checkbox

**Comment by Enjoy2Live** [comment]
Hi @JulieMass , I hope you are doing well!
Our new member [@l1keafox](https://github.com/l1keafox) is taking ownership of this task and will be in contact with you and your team when there's updates :smile:

**Comment by JulieMass** [comment]
> Hi @JulieMass , I hope you are doing well! Our new member [@l1keafox](https://github.com/l1keafox) is taking ownership of this task and will be in contact with you and your team when there's updates 😄

Awesome! Great to have you on board @l1keafox. Thanks, both of you!

**Comment by JulieMass** [comment]
Hey everyone,

I've responded in Discord too. Big thanks to @Enjoy2Live for sharing the storybook link. Also, awesome job @l1keafox 👏👏! It really matches what @Nouri-Anouar designed 😀. If there's anything else we need to do from our side, just let me know please.

Thanks again, this will really help our team fix the checkbox in the submission form.
