### ISSUE TITLE
Remove duplicated code

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#1622]
Currently we have many unused files that aren't being imported anywhere due to the move from polyrepo to monorepo architecture. 

- [x] remove unused files from dev-recruiters and make sure it works
- [x] remove unused files from ideaspace and make sure it works
- [x] remove unused files from site-projects and make sure it works
- [x] remove unused files from website and make sure it works

**Comment by NomarGomez** [comment]
Merged
