### ISSUE TITLE
Fix Member Since Text

### ISSUE THREAD

**Issue by judeamos** [dev-launchers/dev-launchers-platform#1658]
When you land on the user profile page, below the profile picture, there is a text that says "Member Since: Invalid Date". 
This text is meant to show "Member Since: [date the person joined]". The reason it's showing "invalid date" is because the variable that it used to render and show the date is `undefined`. 

Add an extra use condition, that checks if the `created_at` variable is undefined or null. 
- If it is undefined/null, then don't show the "Member Since: Invalid Date" text, meaning it should be completely blank. 
- If it does have a value, then show what ever value is passed back.

**Comment by judeamos** [comment]
You will be applying the fix in this ProfileCard.js 
`apps/user-profile/src/components/modules/UserProfile/ProfileCard/ProfileCard.js`

**Comment by judeamos** [comment]
To test whether your logic has worked, you can manually assign values to the `created_at` variable, like so below: <img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXduQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8950243856556d922dcca6cb02469b886d90f1a/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3c2b0a9ae8f91d7327f2729a63910c5afc24ece/image.png" alt="image.png" />

<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78f56db6d73c82e5ee5b8712c2647b2a8f659ec8/image.png" alt="image.png" />

**Comment by erinsgithubpage** [comment]
Thanks, Jude!

**Comment by judeamos** [comment]
This has been completed and is in production.
