### ISSUE TITLE
Popover content for notifications list

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#1667]
Currently we have a Notification item and generic popover component to display content after clicking a button, it's now possible to build out a popover triggering button with bell icon like shown in the following figma prototype https://www.figma.com/proto/bRIJ0K4oLzZlLNfYzGmsVe/%5BDev-Launchers%5D-Notifications-Feature-UX-Designs?node-id=1-3208&t=RGq9RRc6rbkgu4hH-1&scaling=min-zoom&content-scaling=fixed&page-id=1%3A3&starting-point-node-id=1%3A3208

## Acceptance Criteria
- Notification bell button appears when the user is logged in
- When the bell button is clicked a popover appears with the content being as show as the design (check link above)
- Clicking mark all as read removes the dot from unread notifications (by altering notification entities through an http request)
- Clicking on "<icon> settings" takes you to /notifications/settings
- Clicking on "view all notifications" takes you to /notifications

**Comment by dbradham** [comment]
@yacineKahlerras is anything blocking you from making progress on this ticket?

**Comment by yacineKahlerras** [comment]
@dbradham nope waiting for api to complete so i can finish it properly

**Comment by dbradham** [comment]
@yacineKahlerras are you waiting on the same data here as the other ticket? Or is this dependent on something different in the api?

**Comment by chadcrotchett** [comment]
@Enjoy2Live @dbradham what's the purpose/use case for notifications? Should IdeaSpace expect to use notifications for new ideas/edits/comments/upvotes?
