### ISSUE TITLE
[DEV][User Profile][Redesign][Side Nav Bar][2] — [UI]  Side Menu Links

### ISSUE THREAD

**Issue by judeamos** [dev-launchers/dev-launchers-platform#1702]
Add the side nav bar links as shown in the image below:

- Each menu link should have a hover effect
- Each menu link should have an active state effect
- The active state will be activated when the user is on the linked page 

Add the profile image and name at the top

<img width="951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1NuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7ec6b8bbdd5626a1455855682926b83c4890f8f/Overview-2.png" alt="Overview-2.png" />

**Comment by judeamos** [comment]
This has been completed and is in production.

**Comment by judeamos** [comment]
The Overview Link is working and in production, need to test the remaining link. 
Public view implementation needs to be added — to hide side nav bar if in public view mode.

**Comment by KMallare** [comment]
![Image](https://github.com/user-attachments/assets/59c6bd0d-b978-471b-845f-aeffaa5321cf)
