### ISSUE TITLE
[DEV][User Profile][Redesign][Overview Page][1] — [UI & Function] Bio

### ISSUE THREAD

**Issue by judeamos** [dev-launchers/dev-launchers-platform#1705]
The Bio section on the Overview Page: 

- Build out the UI design for the Bio section, as shown in Figma
- The Edit Button should open up the Edit Profile Modal, and the bio tab should be opened in that modal

Figma Design: 

<img width="955" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--925f82b2daa9ffaa962a9494142e4948a0c4cbf8/Overview-bio.png" alt="Overview-bio.png" />

**Comment by judeamos** [comment]
Using this new global component,

**Comment by KaitlynMallare** [comment]
The Edit Button should open up the Edit Profile Modal, and the bio tab should be opened in that modal - Last thing to do !

**Comment by KMallare** [comment]
![Image](https://github.com/user-attachments/assets/78d6165b-1ccf-4fe1-809d-192b159a6586)
