### ISSUE TITLE
[DEV][User Profile][Redesign][Overview Page][3] — [UI & Function] Interests

### ISSUE THREAD

**Issue by judeamos** [dev-launchers/dev-launchers-platform#1708]
The Interests section on the Overview Page: 

- Build out the UI design for the Interests section, as shown in Figma
- The Edit Button should open up the Edit Profile Modal, and the Interests tab should be opened in that modal

Figma Design: 
(ignore the blue highlight around it) 
<img width="960" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEtuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63acee79247b42c1f4ed1b8e71268975cece25a2/image.png" alt="image.png" />

**Comment by judeamos** [comment]
For this task:
- Create a new component in the Overview Folder, called Interests. 
- Render the interests bubble inside the global container component
- There should already be a bubble component already created.

**Comment by KMallare** [comment]
![Image](https://github.com/user-attachments/assets/6f743a48-480a-4efa-b4ff-90188a028d74)

**Comment by judeamos** [comment]
The edit button modal implementation will be added in another story.
