### ISSUE TITLE
Rebase development/community with master

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#1725]
Our branch `development/community` is currently behind master by 300+ commit. We need to be aligned with other teams and rebase `development/community` from master.

## steps

1- Goto master branch `git checkout master`

2- Pull all the changes from github for master branch`git pull origin master`

3- Goto development/community branch `git checkout development/community`

4- Pull all the changes from github for development/community branch `git pull origin development/community`

5- Start rebasing the latest commits you just pulled from  development/community to master `git rebase master`

6- Push the changes and the rebased branch you have to GitHub `git push -u origin development/community -f`

7- Verify on [here](https://github.com/dev-launchers/dev-launchers-platform/tree/development/community) that `development/community` is no longer behind master as shown in the attached screenshot 
![Screenshot_20240321-052027_Chrome.jpg](https://github.com/dev-launchers/dev-launchers-platform/assets/27841994/45454490-c062-4fd0-aa82-8b1b487cc060)

**Comment by NAsriGhada** [comment]
I got this error <img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHI5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de025883b3c1a9c57d7f0d6f55972eab4a4b32c7/Screenshot%202024-03-21%20161743.png" alt="Screenshot 2024-03-21 161743.png" />

**Comment by Enjoy2Live** [comment]
fixed
