### ISSUE TITLE
[DEV][User Profile][Onboarding][Upload Profile][1] — [UI & Functionality] Button

### ISSUE THREAD

**Issue by judeamos** [dev-launchers/dev-launchers-platform#1734]
What to do: 
1. Add a camera icon to the Profile Icon on the onboarding page. 
2. Add on click functionality — if the user clicks on the camera icon, then a File Explorer modal should pop up that allows the user to pick the photo they want. 
- They should only be able to select only image-based files, if possible limit them to png & jpg 
- There should be a limit on how big the file should be. 

<img width="993" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29pQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cde8cc932edd9e785f438d6a5281c7830f6f2e6/image.png" alt="image.png" />

**Comment by judeamos** [comment]
You will need to do some research on the best way to implement this functionality. 
- Speak to chung-ting to ask for the file size limit
- Look up how to use `<input type="file" />` — this is the html tag you can use to upload files from your own system. 

There will be another story explaining the 2nd implementation.

**Comment by wimaan3** [comment]
Thank you sounds good

**Comment by wimaan3** [comment]
Currently working on integrating the backend of saving the user-uploaded profile picture into our Strapi data collection.

Here is a breakdown of the integration for future developers that need to complete similar tasks.

When a user signs into Dev Launchers or creates a new account, they are redirected to the Google sign-in page. Once authenticated their gmail, Google username, and Google profileURL is passed to the Strapi backend. If there was not a user with the same gmail from before then the backend creates a new user. 

A profile is created at the same time with the name and URL to their profile picture. The code for this authentication can be referenced [here.](https://github.com/dev-launchers/strapiv4/blob/main/src/extensions/users-permissions/server/services/providers-registry.js#L90-L112)

Once users click save and continue on the onboarding landing page form, we need to upload the profile picture to the Strapi backend and store the URL of where the picture is uploaded to which can be replicated [here.](https://www.restack.io/docs/strapi-knowledge-strapi-rest-api-upload-image#clq65voa70zppvh0v1jumxcdw)

**Comment by judeamos** [comment]
This has been completed and is in production.
