### ISSUE TITLE
[UXR] Top Nav Preference test - Step 4: Data Synthesis & Report

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1762]
### Context:
We’ve conducted an evaluative research study to improve the information architecture of IdeaSpace and enhance the findability of our platform for our target audience. The business goal is to increase user awareness, findability and retention.

**Scope of this task:**
In this task we are **sharing our findings and conclusions in a report to the team** as well as recommendations if future research is needed such as an A/B Test.

-------------------------------------------------

### Acceptance criteria:
- Collected data from the preference test is analyzed and synthesized.
- Findings, insights and recommendations are summarized in a report in our research repository EnjoyHQ. 
- Project report and recommendations are shared with the team.

**Comment by JulieMass** [comment]
Hey @katehirschman ,

As we discussed yesterday, I've created a ticket for you to work on the report and share your insights and recommendations with the team. I wanted to follow up on a few things:

1.Ticket Description: 
First, please let me know if the description of the ticket looks good to you. If so, could you please provide a final estimate for the work? Since you won't be able to join our planning meeting next week, I thought we could just go ahead and have you decide on the final estimation instead of involving the whole team.

2. Sharing Recommendations:
Whenever you're ready to share your recommendations from this research, please let me know. I'll be happy to create any new tickets that might be needed. For example, if you decide that we don't need an A/B test because the data we have is sufficient to move forward with a decision, I'll create a ticket for development to make those changes, as well as a ticket for your next research study (maybe interviews to learn more about our personas and the market fit of our product?). On the other hand, if you feel an A/B test is the best approach because you're not entirely sure about the data from the preference test, I'll go ahead and create a ticket for that.

Let me know your thoughts on these next steps.

**Comment by katehirschman** [comment]
Hi @JulieMass 
Looks great! I added my estimate and should have the report completed in a few weeks. I'll let you know as soon as I've figured out next steps, but leaning towards the A/B test idea.

**Comment by katehirschman** [comment]
Hi @JulieMass 
Here is a link to the report: https://app.enjoyhq.com/sh/pj/f80e9a2b-482c-4981-9eba-60ef920a441f
Let me know what you think!

**Comment by JulieMass** [comment]
Hey @katehirschman ,

This is amazing 👏👏!! Overall I love how simple you made it! We can share this at our next sprint review on the 5th of May and you can show it off to the team. That way, they don't have to go read it themselves: you can just present it to them and boom, problem solved! Efficiencyyyyy 😎

Below a question and a thought:

- Question: The below paragraph was a bit confusing for me. What do you mean by "as an option for SECOND CHOICE answers"? If the first part says that "Collaborate was chosen as the first choice by 8 participants and Innovate was chosen first by 6 participants", and then it says: "As options for second choice answers, Collaborate had 3 votes and Innovate had zero." So then...is collaboration a good choice or not? The part about "first choice" and "second choice" is a bit confusing.

After checking the form, I now understand what "first choice" and "second choice" means, but since it wasn't in the chart in the EnjoyHQ report, if someone reads your report from there only, it's a bit confusing. Either we could explain what we mean by "first and second choices", or we can show it in the chart like the Google form does. 
<img width="1074" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2c0c01886f2a2bb066e190e752116a120abf749/image.png" alt="image.png" />


- Suggestion/idea: At the end, we could add the link to the Google Drive folder, don't you think? To point to where the documentation of the process is located.

Let me know if this makes sense!

**Comment by katehirschman** [comment]
Hi @JulieMass  - thanks for the feedback. I see how that could be confusing. I added the ranking image from GoogleSheets to the report which hopefully clears that up. Also added a link to the google drive folder for the preference test. Do you think I should create a story to go along with the report? I feel like the report is a short read, but could always make a story to simplify further - let me know what you think! 

I shared the report at our Sunday meeting but can go over it again during the sprint review, once it's finalized. I also want to share on Discord with the Dev Launchers Home Page Redesign thread once everything is complete.

**Comment by JulieMass** [comment]
> Hi @JulieMass - thanks for the feedback. I see how that could be confusing. I added the ranking image from GoogleSheets to the report which hopefully clears that up. Also added a link to the google drive folder for the preference test. Do you think I should create a story to go along with the report? I feel like the report is a short read, but could always make a story to simplify further - let me know what you think!
> 
> I shared the report at our Sunday meeting but can go over it again during the sprint review, once it's finalized. I also want to share on Discord with the Dev Launchers Home Page Redesign thread once everything is complete.

Hey @katehirschman , thanks! I really liked the ranking image you shared from Google Sheets. It was super helpful.

I also forgot to mention it before, but I loved how you reused the story about users not finding the landing page in the previous usability test as a reference. That was a nice touch.

As for adding a story, I'll leave that up to you. From my perspective, I think what you've created is perfect, but I might not be fully grasping what you have in mind to include in the story. So I'll let you decide what you think is best for the documentation and the team.

Now, about the A/B testing: I've been thinking about that a lot. The main problem and reason we conducted this preference test is that we noticed people weren't finding IdeaSpace when they were asked about it. So, if the question we're trying to answer is: do people understand where IdeaSpace is and how to find it in DevLauncher, I'm wondering if the A/B testing is really the right way to validate this?

And if the question is more about which option is better for us: "collaborate" or "Innovate",  the A/B test will only give us “click” data. But does the amount of clicks really prove that one is better than the other? I feel like there's a high level of chance involved there. What if more people were just randomly clicking around on the website that day, and that's why one option got more clicks?

So, I've been thinking about this a lot, and I'm wondering what the actual research question is that we're trying to get answered with the A/B testing. I kind of feel like we might be selecting the method before we've really nailed down the research question. But I could be wrong, so let me know what you think!

**Comment by katehirschman** [comment]
Hey @JulieMass 

I agree about the story - just thinking of atomic research and wanting the nugget of information to be easily available, but it's pretty straight-forward as is.

For the A/B test, I was thinking we could keep Dream and add Collaborate as the alternative. In looking more into the responses, it's pretty clear Collaborate was the preference - Innovate was second best but it also tied for least liked option. I can see the issue with chance being involved and I haven't looked into A/B as a method yet. I think you're correct that the research questions should come first. 

I will think more about what the research question is - I'm generally curious about why Dream is the least clicked page and wondering if that's because it's an unclear label or if there's some other issue going on? Maybe trying Collaborate and Dream in an A/B test, seeing the analytics before and after might give us more perspective, but maybe there's a better method.

I'll think on it more - maybe the more foundational questions we discussed at our last meeting would be a better project. Perhaps we can set up something quantitative to study the label options that will need to be collected over time, then I can focus on more generative research.

We can discuss more at our meeting tomorrow!

**Comment by JulieMass** [comment]
Hey @katehirschman ,

Just checking in on this ticket. Are there any pending tasks or actions needed? If not, would you mind please moving it to "done" so I can close it out?

Thanks!

**Comment by JulieMass** [comment]
Hi @katehirschman ,

Thanks so much for marking the ticket as done! It completely slipped by me. I also wanted to reiterate my appreciation for your fantastic work on this research and the amazing report you put together 🙏.

I'm going to go ahead and close this ticket now since everything is complete 🎉 ✅.
