### ISSUE TITLE
[Platform] [User Notifications] Fetch and display user-specific notifications

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#1895]
**User Story:**

As a user, I want to see my personalized notifications on the UI so that I can stay updated on important information and take necessary actions.

**Acceptance Criteria:**

* User notifications are fetched from the server/strapi using Tanstack Query.
* Notifications are displayed in a clear and visually appealing format on the UI.
* Latest notifications are displayed first.
* The UI provides clear indicators for unread notifications.

**Additional Considerations:**

* Consider implementing pagination for a large number of notifications (on hold until research team confirms).
* Implement error handling for failed fetch requests.
* Implement loading state for when data is still being fetched.
* Provide options for filtering notifications based on type or status.

By meeting these criteria, the user will have a seamless experience in managing and interacting with their notifications.
 
**Would you like to delve deeper into any specific aspect of this user story, such as the UI design or the Tanstack Query implementation?** 
If so please ask your questions here!

**Comment by dbradham** [comment]
@yacineKahlerras are we ready to test these changes in the staging environment? Or is there more development work to be done?

**Comment by yacineKahlerras** [comment]
@dbradham yeah am waiting for the backend to add more data to the api so i can finish it

**Comment by dbradham** [comment]
@yacineKahlerras thanks! What data do you need specifically in the backend? Specifically, which collection(s) are you planning to access?

**Comment by dbradham** [comment]
Needs to be able to access:

1. user name that commented (now possible with the eventUser)

2. access to profile image (now possible with the eventUser ... we need to include the `user:profile`)

3. action + event name to be separate (we will add a new field in the schema for Event)

**Comment by dbradham** [comment]
@yacineKahlerras are you able to make a pull request to the `master` branch so we can deploy your code to staging?
