### ISSUE TITLE
Identify and remove all non-functioning actions

### ISSUE THREAD

**Issue by chadcrotchett** [dev-launchers/dev-launchers-platform#1915]
As an Idea Creator or Idea Viewer, I only want functionality displayed if it is working correctly from my updated Chrome Browser so that I avoid frustration, confusion, and lack of confidence in the organization.

Acceptance Criteria:
1. All non-functioning buttons within IMS (IdeaSpace Management System) are identified by the team and listed on this story. 
> Example: "Like" button on Idea Comments depresses but does not color in the heart or pop-up after mousing away until there is an additional click. 
2. Buttons are removed from visibility so a user will not be tempted to click them
3. Unsure if buttons should be 'removed' from code, or just 'commented out'. What's the usual process for this?

Definition of Done:
- [x] Remove Tag functionality
- [x] Remove Sort by Recent Ideas
- [x] Remove Sort by Time Commitment
- [x] Update "Back" button to "Browse other ideas" and link to https://devlaunchers.org/ideaspace/browse

**Comment by Ahsaask** [comment]
### Major Issues

1. Route: `/ideaspace/submit`

     - Inconsistent use of semicolons after question marks. Remove the semicolon after the question mark to ensure consistency across all labels.
     - Adjust the tooltip alignment and change its orientation to a horizontal layout, ensuring it does not cover any text beneath it.    
     - The final checkpoint [ ] [**_I have read the terms and conditions_**], does not provide a dropdown or any specific terms and conditions for the user to review, aside from the accompanying questions. Clarification is needed on what the "terms and conditions" refer to in this context.


         
         ![Image](https://github.com/user-attachments/assets/988aaf51-ebe7-4e0d-9a74-0724e51d89d6)


2. Route: `/ideaspace/browse`
 
     - The "Sort by Recent Ideas" option does not filter the list of idea cards or update the order of the displayed ideas.
     - The "Sort by Time Commitment" option does not function, possibly because no time commitment is collected from the user in the form. Further clarification is needed on how time commitment is intended to be provided by the idea owner.
     - The IdeaCard component has an issue where clicking around the edges of the card does not navigate to the idea page, while clicking within the text div does. This is likely due to the clickable property being applied only to the inner div. The entire card container should be made clickable to ensure consistent navigation.



          ![Image](https://github.com/user-attachments/assets/46620411-eb45-4d5e-94fc-0d633e064fc6)



3. Route: `/ideaspace/workshop/id`
     - The idea profile image is not displaying, possibly due to an issue with the image URL. If it’s intended to be a placeholder, add selectable images. In any case, an image should be pre-selected and displayed. Currently, the URL points to a placeholder.
     - Remove the crossbar symbol when there are no list tags, as it misleads users and encourages unnecessary clicks.
     - Fix the "Like" functionality in the comment section (currently commented out).



        ![Image](https://github.com/user-attachments/assets/d4d37ec0-6b3d-4a88-94d6-f6164999ad7f)




### Additional Issues

> These are some non critical issue's or probably just behaviours that could be discussed in the future or could be clarified in next stories.

- The back button at the top of any page navigates to the previously visited link rather than the intended route within the website's navigation structure. This can cause confusion, especially if the user is directed to a specific link. In such cases, clicking the back button may exit the website instead of returning to the previous page in the site’s navigation flow.
- Submit Buttons could have an UI Update to inform the user that a button has been clicked. Some of the current hover effects and on click effects are super subtle to be noticed. 
- New detailed story can be issued to document the UI issues, specifically spacing, margin, padding and major responsiveness discrepancies.

**Comment by chadcrotchett** [comment]
@Ahsaask Is there an option to move stories to "In review" based on whatever tool you were using to move this story to Done?

**Comment by chadcrotchett** [comment]
@Ahsaask @RETprojects Remi will take this feature: 
The IdeaCard component has an issue where clicking around the edges of the card does not navigate to the idea page, while clicking within the text div does. This is likely due to the clickable property being applied only to the inner div. The entire card container should be made clickable to ensure consistent navigation.

I'll take this feature:
The back button at the top of any page navigates to the previously visited link rather than the intended route within the website's navigation structure. This can cause confusion, especially if the user is directed to a specific link. In such cases, clicking the back button may exit the website

Everything else is Ahsaas's.

**Comment by chadcrotchett** [comment]
@Ahsaask Please remove the whole "Tags" functionality, as I have never seen that working or change.
"Remove the crossbar symbol when there are no list tags, as it misleads users and encourages unnecessary clicks."

**Comment by Ahsaask** [comment]
> @Ahsaask Is there an option to move stories to "In review" based on whatever tool you were using to move this story to Done?

I believe it's the github automation that moved it to "Done", maybe we should move the stories manually based on the kanban table.

**Comment by chadcrotchett** [comment]
Additional notes: 
remove "Generate Idea" from /ideaspace via new story
