### ISSUE TITLE
Onboard Andy

### ISSUE THREAD

**Issue by chadcrotchett** [dev-launchers/dev-launchers-platform#1982]
As an IdeaSpace Team Member, I want all team members to have a complete onboarding so they can quickly and confidently add value to the team.

**Acceptance Criteria:**
- [x] GitHub: Provide GitHub ID to @chungthuang and @chadcrotchett 
- [x] GitHub Projects: Assign self to this Onboarding item
- [x] GitHub Projects: Move item to "In Progress" once work starts on this item
- [x] Discord: Update server profile to display "First Last Name"
- [x] TLDV: Login via @devlaunchers account and watch https://tldv.io/app/meetings/66d48162283ef500135d7992/ and mention one thing you learned about the team or the solution
- [x] Confirm you are invited to at least these meetings:
  - [x] Sunday and Wednesday Team Meeting
  - [x] Sprint/Release Demo once a month
- [x] Review "Definitive Guide for Team Members" and comment on any corrections/clarifications: https://drive.google.com/drive/u/0/folders/1suuRuclHZPVxprv2v7iK9lMiqR-jPLeR
- [x] - [ ] Apply for Figma Educational Account here: https://www.figma.com/education/apply
  - [x] Use attached file as Syllabus: [Dev Launchers Syllabus.pdf](https://github.com/user-attachments/files/17138763/Dev.Launchers.Syllabus.pdf)
  - [x] Apply for Figma Educational Account with your @devlaunchers account here: https://www.figma.com/education/apply
- [x] Request a team member send a Figma invite to your @devlaunchers account via "Share" on upper right: https://www.figma.com/files/team/1254849222497104676/all-projects (and accept the invitation)
- [x] Figma: Confirm access to https://www.figma.com/design/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=8040-18045&t=LnN1mWZba9diatOd-4
- [x] StoryBook?

Additionally:

- [x] Update Dev Launchers Google account image for Strapi/Team page: https://devlaunchers.org/projects/DL-IdeaSpace#

- [x] Identify/receive one GitHub Project issue and successfully draft test cases that allow anyone at Dev Launchers to be able to quickly follow to confirm functionality is working as expected

**Comment by chadcrotchett** [comment]
@andyzhu7568 what is one thing you learned from the TLDV video?

**Comment by andyzhu7568** [comment]
> [@andyzhu7568](https://github.com/andyzhu7568) what is one thing you learned from the TLDV video?

since my account does not have access to this video ever after requesting assess, and since it is from 'Too Long, Don't View', I learned that it is likely another trap like StoryBook. Am I correct?

**Comment by chadcrotchett** [comment]
> > [@andyzhu7568](https://github.com/andyzhu7568) what is one thing you learned from the TLDV video?
> 
> since my account does not have access to this video ever after requesting assess, and since it is from 'Too Long, Don't View', I learned that it is likely another trap like StoryBook. Am I correct?

LOL, No, I really do want everyone to see that video. Good test on my test tho.

**Comment by andyzhu7568** [comment]
> [@andyzhu7568](https://github.com/andyzhu7568) what is one thing you learned from the TLDV video?

Finally able to watch it. What I learned is that I should look into GA tech CS master program, the one Remi is in lol
