### ISSUE TITLE
Onboard Sagar

### ISSUE THREAD

**Issue by chadcrotchett** [dev-launchers/dev-launchers-platform#1983]
As an IdeaSpace Team Member, I want all team members to have a complete onboarding so they can quickly and confidently add value to the team.

**Acceptance Criteria:**
- [x] GitHub: Provide GitHub ID to @chungthuang and @chadcrotchett 
- [x] GitHub Projects: Assign self to this Onboarding item
- [x] GitHub Projects: Move item to "In Progress" once work starts on this item
- [x] Discord: Update server profile to display "First Last Name"
- [X ] (SKIP) TLDV: Watch https://tldv.io/app/meetings/66d48162283ef500135d7992/ and mention one thing you learned about the team or the solution
- [x] Confirm you are invited to at least these meetings:
  - [x] Sunday and Wednesday Team Meeting
  - [x] Sprint/Release Demo once a month
- [x] Review "Definitive Guide for Team Members" and comment on any corrections/clarifications: https://drive.google.com/drive/u/0/folders/1suuRuclHZPVxprv2v7iK9lMiqR-jPLeR
- [x] Apply for Figma Educational Account with your @devlaunchers account here: https://www.figma.com/education/apply
  - [ ] Use attached file as Syllabus: [Dev Launchers Syllabus.pdf](https://github.com/user-attachments/files/17138763/Dev.Launchers.Syllabus.pdf)
- [x] Request a team member send a Figma invite to your @devlaunchers account via "Share" on upper right: https://www.figma.com/files/team/1254849222497104676/all-projects (and accept the invitation)
- [x] Figma: Confirm access to https://www.figma.com/design/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=8040-18045&t=LnN1mWZba9diatOd-4
- [ ] Install Developer Plug-in: https://www.figma.com/community/plugin/747985167520967365/builder-io-ai-powered-figma-to-code-react-vue-tailwind-more
- [X] StoryBook?

Additionally:

- [ ] Update Dev Launchers Google account image for Strapi/Team page: https://devlaunchers.org/projects/DL-IdeaSpace#

- [ ] Identify/receive one GitHub Project issue and successfully deploy that issue to QA environment while meeting the Definition of Done

**Comment by SagarDBhatt** [comment]
Items finished/Reviewed: 

1. TLDV: Watch https://tldv.io/app/meetings/66d48162283ef500135d7992/  ==> Access requested.
2. Figma: Confirm access to ==> Completed. 
3. Received invitation for Sunday and Wednesday Team Meeting. Need invitation for "Sprint/Release Demo once a month".
4. StoryBook? ==> Need access to Kanban board OR Jira ticket.

**Comment by chadcrotchett** [comment]
@SagarDBhatt Please check the boxes as you complete them

**Comment by SagarDBhatt** [comment]
Requested access to https://drive.google.com/drive/u/0/folders/1suuRuclHZPVxprv2v7iK9lMiqR-jPLeR

**Comment by chadcrotchett** [comment]
> Requested access to https://drive.google.com/drive/u/0/folders/1suuRuclHZPVxprv2v7iK9lMiqR-jPLeR

@SagarDBhatt please confirm you are using your @devlaunchers account to log into our google drive.

**Comment by chadcrotchett** [comment]
Sagar has stepped away from Dev Launchers.
