### ISSUE TITLE
Sort Ideas by number of Votes

### ISSUE THREAD

**Issue by chadcrotchett** [dev-launchers/dev-launchers-platform#1986]
As an Idea Workshopper, I want to sort by which idea cards have the MOST votes to see what is popular, as well as which idea cards have the LEAST votes so that I view which cards might be newer or received less attention so far, so that I can understand which ideas have the most momentum to move forward.

Acceptance Criteria:
- [x] Idea Workshopping page allows sorting by Ideas from Most Votes to Least Votes
- [x] Idea Workshopping page allows sorting by Ideas from Least Votes to Most Votes
- [x] Sort By Drop-down text suggested:
  - [x] Most Votes
  - [x] Least Votes
- [x] Order these as bottom two of drop-down list

**Comment by SagarDBhatt** [comment]
Assigned this task to myself.

**Comment by chadcrotchett** [comment]
No UI/UX changes, removing label

**Comment by chadcrotchett** [comment]
BLOCKED: Pending ability to deploy code to QA envt. Pending investigation with Dave and Remi.

**Comment by andyzhu7568** [comment]
BUGs: 
1, Ideas can NOT be sorted from the most upvotes to the least upvotes
2, Ideas can NOT be sorted from the Least upvotes to the Most upvotes
3,  'Sort By' dropdown button is NOT visible when have more than 3 ideas added.

**Comment by naiditao** [comment]
> BUGs: _Video Provided_ 1, Ideas can NOT be sorted from the most upvotes to the least upvotes 2, Ideas can NOT be sorted from the Least upvotes to the Most upvotes 3, 'Sort By' dropdown button is NOT visible when have more than 3 ideas added.
> 
>  bug.video.mp4

Hi Andy, I think you tested the wrong website. The code is about sort dropdown in workshopping page, not individual dashboard.

**Comment by andyzhu7568** [comment]
Thanks Vera, I will take a look today

**Comment by andyzhu7568** [comment]
> > BUGs: _Video Provided_ 1, Ideas can NOT be sorted from the most upvotes to the least upvotes 2, Ideas can NOT be sorted from the Least upvotes to the Most upvotes 3, 'Sort By' dropdown button is NOT visible when have more than 3 ideas added.
> > bug.video.mp4
> 
> Hi Andy, I think you tested the wrong website. The code is about sort dropdown in workshopping page, not individual dashboard.

Hi Vera, yes you are correct, I have removed the bug report and marked it as passed QA. Thanks

**Comment by naiditao** [comment]
> > > BUGs: _Video Provided_ 1, Ideas can NOT be sorted from the most upvotes to the least upvotes 2, Ideas can NOT be sorted from the Least upvotes to the Most upvotes 3, 'Sort By' dropdown button is NOT visible when have more than 3 ideas added.
> > > bug.video.mp4
> > 
> > 
> > Hi Andy, I think you tested the wrong website. The code is about sort dropdown in workshopping page, not individual dashboard.
> 
> Hi Vera, yes you are correct, I have removed the bug report and marked it as passed QA. Thanks

Thank you for your effort and time!

**Comment by andyzhu7568** [comment]
Passed QA on staging
