### ISSUE TITLE
Remove "Generate Idea" button

### ISSUE THREAD

**Issue by chadcrotchett** [dev-launchers/dev-launchers-platform#1993]
Remove/comment out the "Generate Idea" button, as that functionality is not scheduled to be available soon.

Work with our UX Team to determine what UI changes can be completed quickly and with medium effort.

![Image](https://github.com/user-attachments/assets/a14d3fa8-6b3a-4010-b02b-66aa36a57917)

**Comment by AlinaU1** [comment]
Figma: https://www.figma.com/design/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=11898-34211&t=An9N9lDYamWHOQDc-4

**Comment by Ahsaask** [comment]
MVP (Non responsive) 
Heading-font: Sans-serif - 32px - weight 700
Body-font: Nunito Sans - 16px - weight 400
CTA-font: Nunito Sans - 16px - weight 700

@AlinaU1 Please let me know if the spacing and styling is correct. Also, I was wondering should I change the IdeaSpace heading and body (Like we have on figma, or is it just the cards?) Thanks! 


![Image](https://github.com/user-attachments/assets/ff7f0396-a45b-4f16-bb86-28b5216d7d78)
![Image](https://github.com/user-attachments/assets/4eefd6a3-160d-4cb0-9235-38a79d9f4fda)
![Image](https://github.com/user-attachments/assets/e94e2c67-e30c-4a3d-b23a-cfa4ca9f958c)
![Image](https://github.com/user-attachments/assets/cff856b7-46ef-4db6-b238-8d562be757dc)


![Image](https://github.com/user-attachments/assets/f95c44c3-4b3c-4445-bea3-2441ccc5d4f9)

**Comment by AlinaU1** [comment]
Hi @Ahsaask,

Thanks a lot for the fast update! The cards look great and all the spacings and stylings within them are good 👍 

Just a few question: 
1. Can we adopt them for different screen sizes, e.g. change height, width and text sizes for different breakpoints?  I can give more details in Figma ![Image](https://github.com/user-attachments/assets/2d928e93-5994-44ee-99dc-3975a35f54e0)
![Image](https://github.com/user-attachments/assets/548ac6b0-47e3-41ba-aacf-deb83efaea6e)
![Image](https://github.com/user-attachments/assets/8a47a8f9-63c9-4cdd-8b03-d1119363d775)

2. I like it how the hover state works, which animation/transition was used?

3. Can we change the arrow icon to the one in Figma? 
![Image](https://github.com/user-attachments/assets/5c508805-9c59-48a1-a1cb-a1eb797ce87f)

 

As for the rest of the page's content (IdeaSpace heading and body), I'll provide details regarding this by Wednesday but let's have the gap between the cards and the content about 80px. ![Image](https://github.com/user-attachments/assets/a44f119f-b642-4c48-bb7c-0905fa0f0e4b)

Thanks again!

**Comment by Ahsaask** [comment]
Thanks for the feedback @AlinaU1

1) Yes! I can adopt them for different screen-sizes, though I have been having some struggles with it. I might need a day or so to figure that out. 

2) For the hover animation I am using `ease-in-out` and transition of `300`. If you want to explore more options here are some examples with visualization. https://tailwindcss.com/docs/transition-timing-function.

3) Yes, Its already changed in my environment, just not in the image. 

Thanks for the feedback, I will share new updates soon. Thanks!

**Comment by AlinaU1** [comment]
Great! thanks @Ahsaask 

For the hover animation I like ease-linear or ease-in:
ease-linear | transition-timing-function: linear;
-- | --
ease-in | transition-timing-function: cubic-bezier(0.4, 0, 1, 1);

**Comment by Ahsaask** [comment]
Hi @AlinaU1 

I am sharing the updated responsive cards, though I had to slightly change the breakpoints and the spacing to cover all the ranges. In some of the screen sizes it was breaking the styling (not sure why) so I tried to fix for each range. I tried to be as close as to your designs and styling. Let me know your thoughts. 

1) Gaps between cards-
Mobile: 24px
Ipad: 26px
Laptop: 32px 

2) Gap between Page heading and cards: 32px (Just saw your comment, I will change it 80px right now)

3) Margins on left and right to the cards are set to auto. 

4) Changed the transition to `ease-in`

Thanks!

![Image](https://github.com/user-attachments/assets/1fda4a21-f525-4fcc-a645-09229b837119)

![Image](https://github.com/user-attachments/assets/eaa09cc9-7386-49bd-bf26-7a28545858f7)

![Image](https://github.com/user-attachments/assets/3f2d82e4-eba3-448b-8987-12930df7419a)

![Image](https://github.com/user-attachments/assets/bc71fd63-4cd7-4897-80e9-35b8533feb7a)

![Image](https://github.com/user-attachments/assets/d9662008-95a1-4657-b439-3829a0cfd99f)

**Comment by Ahsaask** [comment]
Hi  @AlinaU1 , as per our discussion I implemented dynamic responsiveness to the cards. The margin remains same between the breakpoint range while the card size changes dynamically. 

Screen Size > 1536 (2xl)
- Margin left/right: `66px`
- Height: `446px`
- Width: `dynamic`
- H1: `36px`
- P: `18px`
- line-height: `48px`
- gap: `32px`

Screen Size > 1280 (xl)
- Margin left/right: `48px`
- Height: `390px`
- Width: `dynamic`
- H1: `32px`
- P: `16px`
- line-height: `48px`
-  gap: `32px`

Screen Size > 1024 (lg)
- Margin left/right: `32px`
- Height: `390px`
- Width: `dynamic`
- H1: `28px`
- P: `16px`
- line-height: `44px`
- gap: `24px`

Screen Size > 768 (md)
- Margin left/right: `24px`
- Height: `442px`
- Width: `dynamic`
- H1: `32px`
- P: `14px`
- line-height: `48px`
- gap: `24px`

Screen Size > 640 (sm)
- Margin left/right: `24px`
- Height: `406px`
- Width: `dynamic`
- H1: `32px`
- P: `16px`
- line-height: `48px`
- gap: `24px`

Screen Size > 390 
- Margin left/right: `22px`
- Height: `390px`
- Width: `dynamic`
- H1: `32px`
- P: `14px`
- line-height: `44px`
- gap: `24px`

![Image](https://github.com/user-attachments/assets/5656a0b3-1105-493e-b291-a5ab0c94352b)

**Comment by AlinaU1** [comment]
Looks amazing!

**Comment by chadcrotchett** [comment]
BLOCKED: Unable to get QA environment working with new code. Pending investigation by Dave and Remi.

**Comment by Ahsaask** [comment]
I noticed that the Tailwind styles aren't being applied in the QA environment, while the standard CSS works as expected. Do you think this could be related to a Tailwind configuration issue in the QA, or should I look into it from my side? @dbradham 

QA
![Image](https://github.com/user-attachments/assets/58089378-3fe6-43e3-8f4e-d8dbaf7c5e74)

Local
![Image](https://github.com/user-attachments/assets/91829182-bce0-4767-a072-e3ba747455a3)
