### ISSUE TITLE
Draft a plan to guide members to implement SMART goals

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/dev-launchers-platform#2130]
https://www.atlassian.com/blog/productivity/how-to-write-smart-goals explains what are SMART goals. By helping members define their SMART goals, it helps them come up with achievable goals.

**Comment by KiyanDL** [comment]
https://docs.google.com/document/d/1SssHSae-g1qX4K0MU_QG7PtmwsrFMf2CAot1Rw0Benw/edit?usp=drive_link

**Comment by KiyanDL** [comment]
SMART Goals: https://docs.google.com/document/d/1RKrDwRoKOVAGagwYyE2k3dlLGUemomqPFpu1rUHmeWI/edit?usp=drive_link
