### ISSUE TITLE
[Task] Rearchitect codebase to organize components further

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#637]

**Comment by JulieMass** [comment]
@pyxld-kris I guess this task can also be closed?

**Comment by JulieMass** [comment]
@pyxld-kris well you put it difficult for me here 🤣. How do I check this is done? LOL 🤣🤣🤣 I guess it is mmmmmm...done. I trust you?! 🤣

**Comment by JulieMass** [comment]
@pyxld-kris can you please help me leaving an estimation for this task?
