### ISSUE TITLE
[Bug] Long comments not able to posted in workshopping page

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#640]
When trying to submit a very long comment under “What are your thoughts?” nothing was happening. The user is left without any feedback on why his/her comment isn’t being submitted. 

Browsers where this issue happened: Chrome, Opera. 
Systems: MacOS, Windows.

**Considerations**
Based on the team's decision the following rules apply to comments:
- Min. 25 characters per comment
- Max. 215 characters per comment

![image](https://user-images.githubusercontent.com/104226366/195913019-36fe7482-fe4b-49e0-93c9-affa4032442e.png)

------------------------------------------------------

**Comment by JulieMass** [comment]
@RETprojects Remi, are you or were you working on this by any chance? The reason I ask is because I see it assigned to you but it might be that when we did the automatic sync from our Idea-platform Github to devlauncher-platform github some issues might have moved with mistakes. And if it was assigned to you what is the state of this? in progress? done? I am currently cleaning up all the issues moved =). Let me know please and thank you!

**Comment by RETprojects** [comment]
@JulieMass Hi Julie, I have been working on this issue. It is still in progress; I'm not sure if my changes are fixing the bug on the mentioned browsers. Thanks!

**Comment by JulieMass** [comment]
@RETprojects thanks for taking this task Remi. That is awesome! I'll move it to "in progress" then. Thanks 🙏!

**Comment by JulieMass** [comment]
Hi @RETprojects same with this one please, can add an estimation?
