### ISSUE TITLE
Develop the "key moments" where the user feedback form would appear for our target audience (with local storage)

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#647]
Description:

1. **Miles** lands in IdeaSpace home page: [https://idea.devlaunchers.com](https://devlaunchers.org/ideas) 
2. A modal window should appear after the user clicks / taps on the floating button
5. If Miles clicks in the CTA button he should be redirected to our google form (https://docs.google.com/forms/d/e/1FAIpQLSdkipdKLxq4dGQf3dX5Sdfb_XNoPhhGsNxPXNcNNSMzhIrYxg/viewform )
6. If Miles clicks in the close “X” button, the modal should fade out and close:
7. Two ideas here to help Miles realize that he can provide us feedback at any time he prefers:

- Idea 1: the modal fades out in the direction of the “user feedback” button
- Idea 2: Or once the modal closes the “user feedback” button does something (animation? Slight glow?)

10. User feedback button should be visible at all or our IdeaSpace pages. 

Please visit Figma "[IdeaSpace (Copy)](https://docs.google.com/presentation/d/1vArOMxJ4eL75dg4RP55I-uiMJq67meg9afOzmH0jHOA/edit?usp=sharing)" to access designs.

-------------------------------
Team's decisions in weekly meetings of 10 / 14 /22 + 10/28/2022 + 11/04/2022 : 

User feedback form should appear:
- Modal should appear open by default.
- If the user closes it, the modal closes but the floating bubble stays.
- The floating bubble stays visible all the time.
- Animation: team prefers the “slide to the side” animation.
- Add a stroke to the alternate white button to improve accessibility and raise this to the mono repo team.

-------------------------------

**Comment by JulieMass** [comment]
@pyxld-kris I assigned this issue in "Review/QA"  to you because I assumed you are who should review it but I'm not sure. Let me know please if otherwise 🙏.

**Comment by JulieMass** [comment]
@Nouri-Anouar  After what we discussed in today's weekly meeting, I moved this task to the "work in progress" column so we can finish working on it. I also added what was defined in today's meeting in the description. Let me know if I missed anything please 🙌! 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/4132cd04-ecef-4be2-8155-110e9158abe3)

**Comment by dbradham** [comment]
@Nouri-Anouar Hey Anwar, this ticket is older than my time... can it be moved to another lane or does it still require some review & QA?

**Comment by JulieMass** [comment]
> @Nouri-Anouar Hey Anwar, this ticket is older than my time... can it be moved to another lane or does it still require some review & QA?

(CC. @dbradham)

@Nouri-Anouar I moved this task back to "Review/QA" because, is it possible the bubble seems to still be going away after the user closes the feedback window? 

![image](https://user-images.githubusercontent.com/104226366/213956655-ce056aef-4c37-48d8-a141-e05cbe19c185.png)

**Comment by Nouri-Anouar** [comment]
Hey @JulieMass I updated the modal bubble to remain visible but that was after the last release, that is why it has the old behavior.

**Comment by Nouri-Anouar** [comment]
@JulieMass  You mean this one?
![image](https://user-images.githubusercontent.com/79311912/214662168-1cefc346-2bc6-4532-9532-624603ce15e6.png)

**Comment by JulieMass** [comment]
> Hey @JulieMass I updated the modal bubble to remain visible but that was after the last release, that is why it has the old behavior.

Thank you Anwar!
