### ISSUE TITLE
[US - UXD] As MILES HARDIN,  I want to see where my idea stands in the roadmap because I want to know its current state

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#650]
### **Considerations:**
We need to review the different states the ideas can go through, analyze how the system can work on the back with this so people don’t have to do this manually and update the roadmap designs from the workshopping page according to these definitions.

Some questions to review:
- What happens when the idea project is finished? Should we show the “close” state?
- how can the system know that the idea is moving from one state to the other? Recommendation: we should try to make this automatically by the system (not by humans).

### **Acceptance criteria:**
- Idea’s states and how the system will work automatically to update the idea’s status is defined
- New visual design (hi-fi mockups) are designed for the roadmap in the workshopping page.
- Mockups are web responsive and include mobile, tablet and desktop breakpoints.
- Designs include considerations for lots of comment scenarios.

----------------------------------------------------

### **Sub-tasks:**
- [ ] UX design (update hifi mockups)
- [ ] QA

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/650?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @pyxld-kris @RETprojects

**Comment by Enjoy2Live** [comment]
@JulieMass this seems like a good one for the library we're working on, keep us @dev-launchers/platform-enablement on the development of this.

**Comment by JulieMass** [comment]
> @JulieMass this seems like a good component for the library we're working on, keep the @dev-launchers/platform-enablement updated on the development of this.

+ @dbradham

**Comment by JulieMass** [comment]
Same with this one @Nouri-Anouar. No need to include a screenshot. I can see this easily in the "latest designs" page. Thanks again for cleaning up the figma file 🙏
