### ISSUE TITLE
[UXR] Figure out Google Analytics for our page

### ISSUE THREAD

**Issue by han1ya** [dev-launchers/dev-launchers-platform#661]
Main Questions:
-how do we increase traffic to our site?
-what do users seem to like/dislike? What page do they spend the most time on,etc.
-What should we change? 

-------------------------------------------------------------------------------
Outcome:

[[DL - Idea platform] -  Success metrics](https://docs.google.com/spreadsheets/d/1ulsX6jQ__OoXBbONKxZTT53gFNZPUzQcpi7jBpq2G0Y/edit?usp=sharing)

**Comment by JulieMass** [comment]
Worked on the followings:

- Google tag manager (GTM) + Google analytics 4 tags created and tracking.
- Created 2 explore reports for IdeaSpace ( idea creation funnel and idea workshopping funnel) and 1 for DL.org (Path explorations)
- Created events to track for IdeaSpace: 
 - ideaspace_idea_submitted
 - ideaspace_new_comment
 - ideaspace_login
