### ISSUE TITLE
[US - DEV] As MILES HARDIN, I want to navigate IdeaSpace from Dev Launchers global navigation because  I want to find the information I am looking for.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#665]
### **Considerations:**
IdeaSpace is now embedded in Dev Launchers website so after research the team designed a new global navigation solution. We also developed an idea's dashboard for Miles so we need to include an access to this page from the user profile's navigation.

Please refer to UX designs in [Figma ](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1) 

### ⚠️IMPORTANT: 
Assignee/s of this task will be working together with the **platform enablement team** developing the top nav component so we can work on this jointly. This is their [component task in Zenhub](https://app.zenhub.com/workspaces/platform-enablement-63529f02029ee50018fe58c6/issues/dev-launchers/dev-launchers-platform/677).

----------------------------------------------------------------------------------

### **Acceptance criteria:**
- Top navigation menu component is developed following [DL styleguide](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1055%3A1098&t=f4FaGK1cl2k9RXV1-1). 
- When Miles clicks on "Dream" from Dev Launcher's top navigation a dropdown menu appears with IdeaSpace categories. 
- Selected top nav links are underlined when clicked to show Miles in which page he currently is. _(please review our [DL styleguide](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1055%3A1098&t=6W2KUzht9NkWw2UU-1) for the different Nav link styles)_
- If Miles is signed up he can access his idea’s dashboard from the dropdown menu that appears when clicking in his user profile’s picture.
- User profile drop down menu is implemented following IdeaSpace's ux mockups (please check #658). 
- All top nav menues are web responsive.

----------------------------------------------------------------------------------

### **Sub-tasks:**
- [X] UXR (Card sorting study)
- [X] UX design 
- [x] Development
- [ ] QA

----------------------------------------------------------------------------------

**Top nav menu:**
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/14c19aad-df70-43a0-b5d8-837db2b75b4b)

**User profile menu** --> please check UX designs from #658 made by Anwar.

For the different top nav menu link states please review our [DL styleguide](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1055%3A1098&t=6W2KUzht9NkWw2UU-1) in the "Organisms" page:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/1f4a31ec-0bf0-410f-8c33-7e0cab2d090d)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/665?planning-poker) with Zenhub @alicefate @Nouri-Anouar @pyxld-kris @RETprojects

**Comment by JulieMass** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/665?planning-poker) with Zenhub @JulieMass

**Comment by JulieMass** [comment]
Hi @Nouri-Anouar to consider it closed, can you please update the top nav categories to follow Dev launcher's website please? our UX design mockups don't match with the website. 

website:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/99ba99ef-4a80-4f45-ba8d-a6167a592f1f)

our ux design mockups:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/643ee6f2-6820-4d5d-8ef5-0bab78baa879)

**Comment by JulieMass** [comment]
(CC. @dbradham)

Hey @Nouri-Anouar Can you help me out please? So for a bit of context, if you go and check our production top nav we currently don't have either the IdeaSpace dropdown nor the user profile dropdown. 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/04f3a40d-4fc7-4e28-a9eb-37544f863723)

But the scope for this ticket was to develop both dropdowns as it is mentioned in the acceptance criteria: the ideaSpace dropdown (the one that should appear when a user clicks in "Dream") and the user profile dropdown.

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/4b9271ff-77f1-49e3-aaa1-4e39dc4b2a98)

Any idea why we don’t see this developed in production? We also couldn’t find the user profile designs in the Figma file with Dave. 

I’m super lost here 😔

**Comment by Nouri-Anouar** [comment]
@JulieMass my apologies, for some reason I forgot to mention this topic last meeting. 
There are some pending PRs (ex: nav links) that need to be merged so I can use that for the navigation dropdowns.
That being said, once everything is merged, I will be working on all these navigation updates in one PR.

User profile design? Do you mean [This one](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3954%3A10145&t=fDbOjU42g74sHNuK-4)?

**Comment by Nouri-Anouar** [comment]
I might work on this ticket this sprint if the pending PR are merged.
It should be simple since I already build the dropdowns and all I need is to use nav links and sub-nav links components.

**Comment by JulieMass** [comment]
Hey @Nouri-Anouar and @dbradham I'm going to move this ticket to our Icebox so it doesn’t impact our team velocity since the Universal design team is working on the design now. Once we have the designs for the UD team we can check with @Enjoy2Live  who has availability to continue the development of this ticket.

**Comment by JulieMass** [comment]
(CC. @dbradham and @Nouri-Anouar )

We're closing this ticket that was blocked because Mohammed developed a temporary solution to access IdeaSpace and our dashboard. Thanks again, @Enjoy2Live , for your help with this feature!
