### ISSUE TITLE
[US] As MILES HARDIN, I want to click call to actions from the home page that can lead me to  the “submit my idea” page, “projects” page or “generate an idea”page.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#666]
**Sub-tasks:**
- [x] UX design [already done by Anwar]
- [x] Development

-----------------------

**Description:**
- We need to implement the new "Dev Ideas Main page" visual design and develop the new “Generate an idea” call to action (CTA) button.
- Remove "generate an idea" button from the top (old button)

Please refer to UX designs in [Figma ](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1)

_**Note:** This user story won't include making the layout web responsive. We'll be working on this in a separate task._ 

**Acceptance criteria:**
- New "Main page" visual design is implemented.
- Cards are clickable as a whole (not only the text of “continue→”)
- Page title keeps the "Dev Ideas (Beta)" to allow users know we are in Beta for the moment. 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/56a171ef-8d5a-439b-8ad9-f3ce8b5546fc)

**Comment by JulieMass** [comment]
Hi @jordanmcousins 'm moving this task to WIP column since I saw yesterday you started it and it is looking amazing 🤩!

**Comment by JulieMass** [comment]
CC. @dbradham, @pyxld-kris 

Done @jordanmcousins 😀👍!  I removed making the main page responsive in the acceptance criteria here and I created a new enhancement task so we can work on this later (#761). 

Let me know if I missed anything please 🙏

**Comment by dbradham** [comment]
Can we move this to done? @JulieMass

**Comment by JulieMass** [comment]
Yes, Looks good to me! I checked it in staging and production and all acceptance criteria is checked and it follows the design. We can close the ticket if you are OK with it as well. 

@jordanmcousins have I mentioned how AWEEESOOOMEEE the landing page looks? Every time I go to IdeaSpace and I see it I can't stop thinking what a great turn around compared to our previous black and white version. It is so colorful and you respected so much the designs. You did an amazing work here Jordan! 👏👏
