### ISSUE TITLE
[Design enhancement] Drop down allowing people select if they want to be the idea leader or not

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#667]
### Problem:
- What if Miles doesn’t want to be the idea leader? 

**Possible solution:** 
We should include a drop down in the idea form to allow people to express if they want to be the idea leader or if they just want to work on it (design/develop only).

### Tasks:
 - [x] (liwenlin664477) Add new form element to frontend, and handle state management and http request changes
 - [ ] (pyxld-kris) Change backend to allow new data type

**Comment by liwenlin664477** [comment]
I am going to take this

**Comment by JulieMass** [comment]
@liwenlin664477 👍 Awesome, thank you Will 🙏! I moved it to the sprint backlog column. All yours!

**Comment by liwenlin664477** [comment]
I finished my portion.

**Comment by JulieMass** [comment]
@pyxld-kris After what we discussed on Monday of temporary not having this drop down due to complexity, can we considered this issue closed? or does it still need some work?

Also @liwenlin664477 or @pyxld-kris please can one of you estimate it so Zenhub starts tracking the velocity 🙏?

**Comment by JulieMass** [comment]
Hi @pyxld-kris after what we discussed in yesteday's meeting, I'm closing this issue as done.

**Comment by JulieMass** [comment]
> @pyxld-kris After what we discussed on Monday of temporary not having this drop down due to complexity, can we considered this issue closed? or does it still need some work?
> 
> Also @liwenlin664477 or @pyxld-kris please can one of you estimate it so Zenhub starts tracking the velocity 🙏?

Hi @pyxld-kris and @liwenlin664477 this task from our previous sprint was automatically moved from "in progress" to "done" column by Zenhub too 😅. Can we close it? or are we still working on it? please let me know.
