### ISSUE TITLE
Impelement Tooltip [Molecule]

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#671]
The tooltip molecule is a short message that appears when a user interacts with a specific element on a website or in a mobile app.

The component accepts following prop:
- icon => the icon that when a user hover on the tool-tip shows up
- text => the text that the tool-tip will contain

### Where the component should live
The component is an Molecule so it should live in the [Molecule Folder](https://github.com/dev-launchers/dev-launchers-platform/tree/master/packages/UI/src)

### References
The component design can be found in this link
https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=394%3A1343
![image.png](https://images.zenhubusercontent.com/624acdda3bd4ed8698fc4168/e1a4b642-4ec4-4737-bdbd-a1ae5bfbee77)

### About the system we follow
We're building the component library using the [atomic design methodology](https://atomicdesign.bradfrost.com/chapter-2/#:~:text=Atomic%20design%20is%20atoms%2C%20molecules,parts%20at%20the%20same%20time.)

**Comment by adrianrojek** [comment]
Hey, I would like to help with this issue. Can you assign it to me ?

**Comment by Enjoy2Live** [comment]
hey @adrianrojek , unfortunately this was already taken by another member but I'd love to assign you to another issue if you find anything interesting!

it's a little bit hard to notice comments on Github so feel free to message me on either
Discord: Enjoy2Live#5094
Email: mohammedmaqbol@devlaunchers.com
