### ISSUE TITLE
Implement Search Bar [Molecule]

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/dev-launchers-platform#672]
The search bar molecule would help users to seamlessly find the content they're looking for within the app.

The component accepts following props:
- icon => The icon on the left of the search field
- placeholder => the placeholder text that shows when the search bar is empty
- onChange => a function passed to the component that retrieves the searched content

### Where the component should live
The component is an Molecule so it should live in the [Molecule Folder](https://github.com/dev-launchers/dev-launchers-platform/tree/master/packages/UI/src)

### References
The component design can be found in this link
https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=387%3A1628
![image.png](https://images.zenhubusercontent.com/624acdda3bd4ed8698fc4168/1cbe5d9b-7d3b-427d-bde7-7daaf76f602e)

### About the system we follow
We're building the component library using the [atomic design methodology](https://atomicdesign.bradfrost.com/chapter-2/#:~:text=Atomic%20design%20is%20atoms%2C%20molecules,parts%20at%20the%20same%20time.)

**Comment by adrianrojek** [comment]
Hey, I would like to help with this issue. Can you assign it to me ?
