### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to see my information on a board in the workshopping page so that people can recognize me as the creator of the idea.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#702]
**Considerations:**
We’ll update the content and the visual design of the idea creator board in the workshopping page.

QUESTION FOR THE TEAM:
- Email visibility:
Should we include a question on the form allowing people to consent if they want to share their email publicly or not? 
- What would be the best role? idea’s owner? idea’s creator? 

-----------------------------------------------

**Acceptance criteria:**
- A new visual design (UX mockups) are designed for the board in the workshopping page.
- Idea's owner board includes:
   - "Username" of who submitted the idea
   - a "Role" or a description (for example: Idea owner", "idea creator", "idea submitted by", etc.)
   - The user profile photo of the creator of the idea.
- The idea creator's board is web responsive (desktop, mobile and tablets).
- If Mile’s Hardin is the idea creator of this idea, the picture in the board is the same he uploaded in his Dev Launcher’s account page. 

-----------------------------------------------

**Sub-tasks:**
- [ ] UX design

-----------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/2d59bc38-dc33-44e3-8385-44d4916a5699)

**Comment by JulieMass** [comment]
Hey @Nouri-Anouar I was reviewing our backlog to see what tasks can be closed and I noticed this one is in our Review/QA column without an estimation and it was also without a sprint. So couple of questions: can you please estimate it? and also, can we consider it done and close it? Let me know please. Thank you!

**Comment by Nouri-Anouar** [comment]
Yes @JulieMass.
I've just estimated it and we can also close it.

**Comment by JulieMass** [comment]
Thank you @Nouri-Anouar
