### ISSUE TITLE
[US - DEV] As MILES HARDIN,  I want to access my idea workshopping page I just submitted from the form because I want to start workshopping with other people.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#703]
### **Considerations:**
We’ll be updating the visual design layout on the workshopping page and fixing content inconsistencies between the form and the workshopping page.

This item task _doesn’t include_ the following:
- idea picture
- Implementing cards (this will be taken in another item #787)
- Product owner board
- Tags
- word cloud.
- Comment feed.
- Idea roadmap
- Actions: Edit, delete, share or transfer an idea.

Please refer to UX mockups for **“Dev Idea Workshopping Page”** in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=5fHSxtzyVh1IzGWL-1)

----------------------------------

### **Acceptance criteria:**
- New visual design is implemented to the workshopping page for the following elements:
 - A page title + subtitle
 - The idea name + tagline card
 - Description area (without implementing the cards. just adding new styles to the current content)
- The workshopping page includes a "back" button that takes Miles back to the ideas page (https://devlaunchers.org/ideas/browse)
- Workshopping page is web responsive (desktop, mobile and tablets).

--------------------------------------------------------------------
### **Sub-tasks:**
- [x] UX design
- [x] Development
- [ ] QA

--------------------------------------------------------------------

For reference: Screenshot with current content inconsistencies in between idea submission form and idea workshopping pages.
![idea form and workshopping content.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/eb6b8b54-bedd-4935-a3d2-11552d958da2)

Elements included in this US:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/d053dfb8-6619-4d58-b203-9828ce9d236a)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/703?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @pyxld-kris @RETprojects

**Comment by dbradham** [comment]
When we pick up this ticket, the developer should have a quick call with platform enablement team to ensure the cards are being built in a way which is reusable for that team.
