### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to leave a new comment or reply to other people’s comments so that I can workshop my idea with other people

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#704]
### **Considerations:**
Mile Hardin should be able to add a new comment or reply to another person’s comment in the comment feed from the workshopping page.

NOTE:
We need to define: 
- what happens if we have a lot of comments? will we have a scroll or a pagination?
- how will we display replies? aligned to the right? 

-----------------------------------------------

### **Acceptance criteria:**
- New visual design (hi-fi mockups) are designed for the reply and edit comments user flow.
- Mockups are web responsive and include mobile, tablet and desktop breakpoints.
- Comments should be ordered by most recent.
- Designs include considerations for lots of comments scenario. 

----------------------------------------------------
### **Sub-tasks:**
- [ ] UX design: Hi-fi mockups updates

----------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/026bae75-5bc0-4ce9-846e-8c6ef16a5c7a)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/e54f9e9b-38ea-4480-a7e8-a9571bd027d5)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/4244223a-f40d-484b-87c0-191428689a37)

**Comment by JulieMass** [comment]
For inspiration --> from [smashing magazine](https://www.smashingmagazine.com/)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/ff331203-ad72-4505-8c5b-c493ce556e7f)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/704?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @pyxld-kris @RETprojects

**Comment by Enjoy2Live** [comment]
seems like a component for the library we're working on, keep the @dev-launchers/platform-enablement updated on the development of this.

**Comment by JulieMass** [comment]
> seems like a component for the library we're working on, keep the @dev-launchers/platform-enablement updated on the development of this.

+ plus @dbradham 

We'll do. Thanks @Enjoy2Live for the heads up 🙌
