### ISSUE TITLE
[ENHANCEMENT - DEV] Update design layout and content of idea submission page

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#732]
**Considerations:**
Implementation of new UX visual designs and content updates on the idea submission page.

Please refer to UX designs in [Figma ](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1) 

----------------------------------------------------------------------------

**Acceptance criteria:**
- New visual design is implemented.
- Idea submission page follows the content and elements included in the mockups.
- Layout is web responsive.
- People can fill in the form and once submitted (with all mandatory fields completed) the form leads to the corresponding workshopping page.

----------------------------------------------------------------------------

**Sub-tasks:**
- [x] UX design
- [x] Development
- [x] QA

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/389ebe82-885d-4bb7-8a3a-b33cc6edefd3)

**Comment by JulieMass** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/732?planning-poker) with Zenhub @pyxld-kris

**Comment by alicefate** [comment]
@JulieMass Are these questions what we want for now?  (It delete beLeader question.) 
@Nouri-Anouar The last three are not in other screen size UX. Are they wanted or need to be deleted?
![form](https://user-images.githubusercontent.com/33647003/206019348-a0e17f7f-3a3e-4d55-8ec6-232ed1a8d1fc.JPG)

Some questions and placeholder use "idea", others use "product". Should they be unanimous?

Also, I think we need new login UX to match the theme. Currently, it looks like this.
![signIn](https://user-images.githubusercontent.com/33647003/206020452-565128ac-b261-4fbe-bb20-86685c5d0aff.JPG)

**Comment by Nouri-Anouar** [comment]
Hey @alicefate 
1. _**The last three are not in other screen size UX. Are they wanted or need to be deleted?**_
I updated the designs and all the breakpoints have the same fields now.
2. _**Some questions and placeholder use "idea", others use "product". Should they be unanimous?**_
That is good point, I will review this with Julie.
3.  **_Is back button be needed?_**
Yes I believe this was our conclusion from the meeting with you and Julie.
4. _**Also, I think we need new login UX to match the theme**_
I agree with you, we don't have a design for now but I was planning to make one, I will let you know when it is ready.

**Comment by JulieMass** [comment]
Hi @alicefate,

_Re: Are these questions what we want for now? (It delete beLeader question.)_

Yes, those are the questions but please check @Nouri-Anouar's latest mockups because he updated the information on the submission form mockups in Figma. For example: instead of "why do you think this idea..." it now changed to "who do you think your idea is helpful....", the placeholder information there is also different now: describe your audience, including demographic information....", etc.

_Finally in respect to the login UX design:_ yes, I agree the design is using an old DL design style but we will take all login design enhancements in future sprints. Anwar needs to take some time to review all the login user flows and update those designs so they aren't ready yet for development.

**Comment by alicefate** [comment]
Hi @Nouri-Anouar,
Thank you for replying, it helps a lot. There are two follow up:

1. Is only the first two questions are required? (the smallest UX has more requred question)
2. Is the back button should on all size, or only the largest two?

**Comment by Nouri-Anouar** [comment]
Hello @alicefate, Thank you. I appreciate your attention to details
1. the first two fields should be required for all screen sizes. Do you agree @JulieMass?
2. the back button should be on all screen sizes as well. I just updated the UX designs.
The back button is supposed to be a shared component that you can import and use out of the box, I will let you know when it is finished.

**Comment by JulieMass** [comment]
All good questions @alicefate and @Nouri-Anouar  

I’ve checked submission forms in similar products like IdeaSpace because I wanted to see how much information they were asking for as required and I'm thinking we should also make required the two followings: _“Do you have any relevant experience...etc.",_ and _“what features…?”_.

I was in doubt of adding the "who do you think...?" as required. As a UX researcher I will always say that thinking about the audience is super important 😅 but at the same time I don't want to make everything required to make the first step easier to our audience. Maybe for now we can leave it as optional and check later what happens when we run usability testings and gather feedback from people using our product. Same with the workings where we use sometimes "idea" and other times "products". I also agree we will need to review this in the future. What do you think?

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/cdfa8aae-9f48-44dc-aaf2-a0afeea298ee)

Finally @Nouri-Anouar I just noticed we are asking about who is the audience in the placeholder of "what is your idea...?. I think this is coming from our old designs when we didn't have the "who do you think?" question and we should remove it there now, right? 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/bdaa5616-030f-4f24-9e68-fdae8bf343f7)

**Comment by alicefate** [comment]
@Nouri-Anouar Got it, thank you. 
Kris suggest me to use storybook component. The button in storybook has shadow, but UX one don't. Which design should I follow?

@JulieMass 
I agree that "experience" and "features" should be required. I'm not familiar with the features, is that means functions? 
And I think there should be a question for "why"? (ex. why do you want to do this?) It is easy for Miles to answer than the "audience" one. He can answer "I think it is cool." or "I need a program to track all my mails." or "It will help disable people".

**Comment by Nouri-Anouar** [comment]
@alicefate 

Which button are you talking about:
this one?
![image](https://user-images.githubusercontent.com/79311912/206664874-fe1199d4-b0cd-4142-b65e-db5ccec91c5e.png)
or this one?
![image](https://user-images.githubusercontent.com/79311912/206665396-9c93a126-681f-4ec8-ad8f-b6bebd29f495.png)
But anyway you can use these components and the shadow issue will be fixed once we merge PR #754 .

Additonally you can find the `textarea` component under `Organisms`, it is called `OpenResponse`

**Comment by JulieMass** [comment]
Hi  @alicefate replying inline below:

**1. I'm not familiar with the features, is that means functions?** 
Features would be a list of characteristics of a software and functional capabilities available to the user. 

Some people might write this as a list of characteristics the software include for example the list I wrote for the kudification idea:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/57a0ddc3-2405-4e57-9177-d0add47de7e2)

Some others might write this as a list of user stories like Kris did in this idea: https://devlaunchers.org/ideas/workshop/25 
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/cf026449-3d5b-4636-a25a-78226381ce7c)


**2. And I think there should be a question for "why"? (ex. why do you want to do this?) It is easy for Miles to answer than the "audience" one. He can answer "I think it is cool." or "I need a program to track all my mails." or "It will help disable people".**
Yes, I understand your reasoning. We decided with Anwar to change the question from “Why” to “who” after observing the results of a previous usability testing in which a participant mentioned “who” and “why” were two questions that felt the same and were probably going to melt together as one question. So she suggested it might be more useful if we ask “who is this idea for?” instead of why. 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/ad5e8bdb-73ad-404c-a716-efefaa1baee1)

We know one participant is a too small sample but since we plan with Anwar to run a new session of usability testing in our next sprint we might learn more about how people’s experience really is using IdeaSpace 🕵️

I hope this helps!

**Comment by JulieMass** [comment]
> > @JulieMass Are these questions what we want for now? (It delete beLeader question.)
> > @Nouri-Anouar
> > 
> > 1. The last three are not in other screen size UX. Are they wanted or need to be deleted?
> >    ![form](https://user-images.githubusercontent.com/33647003/206019348-a0e17f7f-3a3e-4d55-8ec6-232ed1a8d1fc.JPG)
> > 2. Some questions and placeholder use "idea", others use "product". Should they be unanimous?
> > 3. Is back button be needed?
> > 4. Also, I think we need new login UX to match the theme. Currently, it looks like this.
> >    ![signIn](https://user-images.githubusercontent.com/33647003/206020452-565128ac-b261-4fbe-bb20-86685c5d0aff.JPG)
> 
> to me this form looks very similar to the one we're creating at the recruitment app, I think for us to reduce the complexity for us as developers and from UX point of view using the same form is better.
> 
> ![image](https://user-images.githubusercontent.com/27841994/206918475-5d0e81cb-6677-4fdb-ac15-14d264318a7e.png)
> 
> thoughts? @pyxld-kris @Nouri-Anouar @JulieMass @alicefate
----------
Hi @Enjoy2Live we were thinking of discussing this today in the coworking session but we didn't have enought time. It would have been the perfect place since we were all there 😔

Anyway, what we talked with @alicefate and @pyxld-kris while you and @Nouri-Anouar were in the 1-1 discord channel, was that we agree, if we are using the same components we should see ways to reduce duplicated efforts. Any suggestion on how we can do this? 

P.S. by the way, I just learned thanks to your message here that we an do a "quote reply"  in Github 😂😂😂

**Comment by JulieMass** [comment]
> All good questions @alicefate and @Nouri-Anouar
> 
> I’ve checked submission forms in similar products like IdeaSpace because I wanted to see how much information they were asking for as required and I'm thinking we should also make required the two followings: _“Do you have any relevant experience...etc.",_ and _“what features…?”_.
> 
> I was in doubt of adding the "who do you think...?" as required. As a UX researcher I will always say that thinking about the audience is super important 😅 but at the same time I don't want to make everything required to make the first step easier to our audience. Maybe for now we can leave it as optional and check later what happens when we run usability testings and gather feedback from people using our product. Same with the wordings where we use sometimes "idea" and other times "products". I also agree we will need to review this in the future. What do you think?
> 
> ![image.png](https://camo.githubusercontent.com/6d0cbe9324b87c4185be9da050e54e72217c8ca05a76fea95375d64232698ea3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3633343030663364316537393631346534356439656264392f63646661386161652d396634382d343464632d616166322d613061666565613239386565)
------------------------------------------------
(CC. @alicefate)

Hi @Nouri-Anouar, do you agree on making these two questions required: _“Do you have any relevant experience..."_, and _“what features…”?_ and leave _"who do you think this idea is for?"_ as optional? What are your thoughts on this?

**Comment by dbradham** [comment]
I am closing this issue @JulieMass

**Comment by JulieMass** [comment]
> > All good questions @alicefate and @Nouri-Anouar
> > I’ve checked submission forms in similar products like IdeaSpace because I wanted to see how much information they were asking for as required and I'm thinking we should also make required the two followings: _“Do you have any relevant experience...etc.",_ and _“what features…?”_.
> > I was in doubt of adding the "who do you think...?" as required. As a UX researcher I will always say that thinking about the audience is super important 😅 but at the same time I don't want to make everything required to make the first step easier to our audience. Maybe for now we can leave it as optional and check later what happens when we run usability testings and gather feedback from people using our product. Same with the wordings where we use sometimes "idea" and other times "products". I also agree we will need to review this in the future. What do you think?
> > ![image.png](https://camo.githubusercontent.com/6d0cbe9324b87c4185be9da050e54e72217c8ca05a76fea95375d64232698ea3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3633343030663364316537393631346534356439656264392f63646661386161652d396634382d343464632d616166322d613061666565613239386565)
> 
> (CC. @alicefate)
> 
> Hi @Nouri-Anouar, do you agree on making these two questions required: _“Do you have any relevant experience..."_, and _“what features…”?_ and leave _"who do you think this idea is for?"_ as optional? What are your thoughts on this?

Hey @Nouri-Anouar we never received a reply on the above questions so now the designs doesn't match what Iris developed 😔. If you agree with it, can we please update the designs so we know that what Iris developed is OK? Otherwise, can yo please let us know if Iris needs to make a change on what she developed? Because in order to close tickets we check the acceptance criteria and what is developed is aligned with your designs and if they don't match we can't consider them closed. 

On the other hand, @alicefate we were including the subtitle "idea info" with the underline in ticket #735, correct? Can we also include the title update of the "Submit and Idea" title as well in that ticket? would that be possible please? 

![image](https://user-images.githubusercontent.com/104226366/225295042-c8963158-fbdd-434e-a821-5877e5fe3055.png)

![image](https://user-images.githubusercontent.com/104226366/225294290-cc78f777-aee2-4b1e-afc9-fd34a4e0eaa7.png)

Thank you both!

**Comment by alicefate** [comment]
@JulieMass It has been fixed in latest pr which been merged yesterday.

**Comment by JulieMass** [comment]
> @JulieMass It has been fixed in latest pr which been merged yesterday.

wohooo! that is excellent! always a step ahead Iris! thank you so much! 😀

**Comment by Nouri-Anouar** [comment]
@JulieMass  After checking the staging environment I can see that it matches our designs expect for the "commitment dropdown" and "tooltip".
I suggest that we close this ticket and another one to fix these small details.

![screencapture-staging-devlaunchers-org-ideaspace-submit-2023-03-22-09_16_31](https://user-images.githubusercontent.com/79311912/226856256-0a5b80eb-6190-4893-988e-53dc42ce3078.png)

@alicefate great work!

**Comment by JulieMass** [comment]
Hey @Nouri-Anouar thanks for the reply! What I meant was my question above related to the mandatory fields. If you check what it was developed vs. our mockups they aren't aligned.

**Comment by JulieMass** [comment]
Yay 😀! Thank so much Anwar for updating the designs and helping us unblock this ticket!

**Question: Should "Level of Involvement" be required?**--> Yes it should be required even though it isn't included as part of the scope of this ticket since we want to gather feedback from our testings. 

Also a friendly reminder: the **terms and conditions checkbox** should have an asterisk (*) in our designs too 🙂. 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/040f67b5-8599-446e-bd1a-413c5b87bc41)

**Comment by Nouri-Anouar** [comment]
Got it, and done @JulieMass 🚀

**Comment by JulieMass** [comment]
Yay! thank you so much Anwar🙏

**Comment by JulieMass** [comment]
(CC. @dbradham )

Closing this ticket as completed. I checked it in global staging and production. 

The only issue I found was a missing asterisk next to the Terms & Conditions checkbox. We'll create a ticket to fix that bug.
