### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to delete my idea page because I decided I don’t want to move forward with it.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#736]
### Considerations:
Ability to delete an idea that Miles owns from its workshopping page.

### Acceptance criteria:
- Miles as the idea owner can see the delete action in the workshopping page. Only idea owners can see this action. 
- Since delete an idea is a critical task which can't be reverted a modal dialog should be presented asking him if he wants to confirm this action.
- If Miles confirms he still want to delete the action the system should give him some type of feedback confirming his idea was deleted.
- Layout is web responsive and it works well for mobile, tablets & desktop.

-------------------------------------------------------------
### Sub-tasks:
- [x] UX design
- [ ] QA

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/736?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @RETprojects

**Comment by jordanmcousins** [comment]
Is this story for the entirety of the functionality of deleting the idea or is it just the modal to delete/asking for confirmation that they want to delete the idea?

**Comment by JulieMass** [comment]
> Is this story for the entirety of the functionality of deleting the idea or is it just the modal to delete/asking for confirmation that they want to delete the idea?

Thanks for this @jordanmcousins! As a design task I would say we can include everything in the user flow in one single item as we have it now. But we could break the development task  into smaller items. Do you think breaking it down in two (delete idea + confirmation modal dialog) would work better for development? because I could take this into account when I create the "delete idea" dev task in the future 😌

**Comment by Nouri-Anouar** [comment]
[**workshopping page**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9280&t=BQWnjhJ3WqkgQTL7-4)

**[Prototype link](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9081&scaling=scale-down-width&page-id=2645%3A5947&starting-point-node-id=3451%3A8700)**

**Delete idea record**

https://user-images.githubusercontent.com/79311912/221377497-46c3b3ba-92a3-4d0d-8eac-7a32146f70a9.mp4
