### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to edit or remove a comment because I made a mistake and want to fix it

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#739]
### Considerations:
Ability for Miles to edit or delete a comment he made in the comment feed area in the workshopping page. 

### Acceptance criteria:
- Layout is web responsive and it works well for mobile, tablets & desktop
- Miles can edit or remove a comment he owns in the comment feed
- When a comment is deleted in a thread, we should show a placeholder text where the comment was deleted.

-------------------------------------------------------------
### Sub-tasks:
- [x] UX design
- [x] QA

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/739?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @RETprojects

**Comment by jordanmcousins** [comment]
When a comment is deleted in a thread, do we want to show placeholder text where the comment was deleted?

**Comment by JulieMass** [comment]
> When a comment is deleted in a thread, do we want to show placeholder text where the comment was deleted?

Yes, great point @jordanmcousins. Thanks for bringing this up. Anwar saw your comment today and included it in the designs already 😊

**Comment by Nouri-Anouar** [comment]
[**Workshopping page**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9138&t=BQWnjhJ3WqkgQTL7-4)

[**Prototype link**](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9081&scaling=scale-down-width&page-id=2645%3A5947&starting-point-node-id=3451%3A8700)

**Prototype record**

https://user-images.githubusercontent.com/79311912/221377009-b01172c0-facf-4db9-8816-ce57a07be9b4.mp4

**Comment by JulieMass** [comment]
> [**Workshopping page**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9138&t=BQWnjhJ3WqkgQTL7-4)
> 
> [**prototype link**](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9081&scaling=scale-down-width&page-id=2645%3A5947&starting-point-node-id=3451%3A8700)
> 
> **Edit comment prototype record**
> 
> **Delete comment prototype record**

Thanks Anwar! Same with the other ones. Closing this task and thanks for the videos and useful links to the designs and prototypes. I'll include them to the devs tickets.
