### ISSUE TITLE
[ENHANCEMENT - DEV] As MILES HARDIN, I want to leave a new comment in the comment feed so that I can workshop my idea with other people (part 1)

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#744]
### Considerations:
Miles Hardin wants to add a new comment in the comment feed from the workshopping page. We also need to update the comment feed look & feel to match our new designs.

This task DOESN'T include the followings:
- Comment's filter drop down.
- Reply to a comment
- "Load more" button that brings up new comments
- Like a comment

Please refer to our 
- [Figma prototype ](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?page-id=2562%3A6706&node-id=2562%3A6894&viewport=458%2C-268%2C0.52&scaling=min-zoom&starting-point-node-id=2562%3A6894&show-proto-sidebar=1)
- “workshopping page” UX mockups in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/IdeaSpace-(Copy)?node-id=0%3A1) and related US - UXD #704.

NOTE: @Enjoy2Live mentioned this item seems to be good for the library that the platform enablement team is working on. Good to keep them updated on it. 

-----------------------------------------------

### Acceptance criteria:
- Items included in this ticket have our visual designs implemented. 
- Title of the comment feed shows the total amount of comments for this idea. _Eg. "Comment feed: 18"_
- Each comment created includes:
  - user account name _(e.g. Elisha James)_
  - the commented text 

-----------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/bf489d34-16c4-4bd2-8ca9-ba787a07c027)

![image](https://user-images.githubusercontent.com/104226366/213287447-96060b0f-7de0-4e16-ab6a-e96a9e3f9c14.png)

![image](https://user-images.githubusercontent.com/104226366/213287504-dbde6ae9-e526-4574-9d3e-bd2cbf9b5b04.png)

![image](https://user-images.githubusercontent.com/104226366/213288402-11796be0-06ce-48e5-8622-b2b7ba784def.png)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/744?planning-poker) with Zenhub @dbradham @jordanmcousins @alicefate @liwenlin664477 @RETprojects

**Comment by jordanmcousins** [comment]
I have two questions for this story: 1. Is the focus of this story to create a single reusable comment component or is it to create a comment feed? 2. Is there a character limit on how long we want a comment to be?

**Comment by dbradham** [comment]
We should be able to reuse the "like" button from common packages

**Comment by dbradham** [comment]
Hey @JulieMass , Remi is going to pick up this ticket. Please let him know if there are any remaining blockers. (looks like it is ready for development since the blocker is in closed)

**Comment by JulieMass** [comment]
> I have two questions for this story: 1. Is the focus of this story to create a single reusable comment component or is it to create a comment feed? 2. Is there a character limit on how long we want a comment to be?

Hey @jordanmcousins, thanks again for bringing these questions ☺️! As discussed today replying to them inline:

1. This item would only include updating the look & feel to match our new designs. So we aren’t thinking of including new functionality such as the filter dropdown, replying to comments, etc. I left a note in the description of what ISN’T included to help clarify.

2. I’ve found the item where Remi worked on this . It was #640. And we defined: Min. 25 - Max. 250 characters per comment

**Comment by JulieMass** [comment]
> Hey @JulieMass , Remi is going to pick up this ticket. Please let him know if there are any remaining blockers. (looks like it is ready for development since the blocker is in closed)


Thanks @dbradham. 

@RETprojects Awesome you decided to take it. Thank you so much! Please note the followings:

1. As we discussed in today’s meeting, I’ve just updated the description to clarify what we aren’t including. But please let me know if you have any other questions too.
2. Even though we don’t have blockers for this task, Anwar has been updating our design Figma file and things have changed since I first wrote this user story. I’m having a meeting with him today related to this so we can bring some consistency for our designs and an agreement on how to communicate the designs the team needs to follow and where to find them. After our meeting I’ll share what we decided and any updates on this.
3. Finally Remi, can you please add the final estimation for this item? The poker planning is showing two “3” and two “5”.

**Comment by JulieMass** [comment]
@RETprojects  we talked today with Anwar and he is going to clean up our Figma files. @Nouri-Anouar can you please take the workshopping page as priority and let Remi know where he can find the final design for the comment feed in Figma please? so he can start working on this task? because as we discussed today, we needed to fix some minor design inconsistencies there like the title of the cards. Thank you in advance 🙏

**Comment by Nouri-Anouar** [comment]
> @RETprojects we talked today with Anwar and he is going to clean up our Figma files. @Nouri-Anouar can you please take the workshopping page as priority and let Remi know where he can find the final design for the comment feed in Figma please? so he can start working on this task? because as we discussed today, we needed to fix some minor design inconsistencies there like the title of the cards. Thank you in advance 🙏

Got it!

**Comment by Nouri-Anouar** [comment]
@RETprojects here is the final design:
![comment feed](https://user-images.githubusercontent.com/79311912/216960991-6281282a-22f1-4d7d-8ad7-dac34e3a38d4.png)

You can also take a look at this in [**Figma**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3451%3A8700&t=rU3OLgq2i54jdS4y-4)


@JulieMass please review this and let me know if there is any inconsistencies.

**Comment by JulieMass** [comment]
> @RETprojects here is the final design: ![comment feed](https://user-images.githubusercontent.com/79311912/216960991-6281282a-22f1-4d7d-8ad7-dac34e3a38d4.png)
> 
> You can also take a look at this in [**Figma**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3451%3A8700&t=rU3OLgq2i54jdS4y-4)
> 
> Additionally, here is the **[Prototype](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3451%3A8700&scaling=min-zoom&page-id=2645%3A5947&starting-point-node-id=3385%3A8557)**
> 
> @JulieMass please review this and let me know if there is any inconsistencies.

Thank you Anwar! I only noticed that the reply button is missing in the first two comments from Amelia 🥸😜 but since replying to comments ins't part of this user story I think this is good for Remi to start working.  🙌

**Comment by dbradham** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUNqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55d5e0caee35191cde809c808a73a432497d633b/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6c377c74f72f6509a46e89a02d5cdf1321f5f74/image.png)


@RETprojects can you update the design for the comments to match the first image here? The name and time since the comment was posted should both be adjacent to the user's profile. The time since it was posted should also be a smaller font size in gray. You should be able to get the exact font sizes and colors from the figma file using dev mode.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUtqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88ed47cd8732b644b6afd6e5312a31f1bacb689e/image.png)

**Comment by RETprojects** [comment]
When I post a new comment to an idea's workshopping page on staging, the number of comments updates immediately, and the new comment is shown with my username, the comment text, and how long ago it was posted. The newest comment first appears at the top of the feed, but upon refreshing, the feed has been sorted so that the newest comments are at the bottom.

**Comment by chadcrotchett** [comment]
@dave this looks to me like the alignment works the same in Prod and Staging, and is working as expected. Do you agree?

<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9214929e7d1c341542bf7ebc31f2195bd24c01e2/image.png" alt="image.png" />

**Comment by dbradham** [comment]
@chadcrotchett agreed! We should include this in the July 28 release and close out the ticket here.
