### ISSUE TITLE
[US - DEV] As AMELIA HARRIS, I want to browse the ideas page so that I can discover ideas I could collaborate.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#745]
### Considerations:
Developing the new visual design layout and a simple initial idea card in the Ideas page. 

This user story _doesn't_ include the following functionalities:
- filtering or ordering ideas
- Search ideas
- Secondary Title with a counter of the amount of ideas (e.g. 31 Ideas). The counter will be implemented in a separate user story. 
- "Save", "like" or "share" buttons in the idea cards. These will be implemented in future user stories.
- "Load more" button at the bottom of the page.

Please refer to UX designs of **Dev Ideas page** in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=5fHSxtzyVh1IzGWL-1) 

### Acceptance criteria:
- New visual design is implemented and it includes:
   - **Page Title** ("Browse Ideas") + **subtitle** ("Want to help develop an idea....")
   - **new visual design layout & structure**
   - A simple **"Ideas" secondary title** for the card area. _Note: The ideas counter will be implemented in a separate user story._ 
   - **Cards with ideas**. Card should include:
       - A picture of the idea (please check the dashboard page. we could reuse the cards made by @alicefate)
       - An status tag for the idea (same as above)
       - Idea title (e.g. "Startup Services Platform")
       - Number of comments (E.g. "Comments: 51")
       - Last updated date (E.g. "3 days ago")
       - "Help an idea" button that takes Amelia to the corresponding workshopping page
   - **Back button** that returns to the "Ideas" page (https://devlaunchers.org/ideas/browse)
- Amelia can access ideas by:
 - clicking on the card 
 -_or_ by clicking on the “help this idea” button from the idea card and go to the “workshopping" page
- Layout is web responsive and it works for mobile, tablets and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [X] UX design
- [ ] Development
- [ ] QA

----------------------------------------------------

Note: Elements _not included_ in this user story are marked with an "x".
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/62de93b0-5bda-43df-a0b0-4013c1efc0b8)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/745?planning-poker) with Zenhub @jordanmcousins @dbradham @RETprojects @liwenlin664477 @alicefate

**Comment by dbradham** [comment]
@JulieMass Where should the "pictures of the ideas" actually pull from? It seems like we're just using random images now. Rashika had the same question for the workshopping page since we noticed there is no image upload on the submission form, we don't really know what to use for the pictures.

**Comment by JulieMass** [comment]
> @JulieMass Where should the "pictures of the ideas" actually pull from? It seems like we're just using random images now. Rashika had the same question for the workshopping page since we noticed there is no image upload on the submission form, we don't really know what to use for the pictures.

(CC. @rashikashaw)

Yes, for the moment we are just using random images. Also currently we have a first version of the "edit" of an idea because we wanted to start with something easy to develop. But we'll be designing and developing a better, more advanced version of the edit idea where Miles can edit the idea from the idea workshopping page instead of editing from the idea submission as it is now and there we'll add the image upload. But we need to design this first. Coming soon!

**Comment by dbradham** [comment]
@alicefate Do you know what is causing the tiles to display like this on page load?

![image.png](https://images.zenhubusercontent.com/639ba80c96c787af67163973/fdb1981f-231d-44ab-a235-48f57f2167fe)

**Comment by alicefate** [comment]
@dbradham tag is used after image. Image is loading or load failed due to Inter problem.

**Comment by JulieMass** [comment]
Hi @alicefate and @dbradham 

Can we include here a minor minor typo fix or should we create a different ticket for this? Can we change the subtitle from "Want to help developing ..." to "Want to help **develop** an idea?"

@Nouri-Anouar and I missed this little typo while doing the design reviews 😅 

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/cf87254d-4be0-4fe8-8ff0-d87f70b9eabd)

If a separate ticket is better I'll create it.

**Comment by alicefate** [comment]
> 'clicking on the card 
> -or by clicking on the “help this idea” button from the idea card and go to the “workshopping" page' 
@JulieMass My mistake, I thought second line is the detail of how to accomplish it. I have a question, if the whole card is clickable, why we still need “help this idea” button?

**Comment by JulieMass** [comment]
Thank you Iris 🙏! 

In respect to the button I think where I can find it most valuable is the label might help new users. They might know they can access ideas by clicking on the card because the cursor changes but I think the label “Help this idea” is more specific about how they can interact with ideas and what they’ll find on the other side of the click.
