### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to accept the “terms and conditions” page so that I can submit my idea

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#747]
### Considerations:
Miles Hardin needs to read and accept the terms and conditions before submitting an idea in the idea submission page. 

Terms and conditions should include legal information related to idea ownership, etc.

### Acceptance criteria:
- The terms and conditions checkbox is included in the idea submission form.
- There is a link in the idea submission form for Miles Hardin to read the terms and conditions page. 
- Terms and conditions page is designed and allows Miles to return back to the idea submission form.
- New visual design (hi-fi mockups) and web responsive (mobile, tablet and desktop breakpoints).

----------------------------------------------------
### Sub-tasks:
- [x] UX design: Hi-fi mockups for the T&C checkbox in the idea submission form.
- [x] UX design: Hi-fi mockups for the T&C page.

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/23430139-c34e-4b2e-b10f-bce722b63f0a)![image.png]

UX Designs on Figma: https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=4670-10746&t=auPGVxyhZwX8kIEk-0

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/747?planning-poker) with Zenhub @dbradham @jordanmcousins @alicefate @RETprojects

**Comment by JulieMass** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/747?planning-poker) with Zenhub @rashikashaw

**Comment by MariliaDP** [comment]
Hi @JulieMass, Do we already have content for the T&C page? Or should I use Loren Ipsum? 
Do we have any other policy page already created for Dev Launchers?

**Comment by JulieMass** [comment]
Hi Marilia, thank you so much for taking this task! I’ll add it to our current sprint and move it to the sprint backlog column. Please move it to “work in progress” when you start working on it, and “done” when you consider it done. “Review” and “QA” columns are for development tasks. 

Yes, we have all the content ready for the Terms & conditions. Below some links that you may find useful:

1. “02. Idea ToC (Terms & conditions) - FINAL VERSION” in this doc you can find the final copy. I cleaned it up to make it less confusing.
2. “”01. Idea ToC (Terms & conditions) - Research & process”--> this doc is our original one. You can find some interesting links that we researched other Terms & conditions, good practices. Etc. 
3. Another good resource is this Figma we have in the team where we left some screenshots that can serve as inspiration (no need to follow this to the rule, just inspiration! :)) 

I hope this helps and let me know if you have any questions please,

**Comment by MariliaDP** [comment]
Sounds great @JulieMass 
Thanks for sending the content and other links. I'll check everything out asap.
One question (Sorry still getting used to Github and Zenhub): It looks like you closed this issue. Do I have to reopen it? Or keep it closed? Can I still move it to work in progress while closed?

**Comment by JulieMass** [comment]
Ops! I pressed the wrong button when trying to send a comment 😂 LOL Ticket reopened. Thanks for the heads-up!

**Comment by MariliaDP** [comment]
Haha, no worries :)

**Comment by MariliaDP** [comment]
UX Design on Figma: https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=4670-10746&t=auPGVxyhZwX8kIEk-0

**Comment by MariliaDP** [comment]
<img width="982" alt="Screenshot 2023-05-31 at 9 49 59 PM" src="https://github.com/dev-launchers/dev-launchers-platform/assets/130269888/90c348c2-e9f2-4d4a-83ec-7a325063a2ef">
This ticket is considered done.

UX prototype: https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?type=design&node-id=4670-10746&scaling=scale-down-width&page-id=2562%3A6706&starting-point-node-id=2834%3A6526

**Comment by JulieMass** [comment]
Hi @MariliaDP ,

Thanks for sending over the prototype link! I'll add it to Iris's development ticket. 

Before I close this ticket, could you please move the final mockups to our "LATEST DESIGNS" page when you have a moment? This will help any developer find it easily and understand that this is our final approved design.

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/6a9bb40e-b468-4842-82f2-c7b976bb5bcc)

**Comment by MariliaDP** [comment]
Done @JulieMass let me know if you need anything else. Thanks!

**Comment by JulieMass** [comment]
> Done @JulieMass let me know if you need anything else. Thanks!

Thank you so much Marilia! Ticket closed 🎉

![giphy](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/3b1813da-8a6c-487d-a91f-50e7797d1511)
