### ISSUE TITLE
[US] As MILES HARDIN, I want DL.org domain verified in Google search console so that I can  find IdeaSpace url as a result when I search organically in search engines for a solution to my problem.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#767]
### **Considerations:**
We want to verify devlauncher.org domain in Google search console to learn how we can optimize IdeaSpace’s content for organic search. 

### **Acceptance criteria:**
- devlaunchers.org domain is verified in google search console
- google search console tracks data from DL.org
- IdeaSpace product owner has access to DL.org domain google search console

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/d3b9791c-be63-4078-94df-76a94b3530a9)

**Comment by pyxld-kris** [comment]
Done! devlaunchers.org has been verified, and I've added your @devlaunchers email with full permissions. Sending you a screenshot in Discord

**Comment by JulieMass** [comment]
> Done! devlaunchers.org has been verified, and I've added your @devlaunchers email with full permissions. Sending you a screenshot in Discord

Thanks Kris. I tried it out and it is working  👍
