### ISSUE TITLE
[bug] some bug and needed improvement of top navBar and storybook component

### ISSUE THREAD

**Issue by alicefate** [dev-launchers/dev-launchers-platform#775]
1. navBar width should be "auto" instead of "100%". There is a horizontal scoll
![1](https://user-images.githubusercontent.com/33647003/208369508-1d93474d-4420-49d1-aa61-ee5d79297674.JPG)

2. navBar link don't work. 
![2](https://user-images.githubusercontent.com/33647003/208369615-d60100e0-c053-443c-b04d-4a4bf5e838bf.gif)

3. BackButton don't have onClick

4. I hope we can have a refocus of submit, let user know where to fill. like what happen in tranditional form tag 
![3](https://user-images.githubusercontent.com/33647003/208370227-bcae27f1-b4c2-4233-b3fa-03e32fb09d62.gif)

5.  on a thin width, required mark appear in a seperate line. (I merge master branch on 12.19 1AM. It not be fixed, maybe wait to merge.)
![4](https://user-images.githubusercontent.com/33647003/208370670-f72dcb02-3228-43f5-b694-b4408338abd0.JPG)

6. error message is away from inpunt. It should in the label. it is a seperate div tag now, gap works on it.
![6](https://user-images.githubusercontent.com/33647003/208371050-212a0eb6-f8b6-48ea-be4f-3e0897e5e286.png)

**Comment by Enjoy2Live** [comment]
this PR should fix most of the issues discuss here #792
