### ISSUE TITLE
[US - DEV] As MILES HARDIN, I want to save an idea from the workshopping page so that I can easily get back to it from my saved list.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#776]
### **Considerations:**
Ability to save an idea from the workshopping page. 

Please refer to the Workshopping page UX designs in [Figma ](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1) 

For the interaction of how a save button should function, please check out the [DL style guide in Organisms / cards](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?type=design&node-id=1055%3A1097&t=IX4WDwB9dY7Vw6zk-1). (screenshot below)

### **IMPORTANT ⚠️:**
We can work on developing this task together with the Platform enablement team since this component  might still be pending to be developed. We think it is related to #688 (please verify with @Enjoy2Live) 

### **Acceptance criteria:**
- Save button is included in the workshopping page.
- When Miles does a mouse over the button a tooltip that says "Save idea" appears. 
- Miles can save an idea by clicking on its button in the workshopping page.
- After clicking the save button, this idea should be included in his saved list called “Ideas I follow” in his dashboard and the button changes its status to “saved” (button interactions are in our DL style guide. Please check screenshots below)
- The save button is web responsive and adapts for mobile, tablets and desktop breakpoints.

----------------------------------------------------
### **Sub-tasks:**
- [X] UX design
- [ ] Development
- [ ] QA

----------------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/e4d73fce-3ccc-4659-8ee3-4ece22d71ce9)

Save button interaction from our [DL styleguide](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1055%3A1098&t=cugPyPbJ7GoDNuU1-1):
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/3c102e0f-504f-403c-a422-008f66f5526b)

Saved ideas list in the dashboard page:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/f598eb20-2c70-4e6a-a135-b869f4acd8ad)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/776?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @pyxld-kris @RETprojects

**Comment by dbradham** [comment]
@rashikashaw Since you are working on the changes to the workshopping page, would you be willing to pick up this ticket? The former assignee is no longer working with dev-launchers.

**Comment by rashikashaw** [comment]
> @rashikashaw Since you are working on the changes to the workshopping page, would you be willing to pick up this ticket? The former assignee is no longer working with dev-launchers.

Sure no problem. I'll get this done!

**Comment by JulieMass** [comment]
@dbradham  I thought this ticket was done for some reason....was I wrong? so weird! I was checking its history and I moved it to "Review" 2 months ago but if I did this was because I must have understood on one of our weekly meetings that it was OK to move it there. I wouldn't have just moved it without the OK from the owner.

Once more...I don't think me moving the tickets works so I'll just stop =( . I'll also add this ticket as part of our current sprint.

**Comment by JulieMass** [comment]
We're closing this ticket because we've decided to change the 'save' button to 'Follow'. We'll open a new ticket for the 'follow' button updates on the workshopping page, which Rutuja is currently working on the backend with ticket #913. This will help us start fresh and clear the backlog more effectively.
