### ISSUE TITLE
[ENHANCEMENT - DEV ] Implement cards in the workshopping page

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#787]
### Considerations:
We need to implement the cards to the workshopping page.

This item task _doesn’t include_ the following:
- Idea’s picture
- Product owner board
- Tags
- word cloud
 - Idea roadmap
- Actions: Edit, delete, share or transfer an idea.

Please refer to UX mockups for **“Dev Idea Workshopping Page”** in [Figma ](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1) 

### IMPORTANT ⚠️:
We can work on developing this task together with the Platform enablement team with the following related items: #669 (launcher organism) , #673 (expandable blurb - organism)

----------------------------------

### Acceptance criteria:
The following cards are implemented in the workshopping page:
 - The idea name + tagline card
 - Description card 
 - Idea features card
 - Target audience card
- Cards are web responsive and adapt for mobile, tablets and desktop breakpoints.

--------------------------------------------------------------------
### **Sub-tasks:**
- [x] UX design
- [x] Development
- [ ] QA

--------------------------------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/2e8d16ff-5117-4aae-8922-58ff50f6102f)

**Comment by dbradham** [comment]
@JulieMass just FYI-we did not reuse anything from platform enablement's shared components here-Rashika created everything from scratch because that was much more straightforward and these are relatively simple components. Let us know if we needed to integrate anything from PE's shared components.

**Comment by JulieMass** [comment]
@dbradham moving this back to QA column so the QA team can check this ticket. 

@vidisha-qa and @soniekhande when QA is done, can you please move the ticket to the "done" column so we know it is ready? thank you in advance and let us know if you have any questions.

**Comment by JulieMass** [comment]
Great job @rashikashaw and @dbradham! It looks amazing. ticket is closed 👏
