### ISSUE TITLE
[US - UXD] As MILES HARDIN, I want to edit the information from my idea Workshopping page because I want to improve its content

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#789]
### Considerations:
We are going to develop a first iteration for ideas edition in which Miles could edit the ideas he owns from the submission form.

### Acceptance criteria:
- Miles can edit the content of the ideas he owns
- There is an “edit” button on the ideas Miles owns on the _dashboard_ and _workshopping_ pages.
- When Miles clicks on the edit button, he will be redirected to the _submission form_ where he can edit the idea. 
- When he is updating the idea in the submission form, the button label should say “Save edits”. 
- If he clicks in “Save edits”, the changes he made should be updated and he will be again redirected to the workshopping page so he can see the results of his editions. 
- Miles can also click in a "Cancel" button in the _submission form_ in case he wants to cancel the edition and go back to the workshopping page. 
- If Miles made changes and suddenly decides to leave the submission form, a modal window would appear asking him to confirm if he wants to leave because he hasn't saved his changes.
- Edit buttons in the workshopping page and submission form are web responsive and adapts for mobile, tablets and desktop breakpoints.
- New visual design (hi-fi mockups) are designed 
- Mockups are web responsive and include mobile, tablet and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [x] UX design: Hi-fi mockups for the dashboard, submission form and workshopping page.

----------------------------------------------------
User flow defined within a design meeting with @Nouri-Anouar  and @alicefate
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/1f36bdbc-126a-4ce5-a262-081c8f41005d)

**Comment by JulieMass** [comment]
Hey @Nouri-Anouar I created your user story for designing the edit designs we discussed today with Iris. Let me know please if the description is OK or if I missed anything. Also, could you please estimate it?

**Comment by JulieMass** [comment]
> Hey @Nouri-Anouar I created your user story for designing the edit designs we discussed today with Iris. Let me know please if the description is OK or if I missed anything. Also, could you please estimate it?

@Nouri-Anouar Friendly reminder to estimate this task 🙏.

**Comment by Nouri-Anouar** [comment]
Thanks you @JulieMass  for the reminder.
Estimation done!

**Comment by JulieMass** [comment]
> 🙏



> Thanks you @JulieMass for the reminder. Estimation done!

Thank you 🙏

**Comment by JulieMass** [comment]
We forgot to review this task today 😂. Let me know later if you would like to check it out so we can mark it as done please.

**Comment by JulieMass** [comment]
Hey @Nouri-Anouar I was checking the acceptance criteria in this task to see if we can considered it closed but I noticed we haven't created the designs for this point :_"If Miles made changes and suddenly decides to leave the submission form, a modal window would appear asking him to confirm if he wants to leave because he hasn't saved his changes."_

Dave told me last week Iris was developing this modal window using a custom solution so we might not need a design for this modal from you. So let me confirm this with her here. @alicefate will you need a design for the modal window from Anwar? let us know please.

**Comment by Nouri-Anouar** [comment]
@JulieMass I totally missed that Dave mentioned it. I am okay with either options.
@alicefate let's us now what you think!

**Comment by JulieMass** [comment]
> @JulieMass I totally missed that Dave mentioned it. I am okay with either options. @alicefate let's us now what you think!

Hi @Nouri-Anouar & @alicefate question: what are your thoughts on including in the user flow for this task the following point that was in acceptance criteria :"If Miles made changes and suddenly decides to leave the submission form, a modal window would appear asking him to confirm if he wants to leave because he hasn't saved his changes."? 

The reason I included that in the acceptance criteria was to cover the scenario where Miles edited his idea in the submission form but maybe clicks by mistake in the "back" button. Shouldn't we cover that scenario too and present him a modal window or something to ask him if he is sure he wants to leave without saving his changes?

If Miles _didn't_ made any change in the submission form while in edit mode he would be able to click in the "back" button and leave without reminding him of anything. but what if he _did_ made changes? shouldn't we ask him something like "hey! are you sure you want to leave without saving your changes?" or similar?

Let me know please, because if we decide to not include this scenario I need to remove this point from the acceptance criteria in order to consider this task done and close it. 

Thank you in advance

**Comment by Nouri-Anouar** [comment]
@JulieMass I already added confirmation modal to the prototype today.
It shows up if the user clicks on "CANCEL" or "BACK" while editing an idea.

**Comment by Nouri-Anouar** [comment]
[**workshopping page**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9280&t=BQWnjhJ3WqkgQTL7-4)

**[Prototype link](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9081&scaling=scale-down-width&page-id=2645%3A5947&starting-point-node-id=3451%3A8700)**

**leaving idea edit without saving record**

https://user-images.githubusercontent.com/79311912/221379620-cb722f42-ed08-4f82-adf5-9fa319cbece4.mp4

**saving idea changes record**

https://user-images.githubusercontent.com/79311912/221379894-b2cade9b-0874-446e-a2ef-453969bbd61f.mp4

**Comment by JulieMass** [comment]
> [**workshopping page**](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9280&t=BQWnjhJ3WqkgQTL7-4)
> 
> **[Prototype link](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9081&scaling=scale-down-width&page-id=2645%3A5947&starting-point-node-id=3451%3A8700)**
> 
> **leaving idea edit without saving record**
> 
> **saving idea changes record**

Thank you so much Anwar! This is awweeesome!! even with videos😀! I've shared this with Iris since she's been developing the idea edition.
