### ISSUE TITLE
[US - UXD] As Miles Hardin, I want to archive an idea so that I can pause it's workshopping phase, back it up and reactivate it later if I want to.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#795]
### Considerations:
Miles Hardin as an idea owner, and administrators have the ability to archive ideas.

Ideas that are archived won’t be visible, cannot be accessed or workshopped anymore to IdeaSpace collaborators like Amelia Harris or Frank Wang. Only Miles Hardin (the idea owner) or an admin will have visibility of this idea with a status of “archived” and only them can reactivate the idea to make it be visible and allow people to workshop it again.

Questions to consider:
- Where should Miles go to reactivate his idea? The dashboard page? 
- How can he reactivate his ideas? 
- What if Amelia Harris commented on Miles’s idea and searched for it after he had achieved it? How can we let her know that the idea has been archived and hence cannot be workshopped or accessed anymore?

### Acceptance criteria:
- New visual design (hi-fi mockups) are designed for “archive an idea” user flow and “idea archived” message for Amelia Harris.
- Mockups are web responsive and include mobile, tablet and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [x] UX design: Hi-fi mockups for “archive an idea” user flow and “idea archived” message for Amelia Harris.

----------------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/aa588b1b-62fc-4506-8f45-33e2cc536f5c)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/6ac589ae-2a82-4cfe-94dd-25b6b97da5d9)

**Comment by Nouri-Anouar** [comment]
[workshopping page](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9280&t=BQWnjhJ3WqkgQTL7-4)

[modals design](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3385%3A8563&t=BQWnjhJ3WqkgQTL7-4)

**[Prototype link](https://www.figma.com/proto/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=3446%3A9081&scaling=scale-down-width&page-id=2645%3A5947&starting-point-node-id=3451%3A8700)**

**Record**

https://user-images.githubusercontent.com/79311912/221376218-52bfc4cf-7648-4623-957c-32163ecde540.mp4
