### ISSUE TITLE
[ENHANCEMENT - DEV] Implement new visual design for the filter’s component

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#796]
### Considerations:
We need to update the filter’s in the ideas page to match the dropdown component from the [DL styleguide](https://www.figma.com/file/EwzuhhvTulvFRMvhTD5VAh/Dev-Launchers-Style-Guide?node-id=1055%3A1098&t=8LzCwdGNVvrY7YOZ-1).

### Acceptance criteria:
- The drop down follows the DL style guide and uses the component from the Platform enablement team (#682).
- Layout is web responsive and it works well for mobile, tablets and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [X] UX design
- [ ] Development
- [ ] QA

----------------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/e06d8d9e-e012-4988-ae42-19ed5beae60c)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/b73bab1f-0f5e-43a8-acc1-038063d68e24)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/796?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @RETprojects

**Comment by dbradham** [comment]
@JulieMass where can I find the most recent design file for the /browse page?

I'm wondering if this element should be center justified (what Jordan has in his code), or left justified. (what Iris had in her code)

**Comment by JulieMass** [comment]
Hi @dbradham the [figma file](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=dwNgxx9euOwKCdmG-1) shows the filter aligned to the right.  

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/07461b96-dc19-4426-adcd-1dfea9434450)

Also I would say closed by default.

**Comment by JulieMass** [comment]
Hey @dbradham once you consider this or other tickets are ready for the QA team to be reviewed, can you please add the "QA" label so the ticket appears in the QA team zenhub board and assign it to @vidisha-qa and @soniekhande please? this will let them know tickets are ready for their team to be reviewed.

**Comment by JulieMass** [comment]
As discussed in today's sprint planning with the team, we decided to close this ticket and follow up the work with ticket #993
