### ISSUE TITLE
[UXD] Usability testing with hi-fi prototype #2 - Step 2:  Build interactive prototype

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#806]
### Context:
We are running a usability test with a hi-fi prototype of our product to discover how we can improve our target audience’s experience, if it brings value to them and if it is easier, more intuitive and fun to create and collaborate on ideas.

In this task we need to build the interactive prototype in Figma so we can test it.

-------------------------------------------------

### Acceptance criteria:
- Interactive prototype in Figma was developed

**Comment by JulieMass** [comment]
Hi @Nouri-Anouar, 

As promised I'll be sharing my notes from the meeting with Kris and Dave related to defining how an idea will become a project in Dev Launchers. The idea is that we could include these in our prototype so we can test them with people and learn. 

First and all, please take all these as suggestions. Feel free to bring better ideas, improve our content suggestions, make changes on what I'll be sharing, etc. Your designer opinion is important and if you don't agree with something we are suggesting here can discuss them together ❤️

### NOTES

**Idea owners**
- Are the ones who edit the page. Whether there is movement on the page or not.
- Miles can choose to be an idea owner or postulate as a candidate for a product lead. 

 **Change requests in our UX designs**

**1. Top navigation → change “Dream” to “Ideate”**
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/457dd616-395c-4a57-9d67-160ff7815b09)

**2. Idea submission page **
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/fbe76235-8100-480c-ab50-6969d34d0be3)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/30cf4054-619e-4e82-b57a-51cb3880dc8d)

**3. Ideaspace Roadmap (landing page, workshopping page, confirmation page, etc.) **
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/0addcc71-7746-4ea5-8ec7-403f63aac85f)

**4. Idea Workshopping page → Checklist**
_note: same as above with the roadmap, please save the current designs. We'll probably bring these back in the furute._

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/8688ee27-22ab-4056-b399-1a1a8ea3eb82)![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/733c6d1f-c83c-4cb9-8797-2d6928a315b5)

Let me know if you have questions and I hope the images help! 🙌

**Comment by Nouri-Anouar** [comment]
@JulieMass Thank you for all these details.

**Comment by JulieMass** [comment]
Moving the ticket to "work in progress" since I'm working on it with Anwar and we still need to do the pilot test to check if there are pending updates to it.

**Comment by JulieMass** [comment]
@Nouri-Anouar as discussed, the pilot test task is removed from the AC. Thank you so much for your help today in the meeting with Kate! you made it look easy and saved us a lot of time.

**Comment by Nouri-Anouar** [comment]
Yes it was a productive meeting and it is a pleasure working with you @JulieMass @katehirschman!

**Comment by katehirschman** [comment]
Hi @Nouri-Anouar I just finished a pilot test on the prototype and noticed one page where the navigation label says "Dream." It's on the Idea Workshop page for Mentor Match. Other than that, everything went really well. Thanks for all your help!!

**Comment by katehirschman** [comment]
![Prototype Workshop - Dream.png](https://images.zenhubusercontent.com/63f4c76b31b0bf353fde8f8c/6d137aa6-9225-44ef-8521-137dd6048164)

**Comment by Nouri-Anouar** [comment]
That sounds great @katehirschman.
Thank you for catching that, it is updated now!

**Comment by JulieMass** [comment]
Hey Anwar, Kate mentioned on Sunday that she was going to run the pilot testing this week and see if anything in the prototype was needed. Do you want to check with her?

**Comment by Nouri-Anouar** [comment]
Got it Julie.
@katehirschman how is everything going? Is there anything needed in the prototype?

**Comment by katehirschman** [comment]
@Nouri-Anouar I will run the pilot test as soon as possible and let you know if there are any issues. Thank you!

**Comment by katehirschman** [comment]
Hi @Nouri-Anouar 

I ran another pilot test this morning and everything went great!

**Comment by Nouri-Anouar** [comment]
@katehirschman awesome! Thanks!

**Comment by JulieMass** [comment]
Hi @Nouri-Anouar is this ticket completed? If so, can you please close it so it doesn't impact our team velocity?

**Comment by Nouri-Anouar** [comment]
Got it @JulieMass , done!

**Comment by JulieMass** [comment]
thank you 🙏
