### ISSUE TITLE
[UXR] Usability testing #2 with hi-fi prototype - Step 4: Debrief session with Observers + Data Analysis & Synthesis

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#808]
### Context:
We are running a usability test with a hi-fi prototype of our product to discover how we can improve our target audience’s experience, if it brings value to them and if it is easier, more intuitive and fun to create and collaborate on ideas.

In this task we are **facilitating a Debrief Session with observers** to reflect on the usability test experience and analyze what happened, what it means, and what can be learned from it. .

-------------------------------------------------

### Acceptance criteria:
- Debrief meeting with observers was conducted.
- Collected data from the usability tests is analyzed and synthesized.
- Repeated behaviors and patterns across participants were found.
- Insights were captured from the data and organized into themes

**Comment by JulieMass** [comment]
@katehirschman As discussed today, I updated the acceptance criteria of this ticket and moved the analysis & synthesis part to the report ticket. Let me know if this is OK or if  I missed anything please.

**Comment by katehirschman** [comment]
Hi @JulieMass 
This ticket should also include:
Repeated behaviors and patterns across participants were found.
Insights were captured from the data and organized into themes
And removed from the new one.
Thank you!

**Comment by JulieMass** [comment]
> Hi @JulieMass This ticket should also include: Repeated behaviors and patterns across participants were found. Insights were captured from the data and organized into themes And removed from #809 Thank you!

Thank you Kate! Both tickets are updated. Let me know if I missed anything please but hopefully they are OK now.

**Comment by JulieMass** [comment]
Hey Kate, thanks! Just a quick note for the future - it's actually the Product Owner's responsibility to close tickets 😅. I'm responsible for checking the tickets in the "done" column and ensure that the Definition of Done is being followed and that the tickets are complete before closing them. So please for future tickets if you considered it done, move it the done column and I'll take it from there.
