### ISSUE TITLE
[UXR] Usability testing #2 with hi-fi prototype - Step 5: Coding & tagging data

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#809]
### Context:
We are running a usability test with a hi-fi prototype of our product to discover how we can improve our target audience’s experience, if it brings value to them and if it is easier, more intuitive and fun to create and collaborate on ideas.

In this task we are **coding and tagging data** with EnjoyHQ.

-------------------------------------------------

### Acceptance criteria:
- Data is coded while analyzing using our EnjoyHQ tagging and property's taxonomy.

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/809?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @RETprojects

**Comment by JulieMass** [comment]
Hi @katehirschman same with this ticket. I updated the description and acceptance criteria. Let me know if this is OK and if I missed anything please.

**Comment by JulieMass** [comment]
Hey @katehirschman ,

I just wanted to follow up on what we discussed during our sprint planning yesterday. I went ahead and removed the report-related tasks from this ticket, leaving only the first step of coding data. I also created a new ticket for the report, which is ticket #1324.

In summary, this is how everything we've been doing for this usability testing looks like (screenshot attached below). The ones that are crossed are the closed tickets. Let me know please if this makes sense and if it is OK. Thanks!

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/76ba1987-14ca-45b4-a768-223cd8d96a31)

**Comment by katehirschman** [comment]
Hi @JulieMass 
All looks good! I've moved this one to review and added 1311 to in progress. Thank you!!
