### ISSUE TITLE
[US - DEV] As AMELIA HARRIS, I want to see an “idea owner” tag in the comment feed so that I can visually identify Miles's comments.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#840]
### Considerations:
Miles’s comments will be highlighted in the comment feed with an “idea owner” tag to differentiate these from the other community members. 

Note: in the future we’ll be having “editor” tags for people that have edit permission on IdeaSpace’s content.

Please refer to UX designs in  [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=5fHSxtzyVh1IzGWL-1)

### Acceptance criteria:
- An “idea owner” tag is added next to all idea owners username in the comment feed
- Layout is web responsive and it works well for mobile, tablets and desktop breakpoints

----------------------------------------------------
### Sub-tasks:
- [X] UX design
- [ ] Development
- [ ] QA

----------------------------------------------------
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/68c2275a-a117-4b0e-ba79-a1fa33c739a7)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/840?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @Nouri-Anouar @RETprojects

**Comment by dbradham** [comment]
@alicefate do you know if we currently have these fields available in the backend for an idea?

**Comment by Nouri-Anouar** [comment]
@RETprojects 
I created an ideaspace role component [here](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=4119-10172&t=YhgxtYBkawRoIBiW-4)

I used colors from the styleguide that you can also find in the global theme. You can see which ones I used if you select an element and go to inspect tab
![image](https://user-images.githubusercontent.com/79311912/226862804-4eb04cc0-d75d-4d7a-b372-fa1d91ed3576.png)

let me know if you have questions.

@JulieMass  I've only designed two variants, orange and blue, do you think that is enough for now? considering tags that we discussed earlier.

**Comment by JulieMass** [comment]
Yes @Nouri-Anouar this is perfect👌.thank you!

**Comment by JulieMass** [comment]
As discussed with @RETprojects, we are moving this ticket to the icebox as he is currently working on ticket 1138.

**Comment by JulieMass** [comment]
For item history documentation: As discussed today with @RETprojects  and @dbradham in Discord, we are moving this ticket to the icebox so Remi can focus on his current bug #953. We’ll come back to this one later. Thank you @RETprojects

**Comment by RETprojects** [comment]
The idea owner tag appears to work correctly. It shows for comments posted by the author of the idea and doesn't for users who aren't the author.

**Comment by chadcrotchett** [comment]
Agreed, moving to Release.
