### ISSUE TITLE
[Enhancement - UXD] Content enhancements in landing page after researching Google trends & Google search console

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#845]
### Considerations:
We think that by including certain keywords in our landing page’s content it might help improve our product’s SEO (search engine optimization). For this we researched frequently researched keywords in Google trends and our Google search console (#771) and we brought suggestions for its content. 

### Acceptance criteria:
- Content improvements are included in our landing page hi-fi mockups.

----------------------------------------------------
### Sub-tasks:
- [x] UX design: Implement content suggestions in our new landing page hi-fi mockup

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/845?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @Nouri-Anouar @RETprojects

**Comment by Nouri-Anouar** [comment]
@JulieMass I just updated the landing page with the content suggestions both in _[DL - IdeaSpace] UX designs_ and _[DL - IdeaSpace] Prototype_

![image](https://user-images.githubusercontent.com/79311912/227914570-1a03f288-4bbf-4095-911f-70fe06954816.png)

**Comment by Nouri-Anouar** [comment]
Ah! I missed this one, and also updated the padding.
