### ISSUE TITLE
[BUG] GDPR consent component: Update logo to the approved official logo version and broken content showing code

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#857]
### Steps to replicate are
1. Clean your browser cache or open a private window
2. Go to IdeaSpace landing page https://devlaunchers.org/ideaspace 
3. GDPR consent component should appear at the bottom left of the browser

### Device and OS
Desktop & mobile, Browsers: Chrome & Microsoft Edge
### Expected behavior
- Logo should be updated to the approved logo version that appears in the style guide. 
- Text inside the consent form shouldn’t have code.
### Actual behavior 
- GDPR consent component is showing a newer logo version that hasn’t been officially approved
- There is code embedded in the text that can be confusing for the end users (e.g. “(this$(this)?window:this)”) 

---------------------------------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/cac1b2b6-5d67-4ede-88ad-c1c96c53b75d)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/1f61847b-f26f-4f04-9f62-0d6ef871f69d)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/14655ccb-d97a-4e47-98c3-0235d3fcedae)

**Comment by alicefate** [comment]
@JulieMass Hi Julie, I check the code and I think this doesn't belong to our team. The code of it is under apps/app/pages/_app.js, and our team code is under apps/ideaspace . This is a whole website script and the content of policy is store in iubenda(https://www.iubenda.com/en/).  I think you should ask Kris for more information.

**Comment by JulieMass** [comment]
> @JulieMass Hi Julie, I check the code and I think this doesn't belong to our team. The code of it is under apps/app/pages/_app.js, and our team code is under apps/ideaspace . This is a whole website script and the content of policy is store in iubenda(https://www.iubenda.com/en/). I think you should ask Kris for more information.

(CC. @dbradham FYI )

Hi Iris, 

Might it be that the code is located in a different folder because it is a custom component used across all Dev Launcher's website? Can you still update the code in that folder or do you need permissions? 

Also, yes I remember Anwar mentioned we were using a component from iubenda. I don't know how Iubenda works but is it still possible for us to fix the text? @Nouri-Anouar worked on this initially, maybe he can help us here?

**Comment by alicefate** [comment]
@JulieMass It is not a component and not store in our folder. I think it will need iubenda account to change content.

**Comment by Nouri-Anouar** [comment]
@JulieMass I just updated the logo. is this the right one? :sweat_smile:
![image](https://user-images.githubusercontent.com/79311912/227492021-58399959-7d49-4e64-b384-695ce7f11bc0.png)
 
 @dbradham which branch should I branch from for this fix?

**Comment by dbradham** [comment]
@Nouri-Anouar it would be best to use `development/ideaspace` branch if you can, thanks!

**Comment by JulieMass** [comment]
> @JulieMass I just updated the logo. is this the right one? 😅 ![image](https://user-images.githubusercontent.com/79311912/227497407-ec2f2ca2-0a7d-4961-bc81-f9aa32dada8b.png)
> 
> @dbradham which branch should I branch from for this fix?

Thank you so much Anwar! yes, that is the correct one 😀!

Were you able to updated it in this other modal too?

![image](https://user-images.githubusercontent.com/104226366/227631116-f2aecfdd-a55a-4864-b001-c2d2d91ab0b8.png)

**Comment by Nouri-Anouar** [comment]
> > @JulieMass I just updated the logo. is this the right one? 😅 ![image](https://user-images.githubusercontent.com/79311912/227497407-ec2f2ca2-0a7d-4961-bc81-f9aa32dada8b.png)
> > @dbradham which branch should I branch from for this fix?
> 
> Thank you so much Anwar! yes, that is the correct one 😀!
> 
> Were you able to updated it in this other modal too?
> 
> ![image](https://user-images.githubusercontent.com/104226366/227631116-f2aecfdd-a55a-4864-b001-c2d2d91ab0b8.png)

@JulieMass I believe it is fixed now. 
I will ask Dave to review it on Sunday.

![image](https://user-images.githubusercontent.com/79311912/227652866-30a68710-ffdc-4f98-8578-c34dea6a5000.png)

**Comment by JulieMass** [comment]
wow, niiiice 😀!! Looks great Anwar 👏! thank you so much!

**Comment by dbradham** [comment]
<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d317f67378f7a1966c24af10aa3eb7675085cee1/image.png" alt="image.png" />


@JulieMass
