### ISSUE TITLE
[DEV] (User Profile) Limit number of ideas that appear in Ideas section to four

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#862]
![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/726e866f-630b-46e1-8266-63373dbba78f)

**Comment by mujeeb00** [comment]
Got it

**Comment by judeamos** [comment]
The changes you will be making is in the RecommendedIdeas component, located in: `apps/website/src/components/modules/UserProfile/RecommendedIdeas/RecommendedIdeas.js`. 
---
For the implementation, you can speak with @HavreLoic as he worked on a similar story , or contact me for help:

**Comment by judeamos** [comment]
This was implemented and pushed to production, but with will be re-implementing this code for the new User profile page.
