### ISSUE TITLE
[DEV] (User Profile) Implement ProductCardLarge shared component in Projects section of User Profile

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#863]
Code for the User Profile is located at `\apps\website\src\components\modules\UserProfile`, and the specific Projects component lives at `\apps\website\src\components\modules\UserProfile\UserProjects`

The shared component can be viewed and inspected at
https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=organisms-productcardlarge&buildNumber=227&k=640752b163335b849ee2ae4c-1200-interactive-true&h=5&b=-1

To import the shared component, use 

`import ProductCardLarge from '@devlaunchers/components/components/organisms/cards/ProductCardLarge';`

The props able to be passed in to this shared component can be viewed at https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=organisms-productcardlarge&buildNumber=227&k=640752b163335b849ee2ae4c-1200-docs-true&h=6&b=-2

If you'd like to see the code for the component, in the dev-launchers-platform repo/codebase go to the `\packages\UI\src\components\organisms\cards` folder

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
