### ISSUE TITLE
[DEV] (User Profile) Implement PositionCard shared component in Opportunities section of User Profile

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#864]
![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/851f3794-aaf4-4fc8-9ec7-02ae4e6e9d94)

Code for the User Profile is located at `\apps\website\src\components\modules\UserProfile`, and the specific Opportunities component lives at `\apps\website\src\components\modules\UserProfile\Opportunities`

The shared component can be viewed and inspected at
https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=organisms-positioncard--long-a-save-only-closed&buildNumber=225&k=640369f6738e94f26b5eb76e-1200-interactive-true&h=12&b=-11

To import the shared component, use 

`import PositionCard from '@devlaunchers/components/components/organisms/cards/PositionCard';`

The props able to be passed in to this shared component can be viewed at https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=organisms-positioncard&buildNumber=225&k=640369f6738e94f26b5eb76d-1200-docs-true&h=4&b=-3

If you'd like to see the code for the component, in the dev-launchers-platform repo/codebase go to the `\packages\UI\src\components\organisms\cards` folder

**Comment by judeamos** [comment]
This is an older design version. With the latest version, we'll need to reimplement this. Can scrap this.
