### ISSUE TITLE
[DEV] (User Profile) Implement Toggle shared component in Interests section of User Profile

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#866]
Code for the User Profile is located at `\apps\website\src\components\modules\UserProfile`, and the specific UserInterests component lives at `\apps\website\src\components\modules\UserProfile\UserInterests`

The shared component can be viewed and inspected at
https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=atoms-toggle--with-label&buildNumber=227&k=640752b163335b849ee2ade7-1200-interactive-true&h=11&b=-7

To import the shared component, use 

`import Toggle from '@devlaunchers/components/components/atoms/Toggle';`

The props able to be passed in to this shared component can be viewed at https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=atoms-toggle--with-label&buildNumber=227&k=640752b163335b849ee2ade7-1200-docs-true&h=12&b=-8

If you'd like to see the code for the component, in the dev-launchers-platform repo/codebase go to the `\packages\UI\src\components\atoms\Toggle` folder

**Comment by HavreLoic** [comment]
Hey Kris, can I know where exactly on the Interests page section I should put it?

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
