### ISSUE TITLE
[DEV] (UI Library) Fix Navigation shared component to allow signed in users to access their profiles by clicking their profile pictures

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/dev-launchers-platform#867]
![image.png](https://images.zenhubusercontent.com/633e1a5b90f8260b0fcb1579/ca3a63ef-77cb-4244-9c7e-b8359a113290)

You can view and inspect the current state of this component at https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=molecules-navigation--default-nav&buildNumber=225&k=640369f6738e94f26b5eb75b-1200-interactive-true&h=6&b=-5

To access the code for the component, in the dev-launchers-platform repo/codebase go to the `\packages\UI\src\components\organisms\Navigation` folder

**Comment by judeamos** [comment]
We did not fix this issue, it was done by the universal design team i believe, but this is not an issue anymore.
