### ISSUE TITLE
Change Dropdown title from "all caps" to "title case"

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#870]

**Comment by Divine-offishal** [comment]
Hello, can you assign this to me?

**Comment by Enjoy2Live** [comment]
@Nouri-Anouar @JulieMass  is this fixed?

**Comment by Nouri-Anouar** [comment]
@Enjoy2Live  I believe that the issue has been resolved. 
Initially, the problem was identified as the dropdown title being set in uppercase. This has been solved, and the title is now flexible.

**Comment by JulieMass** [comment]
> @Enjoy2Live I believe that the issue has been resolved. Initially, the problem was identified as the dropdown title being set in uppercase. This has been solved, and the title is now flexible.

Thanks for this update @Nouri-Anouar and @Enjoy2Live ! I'll let our team know 👍
