### ISSUE TITLE
[DEV](User Profile) Enable Links to public user profile on the "People tab"

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#880]
User Story:
As a "Nancy Newbie"
I want to explore other dev launchers user profiles
so that I can discover who I might be working with

Acceptance criteria

Given I am viewing the "people tab"
when I hover my mouse over a user card
then the users name should be underlined and the mouse should indicate I can click on the card

Given that I am logged in, viewing my personal user profile, and have the "people" tab, selected
when I click on a user's name and/or picture
then I should be redirected to their public user profile

![Screenshot 2023-03-09 224655.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/6379864d-e39e-4b57-a830-521cdb24eb08)

**Comment by judeamos** [comment]
This is an older design version. With the latest version, we'll need to reimplement this. Can scrap this.
