### ISSUE TITLE
[DEV](User Profile) View only public profile

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#881]
User Story:
As a "Nancy Newbie"
I want to view other users profiles without the ability to edit them
so that I can explore other Dev Launcher Users w/o altering their profile

Acceptance Criteria:
Given that I am viewing a public user profile
when I am viewing the "Bio Section" & the "Interests" tab
then I will not see the edit button & will not be able to click to edit the user interests
![EditButton.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/7ea5dee2-70ea-4939-85c9-8d0154e66f19)

**Comment by judeamos** [comment]
This is an older design version. With the latest version, we'll need to reimplement this.
