### ISSUE TITLE
[Dev](User Profile) Re Organize the User Profile

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#882]
User Story:
As Danny Dev Launcher
I want to view my organized user profile
So that I can begin my Dev Launchers journey

Acceptance Criteria:
Given I am logged into my account
When I am viewing my personal profile page in the fully expanded orientation
Then I will see the updated view
![New User Profile.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/365c0aeb-afbd-46f2-b03a-071e0ed9b42e)

**Comment by judeamos** [comment]
This is from V2, we are now using V4 Figma design. Can scrap this story.

**Comment by judeamos** [comment]
This was pushed to production before we revamped to new user profile design.
