### ISSUE TITLE
[Dev](User Profile) Remove User Bio Border

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#883]
User Story:
As "Dave Developer"
I want the User Bio Dialogue box to blend in with the background
So that I am not distracted by the format of the website and am able to appreciate the features

Acceptance Criteria:
Given I am on the user profile page
when I click on the user bio when not editing
then the dialogue box will not be outlined.
![DiaBox.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/f5a8b732-a099-4cfb-9dbf-af93c4a1e31b)
 ^ Remove this outline^

**Comment by judeamos** [comment]
This change was pushed to production. But this has been completely redesigned with new user profile revamp.
