### ISSUE TITLE
[Dev](User Profile) Change the update bio button

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#894]
User Story:
As Danny Dev Launcher
I want to edit my user bio
So that I can show the Dev Launchers Community who I am

Acceptance Criteria:
Given I am signed in and viewing my personal User Profile
When I do not see the old edit button and click on the new edit button in the same position where the old button was.
Then I will be able to edit my user bio.

The new edit button can be found here
[https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=common-components-button--with-short-text&buildNumber=247&k=640badf3c1d88005453fd5da-1200-interactive-true&h=8&b=-5](url)

![New EditButton.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/a5dc0656-7931-4738-b721-695ab05a0223)

**Comment by judeamos** [comment]
This is an older design version. With the latest version, we'll need to reimplement this. Can scrap this.
