### ISSUE TITLE
[Dev](User Profile) Create Initial Public User Profile

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#895]
**User Story:**
As "Nancy Newbie"
I want to explore other dev launchers user profiles
so that I can discover who I might be working with

**Acceptance Criteria**
Given, I am logged in to my account
when I use a link to another person's user profile
then I will view their public user profile that is a 1:1 copy of the personal user profile

**Note:** the public and personal user profiles should be separate entities to allow for future development

**Possible Blockers:** This may be blocked by an intermediary screen shown when people FIRST sign up, asking them to set a Dev Launchers username. We had this step included at one point, but it was temporarily removed. **The technical lead will investigate this.**

**Technical Requirements**
    - Routing (next.js) - This may require a change in the `pages` structure of the app in order to pass in a parameter based on the username in the url (ie. /users/krisgano vs /users/ethanlevin)
    - API fix - This may require some changes to our API permissions so our backed is able to request the correct data upon request

**Comment by judeamos** [comment]
The URL to access the public profile page is users/public/[id] e.g users/public/6
6 is Kris's user data

**Comment by judeamos** [comment]
This is similar to story #916. We will be creating a new implementation for the new user profile revamp. Old code implementation for this is still there. Can delete this story.
