### ISSUE TITLE
[Dev](User Profile)Circularize the profile photo personal user profile

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#915]
User Story:
As Nancy Newbie
I want to view my profile photo
so that I can ensure I am presenting myself to the dev launchers community

Acceptance Criteria:
Given I am viewing my personal user profile
When I view my profile photo
then it should be encased in a circle with no border, width and height: 128p

![profilephoto.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/a9d55d31-0c2d-4313-9190-1b00ff16e44b)

**Comment by namigoeku** [comment]
Please remove this: "then it should be encased in a circle with a 9px border colored gray (color Hex Key: BDBDBD)
width: 266.35px;
height: 266.35px;" and replace with a circle with no border, width and height: 128px"

**Comment by namigoeku** [comment]
![Capture.JPG](https://images.zenhubusercontent.com/6404cf5641a65b2ee15d40bb/48016d68-072d-4ed2-92e9-7cd7768e226b)

There should also be an option to add an email where the person can be reached.

**Comment by judeamos** [comment]
This has been completed and is in production.
