### ISSUE TITLE
[Dev](User Profile) Create "Edit Profile Picture Button" (button only no functionality)

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#918]
(not finished)
User Story:
As Nancy Newbie
I want to see a button that will allow me to edit my profile picture
so that I know where to edit my profile picture when I decide to

Acceptance Criteria
Given I am viewing my personal user profile
when I look at my profile picture
then I should see the attached button overlaying the profile photo

![Frame 1123.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/33d71da9-82d1-4599-8a51-da57d398d220)![profilephotowbutton.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/620e3b7b-f10b-43ef-8ad7-99f73a6b3ede)

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
