### ISSUE TITLE
[ENHANCEMENT - DEV] As MILES HARDIN, I want to leave comments with no character limit so that I can workshop my idea without restrictions.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#921]
### Considerations
When initially working on fixing this issue in #640 we decided on adding character limits in the comment feed due to technical constraints about comment length. 

We believe this constraint might be fixed at this point, so we would like to improve Miles’s experience removing the character limits to allow him to write messages as short or long as he prefers which might improve quality and quantity of feedback and reduce possible frustrations

### Acceptance criteria:
- Character limits (min and max.) are removed from the Comment Feed allowing Miles to write messages without restrictions.
- Comment feed works well in our target browsers: Chrome and Microsoft Edge.
- Layout is web responsive and it works well for mobile, tablets and desktop breakpoints.

----------------------------------------------------
### Sub-tasks:
- [ ] Development
- [ ] QA
----------------------------------------------------

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/1adf9f5f-7014-4d6a-82f5-833bcd4b2cc3)

**Comment by chadcrotchett** [comment]
"no character limit" is neither feasible or testable. It can be a large number, sure, but not infinity.

**Comment by RETprojects** [comment]
There is no maximum restriction on number of characters on staging.

**Comment by chadcrotchett** [comment]
ready to go
