### ISSUE TITLE
[BUG] Dev Launcher’s rainbow at the top nav height with inconsistent height sizes across the website

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#933]
### Steps to replicate are
1. Go to DL home page https://devlaunchers.org/, IdeaSpace https://devlaunchers.org/ideaspace, the Create page https://devlaunchers.org/create, etc. navigate Dev Launchers website.
2. Observe the height size of the “rainbow” at the top nav. It isn't consistent across the website.

### Device and OS
- Desktop & mobile
- Browsers: Chrome & Microsoft Edge

### Expected behavior
The top nav rainbow should follow the height of our designs and be consistent across Dev Launchers website.

### Actual behavior 
The top nav rainbow height is inconsistent and it doesn't follow our UX design mockups. Please see screenshots below.

---------------------------------------------------------------------------
Rainbow in production:
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/60b4b44c-3f83-4143-86d9-761bbf4c508f)

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/7a652bc2-a5c7-4023-811b-56152f67c936)

Rainbow in [UX designs](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=M3ibemYSIkqKoj8p-1)
![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/223231e3-f142-49a7-9187-51a447da115f)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/933?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @Nouri-Anouar @rashikashaw @RETprojects

**Comment by Abhishek7Tech** [comment]
Hi @JulieMass I would like to contribute!

**Comment by S1ddG** [comment]
Hi! I would love to solve this issue!!!

**Comment by JulieMass** [comment]
> Hi @JulieMass I would like to contribute!

Hey @Abhishek7Tech and @S1ddG 

**Thanks for offering to help us! ** We really appreciate it. :100:  :pray: 

If you are interested in helping us, we would love you to join us! I would recommend you apply to volunteer with our organization and then you could take tasks and work with our team or join other open source teams. We have a lot of **open volunteer opportunities for ambitious developers like you! Please check them out here: https://www.volunteermatch.org/search/org1189675.jsp

**Comment by imsidkg** [comment]
I would like to fix the issue.

**Comment by Abhishek7Tech** [comment]
Hey @JulieMass  just checked the positions all are lead or senior positions and I am looking for a junior position? Can I join as a junior developer.

**Comment by JulieMass** [comment]
> I would like to fix the issue.

**Comment by JulieMass** [comment]
> Abhishek7Tech

Hey 

> Hey @JulieMass just checked the positions, all are lead or senior positions and I am looking for a junior position? Can I join as a junior developer.

Hey thanks for writing back. I’ll send you an email to the account you provided in your Github profile. This one: [abhishektab45@gmail.com](mailto:abhishektab45@gmail.com). I think we can find a way to make it work for you!

**Comment by JulieMass** [comment]
Hey @alicefate as discussed yesterday in our weekly meeting I updated the ticket description so it covers fixing the rainbow across ALL Dev Launchers website to make it consistent. 

Thank you so much again for offering to take all these bugs and tickets! you are rocking it girl! 💪🔥

**Comment by Abhishek7Tech** [comment]
Hi @JulieMass Thanks for contacting me via email. I will join you guys soon.

**Comment by JulieMass** [comment]
Hey @alicefate I checked bugs #932, #936 and this one, in most our target browsers (Chrome, Edge, Opera, etc.,) and everything looks amazing 🤩! great job! 👏👏👏
