### ISSUE TITLE
[BUG] Back button in Idea submission page not showing hand icon while hover with the mouse

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#936]
### Steps to replicate are
1. Go to IdeaSpace > Idea Submission page https://devlaunchers.org/ideaspace/submit 
2. Rollover with the mouse over the back button at the top left.

### Device and OS

- Desktop
- Browsers: Chrome & Microsoft Edge

### Expected behavior
While hovering with the mouse over the back button the cursor should show a hand icon.

### Actual behavior 
While hovering with the mouse on the back button it shows the pointer icon. Please watch the video and screenshot below. 

-----------------------------------------------------------------
https://images.zenhubusercontent.com/225525029/8bcc4084-27bb-4ab1-87b7-46e1c481baff/https___devlaunchers_org_ideaspace_submit___google_chrome_2023_03_18_16_01_37.mp4

![image.png](https://images.zenhubusercontent.com/63400f3d1e79614e45d9ebd9/91e619fd-57ac-4bb8-8df1-4b59f928e050)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/936?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @Nouri-Anouar @rashikashaw @RETprojects

**Comment by nitin1chandani** [comment]
Assign me, I will do it for you.

**Comment by imsidkg** [comment]
I can rectify this issue.
please assign me if nobody is assigned yet.

**Comment by JulieMass** [comment]
> Assign me, I will do it for you.

Hey @nitin1chandani 

**Thanks for offering to help us!**  We really appreciate it. :100:  :pray:  

We started a new sprint with our team yesterday so this ticket has been already assigned. But if you are interested in helping us, we would love you to join us! I would recommend you apply to volunteer with our organization and then you could take tasks and work with our team _or_ join other open source teams. We have a lot of open volunteer opportunities for ambitious developers like you! 

Dev Launchers is an international nonprofit organization so we are all open source volunteers like you. For the moment we only have open positions for Senior devs but we’ll soon be opening more positions! If interested,  I would recommend you apply at the link below: https://www.volunteermatch.org/search/org1189675.jsp 

Thank you so much again and hopefully we’ll hear from you again!
