### ISSUE TITLE
[Dev](User Profile) "Member Since" profile information Public and Personal User Profile

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#937]
User Story:
As Dave Developer
I want to see when my team members and myself started with "Dev Launchers"
So that I can familiarize myself with everybody's experience level

Acceptance Criteria
Given I am viewing either my personal user profile or someone's public user profile
when I am looking underneath the user profile photo
then I will see text saying "Member Since Month YYYY" centered underneath the user profile photo
Note: Text should be the same size as the user bio![New User Profile.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/519ab848-2a21-455b-9276-b6f960d0d263)

**Comment by judeamos** [comment]
This is from V2, we are now using V4 Figma design. Can scrap this story.
