### ISSUE TITLE
[Dev](Registration) First time user Interests Selection component creation

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#938]
User Story:
As Nancy Newbie
I want to select topics I may be interested in during my initial onboarding
So that I can be better recommended people and topics

Acceptance Criteria:

Given I am on the interest selection page
when I select an interest
then color of the text and box will invert

Note:
see "people" tab in user profile for functionality example

![interests-modified.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/456724fa-513b-4a9d-93e4-9aec8e90bd31)

**Comment by judeamos** [comment]
This story is a continuation of #965. Please contact me for implementation, as there's the possibility of creating a new component UserInterest component specifically for this page. The UserInterest component used in the UserProfile page is specifically tied to that page.

**Comment by judeamos** [comment]
This story is going to be closed, as there's a new story to remove this page: #981.
