### ISSUE TITLE
[Dev](Registration) First time user data collection

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#939]
User Story:
As Nancy Newbie
I want to enter my user information
so that my user profile will be filled in when I first see it

Acceptance Criteria:
Given I am viewing the information page
When I click on "Terms of Service" or "Privacy Policy"
then I will be redirected to 
https://devlaunchers.org/page/terms-and-conditions
https://devlaunchers.org/page/privacy-policy
respectively

Given I have filled in my information and not checked the "Terms of service" Checkbox
when I click the continue button
then I will be prompted with an error message reading "You must read and accept the Terms of Service and Privacy policy to continue"

Given I have been redirected to the information page
when I enter the information noted below & have selected the terms and conditions checkbox
then my data will be saved & I will be redirected to the "Interests" selection page

![onboarding.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/bfb6c2cb-66c6-45c8-a2e1-07df2d1f0528)

**Comment by judeamos** [comment]
All the sub-components e.g input field, bio box, check box, are already created components.

1. input field component located at _packages/UI/src/components/organisms/FormField_ 
2. checkbox _packages/UI/src/components/atoms/Checkbox_
3. Bio box _packages/UI/src/components/organisms/OpenResponse_  
4. Links _packages/UI/src/components/atoms/Link_

**Comment by judeamos** [comment]
@HavreLoic Good question Havre. @ethanzlevin Theres two ways of handling this: 
1. Show an error message when the user clicks on the continue button and the user has not checked the checkbox
2. Disabled the continue button until the user has checked the checkbox.
