### ISSUE TITLE
[Dev](User Profile) Implement recommended people selection system

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#940]
User Story:
As Danny Dev Launcher
I want to be recommended relevant people
so that I can see people with similar interests 

Acceptance Criteria:
Given I have the "People" Tab Open
When I view the people cards
then 6 people will be recommended to me based on shared interests

Note:
the system to select recommended people should match based on shared interests
each person will have a "relevance score" relative to the signed-in user. Each interest that matches the user's selected interests will increase the "relevance score" by one. the 6 highest relevance scores will determine the recommended users. tie breakers should be random. 

Example
[https://app.zenhub.com/files/225525029/fc855a21-b023-40b9-a157-ad679fe8ee29/download](https://app.zenhub.com/files/225525029/fc855a21-b023-40b9-a157-ad679fe8ee29/download)

**Comment by judeamos** [comment]
Note**: Chung-ting is still in the process of reviewing this user story. Its gonna be a slow process.

**Comment by judeamos** [comment]
PR has been approved by the backend team @ethanzlevin, moving this to QA.

**Comment by KaitlynMallare** [comment]
No longer needed - deleting/closing as not planned
