### ISSUE TITLE
[Dev](Registration) First time user data collection BE

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#946]
User Story:
As Nancy Newbie
I want to enter my user information
so that my user profile will be filled in when I first see it

Acceptance Criteria
Given I have input my first and last name in the two separate input boxes
when I click continue and my information is saved
then the First and Last name with concatenate into my Username

**Comment by judeamos** [comment]
This is for the onboarding page. Code already in production.
