### ISSUE TITLE
[Dev](Registration) First time user data collection page creation

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#947]
User Story:
As Nancy Newbie
I want to enter my user information
so that my user profile will be filled in when I first see it

Acceptance Criteria:
Given I am creating my account/signing in for the first time
when I have selected my Google account to create my profile
then I will be redirected to "Onboarding" page

**Comment by judeamos** [comment]
@HavreLoic 

- [ ] Create a new folder in the modules **_apps/website/src/components/modules_** folder called UserOnboarding, which will be the page component name.
- [ ] Following the UserProfile structure, create index.js, StyledUserOnboarding.js, and UserOnboarding.js files. 
- We can talk about next.js routing on a call

**Comment by HavreLoic** [comment]
I have done it in the same branch as  [#939](https://app.zenhub.com/workspaces/hello-world-team-63fbeb395997506a79321dd2/issues/gh/dev-launchers/dev-launchers-platform/939)
The branch name is havreloic-first-time-user-data-collection-939
