### ISSUE TITLE
[Dev](Registration) First Time User Interests next page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#965]
User Story:
As Nancy Newbie
I want to, on the same webpage, enter my interests after entering my initial data 
So that I can fill in my interests and be presented with recommendations

Acceptance Criteria:
Given I have entered all of my information and accepted the terms and conditions
when I select continue
then the page, without reloading to a new page, will have space available to enter my interests.

Given I have entered all of my information and accepted the terms and conditions
when I select continue
then the data I previously entered will be saved locally

**Comment by judeamos** [comment]
This story is similar to #947. Please contact me to talk about the implementation. 
To summarise changes you need to make: 
1. You will be working with next.js routing to route to the correct path URL e.g devlaunchers.com/onboarding/interests
      - We will discuss possible implementation for the URL

2. You will be creating a new folder within the _website/src/components/module_ folder similar to that of the UserProfile folder

3. You will use the context API hook provided by react to store the data entered. 
      - There will be a functionality where users can navigate back to the information page (#947), and the data 
          entered on that page must be available.

**Comment by judeamos** [comment]
This page should only be accessible after they've signed up, and can only be completed once.
I will confirm with @pyxld-kris, if there's any indicator we can use from the backend to determine whether the user has completed it.

**Comment by judeamos** [comment]
This story is going to be closed, as there's a new story to remove this page: #981.
