### ISSUE TITLE
[Dev](Registration) Continue to profile page after interests selection

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#966]
User Story:
As Nancy Newbie
I want to view my user profile after I have selected my interests
so that I can begin my DevLaunchers Journey

Acceptance Criteria

Given I have selected my interests
when I click on the continue button placed in the bottom right corner of the screen
then my selected interests & profile information will be saved & I will be redirected to my profile page at www.devlaunchers.orgs/users/me

https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=atoms-button--primary-large&buildNumber=264&k=6411c502415bc08351b2f4a0-1200-interactive-true&h=8&b=-5

**Comment by judeamos** [comment]
This is a continuation of #938. 

1. When the user clicks on the continue button the data stored in the context API needs to be sent to the backend to update the user profile. 
      - This involves mapping the data from the context API to fit the request body, ready to be sent to the backend.
---
2. when data has _successfully_ been sent, then navigate the user to the private profile page _devlaunchers/users/me_
