### ISSUE TITLE
[Dev](Registration)User Interests back button

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#968]
As Nancy Newbie
I want to go back to the information collection page from the interests selection page
so that I can change my Name or Bio

Acceptance Criteria:
Given I am on the interests selection page
when I click on the "Back" button placed in the bottom left
then I will be directed back to the information collection page with my previous data filled in
![interests-modified.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/3f9c3e18-b35c-4481-9e6e-cd57b1f376cc)

https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=atoms-button--secondary&buildNumber=264&k=6411c502415bc08351b2f4a2-1200-interactive-true&h=2&b=5

**Comment by judeamos** [comment]
This is a continuation of #938.  We're simply navigating back to the first page #939. 
The context api should have been set up during #938 to store the data, so on landing back on the first page, form elements should be prepopulated data they last entered.
