### ISSUE TITLE
[Dev](User Profile) Onboarding Modal Creation

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#978]
User Story:
As Nancy Newbie
I want a modal to display on the user profile page the very first time I view it
So that I can continue to be directed on the onboarding process

Acceptance Criteria
Given I have entered my user info in the "information collection" page
when I am redirected to my personal user profile page for the first time
then a blank modal will be created on top of the user profile page.

**Comment by ethanzlevin** [comment]
https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/Hello-World-Project?node-id=237-2662&t=dAoUPd2pBYfY6rz1-0

**Comment by judeamos** [comment]
This has been completed and is in production.
