### ISSUE TITLE
[Dev](User Profile) Onboarding Modal Styling

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#979]
User Story
As Nancy Newbie
I want the onboarding modal to have styling
so that the DevLaunchers brand is communicated to me

Acceptance Criteria
Given I am viewing my user profile for the first time
when the onboarding modal appears
The styling will match the image below
Rounded Corners
Black DevLaunchers header
"Get Started with Dev Launchers" Heading Text
"Please complete the following onboarding tasks" Sub Heading Text
![onboardingmodal.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/e17005aa-16d9-4636-8169-0baeaf54a4a7)
Note: See for styling specifics https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/Hello-World-Project?node-id=237-2662&t=HmAUIHAS86L9qJAI-0

**Comment by judeamos** [comment]
This is dependent on #978 being completed. Please contact me for implementation.

**Comment by judeamos** [comment]
This is from V2, we are now using V4 Figma design. Can scrap this story.
