### ISSUE TITLE
[Dev](User Profile) Onboarding Modal Progress Indicator

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#980]
User Story
As Nancy Newbie
I want to track my progress
So that I know how far along I am with the onboarding process

Acceptance Criteria:
Given I am viewing the onboarding Modal
When I look under the subheader & to the right of the header text
Then I will see the Progress Indicator

Given I am viewing the onboarding modal
When I complete a task
then the progress indicator will progress by a quarter![onboardingmodal.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/8b223be5-1225-4291-824a-d2a11bca0faf)

Note: For styling details see https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/Hello-World-Project?node-id=237-2662&t=HmAUIHAS86L9qJAI-0

**Comment by judeamos** [comment]
This story is dependent on a lot of stories being completed: #978, #981, #979, #982, #984, #985.
Once those stories are completed, contact me for implementation.
