### ISSUE TITLE
[Dev](User Profile) Update onboarding flow, remove "interests" page

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#981]
User Story
As Nancy Newbie
I want to move directly to my personal user profile after completing the "information page"
So that I can move forward on the onboarding process

Acceptance Criteria:
Given I have entered my user profile information & accepted the terms and conditions
when I click continue
I will be redirected to www.Devlaunchers.org/users/me

**Comment by judeamos** [comment]
This has been completed and is in production.
