### ISSUE TITLE
[Dev](User Profile) Create Onboarding Card Component

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#982]
User Story:
As Nancy Newbie
I want uniformly designed "cards" that outline the steps I need to complete to finish the onboarding process
So that I can better understand what is expected of me
Acceptance Criteria:

Given the onboarding step is NOT completed
when I am viewing the onboarding modal main page
then the onboarding card will be white, have drop shadow, and an empty circle on the right

Given the onboarding step is completed
when I return to the onboarding modal main page
then the onboarding card will be greyed out, and the circle will be filled with a checkmark.
Note:
Component in either variation should have a configurable photo on the left, to the right of the photo should be a heading text and a subheading text.
![onboardingmodal.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/e51f1c0f-451b-4dfd-8d64-80272d29756f)

**Comment by ethanzlevin** [comment]
https://www.figma.com/file/maDULycPMZpl6t1aRJjsac/Hello-World-Project?node-id=237-2662&t=dAoUPd2pBYfY6rz1-0

**Comment by judeamos** [comment]
Please contact me before starting this as this is dependent on: #978

**Comment by judeamos** [comment]
This is from V2, we are now using V4 Figma design. Can scrap this story.
