### ISSUE TITLE
[Dev](User Profile) First Oboarding card

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#984]
User Story:
As Nancy Newbie
I want to see the first onboarding card in its completed mode
so that I can tell, I have finished the first steps in the onboarding process

Acceptance Criteria
Given the onboarding card is filled in with the following
Image: User Circle
Heading Text: Create DevLaunchers Login
Sub Heading text: All Set! Let's Get Started With The Rest.
When I first enter the onboarding modal
Then this onboarding card should be set to its "completed" mode

![UserCircle.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/b3c5afcf-1b9b-4d5f-a071-27eb5f710679)

**Comment by judeamos** [comment]
This is dependant on #982 being completed, so either speak to me or the person who worked on that story.

**Comment by judeamos** [comment]
@ethanzlevin Should this be in QA?

**Comment by judeamos** [comment]
This is V2 design change, we are now using V4. This story can be scrapped.
