### ISSUE TITLE
[Dev](User Profile) Second Onboarding Card

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#985]
User Story:
As Nancy Newbie
I want to see a second onboarding card in its "incomplete" mode
so that I understand my next steps

Given the onboarding card is filled in with the following
Image: 
![Vector.png](https://images.zenhubusercontent.com/6404cf78eb446cd49a9a130a/deb8d9ef-741e-4fb2-8f3b-23e4b7f62aea)
Heading Text: Platform Onboarding
Sub Heading text: Here's a bit of what DevLaunchers has to offer!
When I first enter the onboarding modal
Then this onboarding card should be set to its "incomplete" mode

**Comment by judeamos** [comment]
This is dependent on #982 being completed, so either speak to me or the person who worked on that story for guidance.
This is also dependent on #981 being completed as well. Data must be passed using next.js from the first-time data collection page. Contact me for support on this.

**Comment by judeamos** [comment]
Hey @ethanzlevin, this is done, should this be in QA?

**Comment by judeamos** [comment]
This is from V2, we are now using V4 Figma design. Can scrap this story.
