### ISSUE TITLE
[Dev](User Profile) Third Onboarding Card

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#987]
User Story:
As Nancy Newbie
I want to see a third onboarding card in its "incomplete" mode
so that I understand my next steps

Given the onboarding card is filled in with the following
Image:
https://www.chromatic.com/component?appId=632ca21aeea1618b7fa0bf48&csfId=molecules-socialiconbutton--github&buildNumber=304&k=64284fe38b7b4c8bb8f90d05-1200-interactive-true&h=4&b=-2
Heading Text: Link Your Github
Sub Heading text: Check Out What We're Working On
When I first enter the onboarding modal
Then this onboarding card should be set to its "incomplete" mode

**Comment by judeamos** [comment]
This is similar to #984, in this case, the state of the component will be incomplete.

This is also dependent on #982 being completed, so either speak to me or the person who worked on that story for guidance on how to use the component.

**Comment by judeamos** [comment]
Hey @ethanzlevin, this is done, should this be in QA?

**Comment by judeamos** [comment]
This is from V2, we are now using V4 Figma design. Can scrap this story.
