### ISSUE TITLE
[Dev](User Profile) Edit the Third Onboarding Card

### ISSUE THREAD

**Issue by ethanzlevin** [dev-launchers/dev-launchers-platform#988]
TBD

**Comment by judeamos** [comment]
This is similar to #984, in this case, the state of the component will be incomplete.

This is also dependent on #982 being completed, so either speak to me or the person who worked on that story for guidance on how to use the component.

**Comment by judeamos** [comment]
Can scrap this story. Not sure what this was for, believe this was V2 figma design.
